### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1000]
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 540, in _start_runner
    self._runner.start()
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 102, in start
    self.restart_backend(False, True)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 557, in restart_backend
    self._proxy = backend_class(clean)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 1227, in _init_
    super().__init__(clean, get_interpreter_for_subprocess())
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 1057, in _init_
    super().__init__(clean, executable)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 771, in _init_
    self._start_background_process(clean=clean)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 831, in _start_background_process
    **extra_params
  File "C:\Program Files (x86)\Thonny\lib\subprocess.py", line 800, in _init_
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Thonny\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 87] The parameter is incorrect
```

May be related to https://bugs.python.org/issue37549

**Comment by aivarannamaa** [comment]
Windows 10 home. Thonny 3.2.3. 

> Try with Polish

**Comment by aivarannamaa** [comment]
https://github.com/python/cpython/issues/80394
