### ISSUE TITLE
thonny throws exception when saving file 

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#1042]
details:

```
Traceback (most recent call last):
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/workbench.py", line 1598, in event_generate
    handler(event)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 790, in on_local_file_operation
    self.refresh_tree()
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 640, in refresh_tree
    self.render_children_from_cache("")
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 382, in render_children_from_cache
    self.request_dirs_child_data(node_id, self.get_open_paths() | {path})
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 765, in request_dirs_child_data
    self.render_children_from_cache(node_id)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 444, in render_children_from_cache
    self.render_children_from_cache(child_id)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 382, in render_children_from_cache
    self.request_dirs_child_data(node_id, self.get_open_paths() | {path})
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 765, in request_dirs_child_data
    self.render_children_from_cache(node_id)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/base_file_browser.py", line 402, in render_children_from_cache
    raise RuntimeError("None data for %s" % path)
RuntimeError: None data for /home/benutzer/repo/pyfileguard/monty.txt
```

**Comment by aivarannamaa** [comment]
Thank you for the report!

Does it happen when you save a file in your program or when saving Python script with Thonny?

Can you give me exact steps how to reproduce this?

**Comment by kr-g** [comment]
during save of a file in thonny.
happened one evening, also after restarting thonny it appeared again.
i also can _not_ reproduce it now.
