### ISSUE TITLE
Error when trying to read directory on ESP8266

### ISSUE THREAD

**Issue by riteman** [thonny/thonny#1070]
Traceback (most recent call last):
  File "C:\Users\ritem\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1594, in event_generate
    handler(event)
  File "C:\Users\ritem\AppData\Local\Programs\Thonny\lib\site-packages\thonny\base_file_browser.py", line 875, in update_dir_data
    self.cache_dirs_child_data(msg["data"])
  File "C:\Users\ritem\AppData\Local\Programs\Thonny\lib\site-packages\thonny\base_file_browser.py", line 318, in cache_dirs_child_data
    for parent_path in data:
TypeError: 'NoneType' object is not iterable

I erased the flash and re-installed micropython: Same result

**Comment by sinayg** [comment]
Same here: 
can't see the directory and when trying to upload a file:
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
AttributeError: 'module' object has no attribute 'size'
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 2, in <dictcomp>
AttributeError: 'module' object has no attribute 'size'
PROBLEM WITH THONNY'S BACK-END:

Traceback (most recent call last):
  File "C:\Users\sinay\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 340, in handle_command
    response = handler(cmd)
  File "C:\Users\sinay\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 729, in _cmd_get_dirs_child_data
    root_data = {name: {"kind": "file", "size": size} for (name, size) in sizes.items()}
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by aivarannamaa** [comment]
@sinayg, which device are you using?

**Comment by sinayg** [comment]
Esp32 via USB

Sinay +972-545-506-412

**Comment by aivarannamaa** [comment]
Please try Thonny 3.3 and reopen if you're still having problems

**Comment by sinayg** [comment]
thank you. will try
Sinay
+972 545 506 412
