### ISSUE TITLE
Error when read a file on ESP32

### ISSUE THREAD

**Issue by ChristianFrench** [thonny/thonny#1096]
Hello,
When I "Open" a file on ESP32, there is a bug after a lopp without end :

Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 969, in dispatch_from_menu
    dispatch(None)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 911, in dispatch
    handler()
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 700, in _cmd_open_file
    self.show_file(path, propose_dialog=False)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 813, in show_file
    editor = self.get_editor(filename, True)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 898, in get_editor
    return self._open_file(filename)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 885, in _open_file
    editor._load_file(filename)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 157, in _load_file
    self._load_remote_file(filename)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 200, in _load_remote_file
    if response.get("error"):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by aivarannamaa** [comment]
Does it happen always?

**Comment by ChristianFrench** [comment]
No, usually after some CTRL-C or D, some other opérations, an example without this 

![image](https://user-images.githubusercontent.com/60058707/75360380-00447500-58b6-11ea-9270-7af0df9e1125.png)

**Comment by GlebDen** [comment]
I've got this one error when reboot esp32:
```
Traceback (most recent call last):
  File "E:\thonny-3.2.7-windows-portable\lib\site-packages\thonny\workbench.py", line 1598, in event_generate
    handler(event)
  File "E:\thonny-3.2.7-windows-portable\lib\site-packages\thonny\base_file_browser.py", line 872, in update_dir_data
    self.cache_dirs_child_data(msg["data"])
  File "E:\thonny-3.2.7-windows-portable\lib\site-packages\thonny\base_file_browser.py", line 315, in cache_dirs_child_data
    for parent_path in data:
TypeError: 'NoneType' object is not iterable
```

**Comment by aivarannamaa** [comment]
Should be fixed in the latest beta. Please reopen if still a problem
