### ISSUE TITLE
Raspberry Pi 3 using Stretch OS Debug issue

### ISSUE THREAD

**Issue by jimtal001** [thonny/thonny#1110]
When trying to use the Debug Current script command I get the following error:

PROBLEM WITH THONNY'S BACK-END:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1208, in execute_source
    root = self._prepare_ast(source, filename, mode)
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 1531, in _prepare_ast
    self._tag_nodes(root)
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 2111, in _tag_nodes
    last_child = ast_utils.get_last_child(node)
  File "/usr/lib/python3/dist-packages/thonny/ast_utils.py", line 126, in get_last_child
    and hasattr(node.slice, "step")
AssertionError

**Comment by aivarannamaa** [comment]
Thank you for the report!

Please post your Thonny version and the code you are trying to debug.
