### ISSUE TITLE
thonny crashes on shell > clear

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#1118]
thonny crashes on shell > clear

happend several times today.
no idea how to reproduce (sorry, but maybe the traceback helps...)

Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/shell.py", line 1268, in _clear_shell
    self._clear_content(end_index)
  File "/home/benutzer/.local/lib/python3.6/site-packages/thonny/shell.py", line 1361, in _clear_content
    btn_pos = float(self.index(btn))
ValueError: could not convert string to float: 

thonny version 3.2.7
on linux (64bit), python 3.6.9 (64bit), tk 8.6.8

**Comment by aivarannamaa** [comment]
Thank you for the report!
This seems to be duplicate of #1091

**Comment by kr-g** [comment]
last time it happened during argparse. 
no "squeezed" content here.

**Comment by aivarannamaa** [comment]
Alright, I leave it open then.

**Comment by kr-g** [comment]
it did not occur again ...

**Comment by aivarannamaa** [comment]
Duplicate of #1091
