### ISSUE TITLE
internal erro when using pip-gui

### ISSUE THREAD

**Issue by zjuxumang** [thonny/thonny#1125]
After open the package manager and click one of the installed packages, the window lose response and seconds later an erro message was shown.
The full message is shown as below
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 1188, in poll_fetch_complete
    completion_handler(name, json.loads(raw_data))
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 488, in _show_package_info
    self._set_state("idle")
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 223, in _set_state
    self.config(cursor="")
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!backendpipdialog2"
```

**Comment by aivarannamaa** [comment]
Thank you for your report!

Does it happen all the time or only with a specific sequence of actions?
