### ISSUE TITLE
I can't install the packages "torch" or "pytorch"

### ISSUE THREAD

**Issue by giovanibcogo** [thonny/thonny#1127]
```
_Collecting pytorch
  Downloading pytorch-1.0.2.tar.gz (689 bytes)
Installing collected packages: pytorch
    Running setup.py install for pytorch: started
    Running setup.py install for pytorch: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'E:\programs\Python377\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GIOVAN~1.BOL\\AppData\\Local\\Temp\\pip-install-dhg0s3_a\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\GIOVAN~1.BOL\\AppData\\Local\\Temp\\pip-install-dhg0s3_a\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GIOVAN~1.BOL\AppData\Local\Temp\pip-record-c152h98d\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\giovani.bolzan\AppData\Roaming\Python\Python37\Include\pytorch'
         cwd: C:\Users\GIOVAN~1.BOL\AppData\Local\Temp\pip-install-dhg0s3_a\pytorch\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GIOVAN~1.BOL\AppData\Local\Temp\pip-install-dhg0s3_a\pytorch\setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\programs\Python377\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GIOVAN~1.BOL\\AppData\\Local\\Temp\\pip-install-dhg0s3_a\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\GIOVAN~1.BOL\\AppData\\Local\\Temp\\pip-install-dhg0s3_a\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GIOVAN~1.BOL\AppData\Local\Temp\pip-record-c152h98d\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\giovani.bolzan\AppData\Roaming\Python\Python37\Include\pytorch' Check the logs for full command output.

Process failed, return code: 1_

```
This is the message from the Manage Packages tool. And I couldn't even install it manually.

**Comment by aivarannamaa** [comment]
I found this thread: https://discuss.pytorch.org/t/trying-to-install-pytorch-from-local-package/57343

It looks like you need to download whl-file and install it (Look for "Install from local file" in Thonny's Manage Package dialog)
