### ISSUE TITLE
Thonny doesn't like f-expressions

### ISSUE THREAD

**Issue by andrastantos** [thonny/thonny#1151]
Version 2.1.16 on 64-bit Linux. Python 3.6.9 Tk 8.6.8.

Repro:

1. Type in the following code:
print(f"my answer to you is {42}")

2. Debug (Ctrl-F5)

Expected behaviour:
code executed without errors

Actual behaviour:
code executes, but errors are reported:

>>> %Debug test.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/shared/thonny/ast_utils.py", line 178, in _mark_text_ranges_rec
    tokens = _mark_end_and_return_child_tokens(node, tokens, prelim_end_lineno, prelim_end_col_offset)
  File "/usr/lib/python3/dist-packages/thonny/shared/thonny/ast_utils.py", line 263, in _mark_end_and_return_child_tokens
    _strip_trailing_junk_from_expressions(tokens)
  File "/usr/lib/python3/dist-packages/thonny/shared/thonny/ast_utils.py", line 202, in _strip_trailing_junk_from_expressions
    while (tokens[-1].type not in (token.RBRACE, token.RPAR, token.RSQB,
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/shared/thonny/ast_utils.py", line 178, in _mark_text_ranges_rec
    tokens = _mark_end_and_return_child_tokens(node, tokens, prelim_end_lineno, prelim_end_col_offset)
  File "/usr/lib/python3/dist-packages/thonny/shared/thonny/ast_utils.py", line 263, in _mark_end_and_return_child_tokens
    _strip_trailing_junk_from_expressions(tokens)
  File "/usr/lib/python3/dist-packages/thonny/shared/thonny/ast_utils.py", line 202, in _strip_trailing_junk_from_expressions
    while (tokens[-1].type not in (token.RBRACE, token.RPAR, token.RSQB,
IndexError: list index out of range

**Comment by andrastantos** [comment]
For people who are maybe running this in the future: this has been fixed already, only Unbuntu didn't pick up a recent enough version.
