### ISSUE TITLE
same problem post #936 error with write files "PROBLEM WITH THONNY'S BACK-END: "

### ISSUE THREAD

**Issue by patfrench** [thonny/thonny#1161]
Hi,

Excuse me i have posted in the closed subject
 
I have a same problem with nucleo411RE. I have to install Thonny v3.2.7.
The fix are already ok in this version ?

i have same problem with ESP-WROVER-KITv3 but never problem with ESP32-WROOM.

I don't understand. The firmware for ESP32 come of 
https://micropython.org/download/esp32/
and 
https://micropython.org/download/stm32_nucleo/NUCLEO_F411RE-20200416-v1.12-371-gf534b9976.dfu for my nucleo411RE

I try too change size of block but it's not working.

Thank you

```PROBLEM WITH THONNY'S BACK-END:

Traceback (most recent call last):
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 35, in read
    self._read_buffer.extend(self._read_queue.get(True, timer.time_left))
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 340, in handle_command
    response = handler(cmd)
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 864, in _cmd_upload
    written_bytes = self._upload_file(item["source"], item["target"], notify)
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 1461, in _upload_file
    return self._write_file(block_generator(), target, notifier=notifier)
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 1094, in _write_file
    result = self._write_file_via_serial(content_blocks, target_path, notifier)
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 1166, in _write_file_via_serial
    self._execute_without_output(script)
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 444, in _execute_without_output
    out, err, value = self._execute(script, capture_output=True)
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 438, in _execute
    ok = self._connection.read(2)
  File "C:\Users\Ppetit\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 37, in read
    raise TimeoutError("Reaction timeout. Bytes read: %s" % self._read_buffer)
TimeoutError: Reaction timeout. Bytes read: bytearray(b'')```

**Comment by aivarannamaa** [comment]
Sorry, I've somehow missed your report.

Please try Thonny 3.3 and reopen if you still have problems
