### ISSUE TITLE
Unexpected internal error `in event_generate handler(event)`

### ISSUE THREAD

**Issue by villares** [thonny/thonny#1204]
I think it might be related to have left the *Plotter* panel open. Unable to reproduce.
```
Traceback (most recent call last):
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/workbench.py", line 1598, in event_generate
    handler(event)
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 231, in text_inserted
    self.update_plotter()
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 235, in update_plotter
    self.plotter.update_plot()
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 1659, in update_plot
    self.update_legend(data_lines, force_clean)
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 1732, in update_legend
    fill=self.colors[i - 1 % len(self.colors)],
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 217, in set_scrollbar
    self.update_plotter()
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 235, in update_plotter
    self.plotter.update_plot()
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 1659, in update_plot
    self.update_legend(data_lines, force_clean)
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 1732, in update_legend
    fill=self.colors[i - 1 % len(self.colors)],
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 217, in set_scrollbar
    self.update_plotter()
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 235, in update_plotter
    self.plotter.update_plot()
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 1659, in update_plot
    self.update_legend(data_lines, force_clean)
  File "/home/villares/.local/lib/python3.6/site-packages/thonny/shell.py", line 1732, in update_legend
    fill=self.colors[i - 1 % len(self.colors)],
IndexError: list index out of range
```

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll look into this.
