### ISSUE TITLE
Can't choose Micropython interpreter with Thonny 3.2.7

### ISSUE THREAD

**Issue by G-Boronad** [thonny/thonny#1237]
Hye, 
I have only three possibility in the options, there is no  ESP32, ESP8266 or microbit Interpreter.
![Sans titre 1](https://user-images.githubusercontent.com/63054170/84416748-e9335400-ac14-11ea-9f41-9f3c4598c665.jpg)

Thanks

**Comment by aivarannamaa** [comment]
Please select "Tools => Open Thonny data folder" (or whatever it is in French), close Thonny and check whether there is anything in frontend.log or frontend_faults.log

**Comment by aivarannamaa** [comment]
Also, make sure you really have Thonny 3.2.7 (Help => About)

**Comment by G-Boronad** [comment]
Hello, 
Here my version:
![image](https://user-images.githubusercontent.com/63054170/84520827-6bcf1880-acd4-11ea-96a4-8b12fc3570b0.png)
My log files are empty:
![image](https://user-images.githubusercontent.com/63054170/84520910-8c976e00-acd4-11ea-93bd-d49b8013a313.png)
Thanks

**Comment by aivarannamaa** [comment]
Can you try following:

* close Thonny
* Open system command prompt (open start menu, type `cmd` and press enter)
* enter following command `cd %LOCALAPPDATA%\Programs\Thonny` (if you installed for yourself) or `cd "C:\Program Files (x86)\Thonny"` (if you installed for all users)
* enter `python -m thonny`
* Select "Run => Select interpreter"
* Check the command propmt window. If there are some error messages then please paste them under this issue.

**Comment by G-Boronad** [comment]
We can see these  error messages when i run thonny in prompt:

Microsoft Windows [version 10.0.18363.900]
(c) 2019 Microsoft Corporation. Tous droits réservés.

C:\Users\hp>cd "C:\Program Files (x86)\Thonny"

C:\Program Files (x86)\Thonny>python -m thonny
ERROR:root:Failed loading plugin 'thonny.plugins.circuitpython'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\circuitpython\__init__.py", line 5, in <module>
    from thonny.plugins.micropython import (
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'
ERROR: Failed loading plugin 'thonny.plugins.circuitpython'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\circuitpython\__init__.py", line 5, in <module>
    from thonny.plugins.micropython import (
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'
ERROR:root:Failed loading plugin 'thonny.plugins.esp'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\esp\__init__.py", line 1, in <module>
    from thonny.plugins.micropython import (
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'
ERROR: Failed loading plugin 'thonny.plugins.esp'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\esp\__init__.py", line 1, in <module>
    from thonny.plugins.micropython import (
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'
ERROR:root:Failed loading plugin 'thonny.plugins.microbit'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\microbit\__init__.py", line 3, in <module>
    from thonny.plugins.micropython import (
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'
ERROR: Failed loading plugin 'thonny.plugins.microbit'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\microbit\__init__.py", line 3, in <module>
    from thonny.plugins.micropython import (
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'
ERROR:root:Failed loading plugin 'thonny.plugins.micropython'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'
ERROR: Failed loading plugin 'thonny.plugins.micropython'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 394, in _load_plugins_from_path
    m = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Thonny\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 24, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'

thanks for your help

**Comment by aivarannamaa** [comment]
That's weird -- it looks like for some reason Thonny can't find a library which comes with Thonny's installer.

Do you happen to have a script named `serial.py` in your working directory? If yes, then try renaming it and restarting Thonny.

**Comment by G-Boronad** [comment]
Here is my directoty named "serial:
![image](https://user-images.githubusercontent.com/63054170/84999493-84ff1b80-b151-11ea-89d7-52a323b94fb3.png)
I try to renamed it but it doesn't change anything.
I don't have any "serial.py" script.

**Comment by aivarannamaa** [comment]
I assume this directory is under Thonny's installation directory.

Please also check which packages you have in your user package directory. In order to open this, select "Tools => Manage plug-ins" and click the link under "Target ___" (in the lower part of the dialog). Do you have something named "serial" there?

**Comment by G-Boronad** [comment]
I see a stuf,
My installation directory  with serial directory is :
C:\Users\hp\AppData\Local\Programs\Thonny\
My python default interpreter is:
![image](https://user-images.githubusercontent.com/63054170/85014738-217fe880-b167-11ea-9565-fb70a6266aba.png)
But, my plugins folder is C:\Users\hp\AppData\Roaming\Python\Python37\site-packages. And the  serial plugin is installed  in this directory.
![image](https://user-images.githubusercontent.com/63054170/85015034-96532280-b167-11ea-86f1-26212396bc98.png)

**Comment by aivarannamaa** [comment]
I guess we found the reason. This package shadows the package with the same name, which is required by Thonny's MicroPython support. They have different PyPI names (`serial` vs `pyserial`), but same module names (`serial`).

If need this package under user packages, the I don't have a solution. If you can use it in a virtual environment, then uninstall it from user packages and restart Thonny.

If you need this package

**Comment by G-Boronad** [comment]
I uninstalled serial plugins (i used this plugin to communicate between an arduino and a python program) and it works. Now I can see  micropython interpreters.
Perhaps il will be possible to change module name for micropython interpreter in a next version of Thonny
Thanks for your help.
G.B.

**Comment by aivarannamaa** [comment]
> i used this plugin to communicate between an arduino and a python program

I'm afraid you have confused something. [According to PyPI](https://pypi.org/project/serial/), this package is "A framework for serializing/deserializing JSON/YAML/XML into python class instances and vice versa"

PySerial is for serial communication and I can't change its name.

**Comment by dsl400** [comment]
is this the same problem ?

`Traceback (most recent call last):
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\backend_config_page.py", line 122, in _backend_changed
    page = self._get_conf_page(backend_desc)
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\backend_config_page.py", line 141, in _get_conf_page
    self._conf_pages[backend_desc] = cp_constructor(self.labelframe)
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 409, in __init__
    for p in list_serial_ports()
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 873, in list_serial_ports
    return list(serial.tools.list_ports.comports())
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\site-packages\serial\tools\list_ports_windows.py", line 412, in comports
    return list(iterate_comports())
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\site-packages\serial\tools\list_ports_windows.py", line 334, in iterate_comports
    info.serial_number = get_parent_serial_number(devinfo.DevInst, info.vid, info.pid)
  File "C:\Users\dsl40\AppData\Local\Programs\Thonny\lib\site-packages\serial\tools\list_ports_windows.py", line 197, in get_parent_serial_number
    vid = int(m.group(1), 16)
AttributeError: 'NoneType' object has no attribute 'group'

`

**Comment by aivarannamaa** [comment]
@dsl400, no, your problem is reported under #1443 and I hope to release the new version with the fix within this week.
