### ISSUE TITLE
Double clicking on blank space on Files browser gives error

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1251]
```
Traceback (most recent call last):
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\base_file_browser.py", line 525, in on_double_click
    parts = path.split(".")
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by aivarannamaa** [comment]
Fixed by unrelated changes
