### ISSUE TITLE
Package installation from local file / requirements.txt doesn't work

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1261]
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in _call_
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/thonny/plugins/pip_gui.py", line 658, in _handle_install_file_click
    initialdir=get_workbench().get_local_cwd,
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 1920, in askopenfilename
    return _get_dialog_provider().askopenfilename(**options)
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 1960, in askopenfilename
    args = cls._convert_common_options("Open file", **options)
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 1994, in _convert_common_options
    filename = _options_to_zenity_filename(options)
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 2036, in _options_to_zenity_filename
    return options["initialdir"] + os.path.sep
TypeError: unsupported operand type(s) for +: 'method' and 'str'
```

ok my fix . my idea replace line :  return options["initialdir"] + os.path.sep on return options["initialdir"]

**Comment by aivarannamaa** [comment]
Duplicate of #1344
