### ISSUE TITLE
caffe2_nvrtc.dll problem with Pytorch

### ISSUE THREAD

**Issue by jr751** [thonny/thonny#1284]
I have been trying to install Pytorch on Thonny with Python 3.8 without success (Note: I have python 3.8 selected under Tools->Options->Alternative Python 3 interpreter or environment). When I went to manage packages I was able to install torch and torchvision without issue. But when I type `import torch` into the shell I get the error message:

```
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "C:\Users\crovn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\crovn\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\crovn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`
```

I am not sure why this is happening. I checked the folder C:\Users\crovn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\lib\ to see if caffe2_nvrtc.dll is present and it is. Also, I tried to install Pytorch under manage packages, but it fails, and it returns the error message:

```
Collecting pytorch
  Downloading pytorch-1.0.2.tar.gz (689 bytes)
Building wheels for collected packages: pytorch
  Building wheel for pytorch (setup.py): started
  Building wheel for pytorch (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\crovn\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\crovn\\AppData\\Local\\Temp\\pip-install-x2oco3g_\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\crovn\\AppData\\Local\\Temp\\pip-install-x2oco3g_\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\crovn\AppData\Local\Temp\pip-wheel-4qx_ktf1'
       cwd: C:\Users\crovn\AppData\Local\Temp\pip-install-x2oco3g_\pytorch\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\crovn\AppData\Local\Temp\pip-install-x2oco3g_\pytorch\setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  ----------------------------------------
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
Installing collected packages: pytorch
    Running setup.py install for pytorch: started
    Running setup.py install for pytorch: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\crovn\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\crovn\\AppData\\Local\\Temp\\pip-install-x2oco3g_\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\crovn\\AppData\\Local\\Temp\\pip-install-x2oco3g_\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\crovn\AppData\Local\Temp\pip-record-vc3wiq7a\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\crovn\AppData\Roaming\Python\Python38\Include\pytorch'
         cwd: C:\Users\crovn\AppData\Local\Temp\pip-install-x2oco3g_\pytorch\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\crovn\AppData\Local\Temp\pip-install-x2oco3g_\pytorch\setup.py", line 11, in <module>
        raise Exception(message)
    Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\crovn\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\crovn\\AppData\\Local\\Temp\\pip-install-x2oco3g_\\pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\crovn\\AppData\\Local\\Temp\\pip-install-x2oco3g_\\pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\crovn\AppData\Local\Temp\pip-record-vc3wiq7a\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\crovn\AppData\Roaming\Python\Python38\Include\pytorch' Check the logs for full command output.


Process failed, return code: 1`
```

All I really want to be able to do is import torch, torch.optim, and torchvision. In addition, under Tools->Open system shell.. I typed in both `pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html` and `pip3.8 install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html` which both indicated that pytorch was installed. 

How do I fix this problem and be able to use the three imports torch, torch.optim, and torchvision? Are these the same as pytorch?

**Comment by aivarannamaa** [comment]
I don't know this package, but recently I suggested something: #1127
