### ISSUE TITLE
Unable to read back MP echo for management command

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1417]
```
print("Loop starting!")
while True:
    print("Loop running!")
print("Loop finished!")
```

```
>>> %Run -c $EDITOR_CONTENT
PROBLEM WITH THONNY'S BACK-END:

Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 46, in read
    self._read_buffer.extend(self._read_queue.get(True, timer.time_left))
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 340, in _handle_normal_command
    response = handler(cmd)
  File "/home/annamaa/python_stuff/thonny/thonny/backend.py", line 214, in _cmd_get_dirs_children_info
    data = {
  File "/home/annamaa/python_stuff/thonny/thonny/backend.py", line 215, in <dictcomp>
    path: self._get_filtered_dir_children_info(path, cmd["include_hidden"])
  File "/home/annamaa/python_stuff/thonny/thonny/backend.py", line 261, in _get_filtered_dir_children_info
    children = self._get_dir_children_info(path, include_hidden)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 1185, in _get_dir_children_info
    raw_data = self._evaluate(
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 560, in _evaluate
    out, err = self._execute(script, capture_output=True)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 516, in _execute
    self._execute_with_consumer(script, consume_output)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 548, in _execute_with_consumer
    self._submit_code(script)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 524, in _submit_code
    self._connection.read_all_expected(expected_echo, timeout=WAIT_OR_CRASH_TIMEOUT)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 117, in read_all_expected
    actual = self.read(len(expected), timeout=timeout)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 51, in read
    raise TimeoutError("Reaction timeout. Bytes read: %s" % self._read_buffer)
TimeoutError: Reaction timeout. Bytes read: bytearray(b'\n__thonny_result = {} \ntry:\n    __thonny_names = __thonny_helper.listdir(\'/\')\nexcept OSError:\n    __thonny_helper.print_mgmt_value(None) \nelse:\n    for __thonny_name in __thonny_names:\n        if not __thonny_name.startswith(".") or Fals     ')

__thonny_result = {} 
try:
    __thonny_names = __thonny_helper.listdir('/')
except OSError:
    __thonny_helper.print_mgmt_value(None) 
else:
    for __thonny_name in __thonny_names:
        if not __thonny_name.startswith(".") or Fals     
```

**Comment by aivarannamaa** [comment]
There was simultaneous connection in another process.

**Comment by aivarannamaa** [comment]
To be dealt with under #1418
