### ISSUE TITLE
AST marker fails (docstring, default values, tuple assignment)

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#149]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/149) by me.**

----------------------------------------

code:

```
def pour_problem(X, Y, goal, start=(0,0)):
    """X and Y are the capacity of glassesL (x, y) is curent fill levels
    and represents a stae. The goal is a level that can be in either glass.
    Start at start state and follow successors until we reach the goal.
    Keep trak of frontier and previously explored; fail when no frontier."""
    if goal in start:
        return [start]
    explored = set()
    frontier = [[start]]
    while frontier:
        path = frontier.pop(0)
        (x, y) = path[-1] # Last state in the first path of the frontier
        for (state, action) in successors(x, y, X, Y).items():
            if state not in explored:
                explored.add(state)
                path2 = path + [action, state]
                if goal in state:
                    return path2
                else:
                    frontier.append(path2)
    return Fail

Fail = []

def successors(x, y, X, Y):
    """Return a dict of {state: action} pairs describing what can be reached from
    the (x, y) state and how"""
    assert x<=X and y<=Y
    return {((0, y+x) if y+x<=Y else (x-(Y-y), y+(Y-y))): 'X->Y',
            ((x+y, 0) if x+y<=X else (x+(X-x), y-(X-x))): 'Y->X',
            (X, y): 'fill X', (x, Y): 'fill Y',
            (0, y): 'empty X', (x, 0): 'empty Y'}


print(pour_problem(4, 9, 6))
```

Stacktrace

```
Traceback (most recent call last):
  File "C:\Users\Kronen\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend_private\thonny\ast_utils.py", line 189, in _mark_text_ranges_rec
    tokens = _mark_end_and_return_child_tokens(node, tokens, prelim_end_lineno, prelim_end_col_offset)
  File "C:\Users\Kronen\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend_private\thonny\ast_utils.py", line 274, in _mark_end_and_return_child_tokens
    _strip_trailing_junk_from_expressions(tokens)
  File "C:\Users\Kronen\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend_private\thonny\ast_utils.py", line 213, in _strip_trailing_junk_from_expressions
    while (tokens[-1].type not in (token.RBRACE, token.RPAR, token.RSQB,
IndexError: list index out of range

```

**Comment by aivarannamaa** [comment]
Fixed in 3.2
