### ISSUE TITLE
Problems with micro:bit

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1515]
```
MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
>>> MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
ERROR   thonny.plugins.micropython.backend: PROBLEM WITH THONNY'S BACK-END:
Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 46, in read
    self._read_buffer.extend(self._read_queue.get(True, timer.time_left))
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 331, in _handle_normal_command
    response = handler(cmd)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 920, in _cmd_Run
    self._execute(source, capture_output=False)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 508, in _execute
    self._execute_with_consumer(script, self._send_output)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 668, in _execute_with_consumer
    self._submit_code(script)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 535, in _submit_code
    self._submit_code_via_paste_mode(to_be_sent)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 567, in _submit_code_via_paste_mode
    self._connection.read_all_expected(expected_echo, timeout=WAIT_OR_CRASH_TIMEOUT)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 117, in read_all_expected
    actual = self.read(len(expected), timeout=timeout)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 51, in read
    raise TimeoutError("Reaction timeout. Bytes read: %s" % self._read_buffer)
TimeoutError: Reaction timeout. Bytes read: bytearray(b'igital(0) and None or None\n\ndef turn():\n    pin0.write_digital(1) and None or None\n    pin8.write_digital(0) and None or None\n    pin1.write_digital(0) and None or None\n    pin12.write_digital(1) None\n    pin12.write_di')
Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 46, in read
    self._read_buffer.extend(self._read_queue.get(True, timer.time_left))
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 331, in _handle_normal_command
    response = handler(cmd)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 920, in _cmd_Run
    self._execute(source, capture_output=False)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 508, in _execute
    self._execute_with_consumer(script, self._send_output)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 668, in _execute_with_consumer
    self._submit_code(script)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 535, in _submit_code
    self._submit_code_via_paste_mode(to_be_sent)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 567, in _submit_code_via_paste_mode
    self._connection.read_all_expected(expected_echo, timeout=WAIT_OR_CRASH_TIMEOUT)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 117, in read_all_expected
    actual = self.read(len(expected), timeout=timeout)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 51, in read
    raise TimeoutError("Reaction timeout. Bytes read: %s" % self._read_buffer)
TimeoutError: Reaction timeout. Bytes read: bytearray(b'igital(0) and None or None\n\ndef turn():\n    pin0.write_digital(1) and None or None\n    pin8.write_digital(0) and None or None\n    pin1.write_digital(0) and None or None\n    pin12.write_digital(1) None\n    pin12.write_di')

>>> igital(0) and None or None

def turn():
    pin0.write_digital(1) and None or None
    pin8.write_digital(0) and None or None
    pin1.write_digital(0) and None or None
    pin12.write_digital(1) None
    pin12.write_di
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - use Stop/Restart to interrupt more and enter REPL.

MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> 
>>> %Run -c $EDITOR_CONTENT

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> ERROR   thonny.plugins.micropython.backend: PROBLEM WITH THONNY'S BACK-END:
Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 46, in read
    self._read_buffer.extend(self._read_queue.get(True, timer.time_left))
  File "/usr/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 331, in _handle_normal_command
    response = handler(cmd)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 634, in _cmd_get_globals
    globs = self._evaluate(
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 548, in _evaluate
    out, err = self._execute(script, capture_output=True)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 504, in _execute
    self._execute_with_consumer(script, consume_output)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 668, in _execute_with_consumer
    self._submit_code(script)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 535, in _submit_code
    self._submit_code_via_paste_mode(to_be_sent)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/bare_metal_backend.py", line 567, in _submit_code_via_paste_mode
    self._connection.read_all_expected(expected_echo, timeout=WAIT_OR_CRASH_TIMEOUT)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 117, in read_all_expected
    actual = self.read(len(expected), timeout=timeout)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/connection.py", line 51, in read
    raise TimeoutError("Reaction timeout. Bytes read: %s" % self._read_buffer)
TimeoutError: Reaction timeout. Bytes read: bytearray(b'__thonny_helper.print_mgmt_value({name : __thonny_helper.repr(value) for (name, valulper.repr(value) for (name, v')
__thonny_helper.print_mgmt_value({name : __thonny_helper.repr(value) for (name, valulper.repr(value) for (name, v
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - use Stop/Restart to interrupt more and enter REPL.


────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - use Stop/Restart to interrupt more and enter REPL.

MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> ERROR   thonny.plugins.micropython.backend: Crash in backend
Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 135, in __init__
    self.mainloop()
  File "/home/annamaa/python_stuff/thonny/thonny/backend.py", line 72, in mainloop
    self._handle_normal_command(msg)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 376, in _handle_normal_command
    self._check_perform_just_in_case_gc()
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 173, in _check_perform_just_in_case_gc
    self._perform_gc()
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 180, in _perform_gc
    self._execute_without_output(
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 532, in _execute_without_output
    raise ManagementError(script, out, err)
thonny.plugins.micropython.backend.ManagementError: Problem with a management command

SCRIPT:

import gc as __thonny_gc
__thonny_gc.collect()
del __thonny_gc


STDOUT:
KeyboardInterrupt: 


STDERR:




Backend terminated or disconnected. Use 'Stop/Restart' to restart.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
MicroPython v1.13 on 2020-12-21; micro:bit v2.0.0-beta.3 with nRF52833
Type "help()" for more information.
>>> 
Backend terminated or disconnected. Use 'Stop/Restart' to restart.

```

**Comment by aivarannamaa** [comment]
Seems to be cured raw mode and/or smaller block size
