### ISSUE TITLE
Error while parsing Pygame Zero error.

### ISSUE THREAD

**Issue by r0the** [thonny/thonny#1535]
Thonny 3.3.2 on macOS 11 fails with the following error when parsing an exception:

```
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/workbench.py", line 1706, in event_generate
    handler(event)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/assistance.py", line 126, in handle_toplevel_response
    self._explain_exception(msg["user_exception"])
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/assistance.py", line 165, in _explain_exception
    _error_helper_classes.get(error_info["type_name"], []) + _error_helper_classes["*"]
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/assistance.py", line 164, in <listcomp>
    for helper_class in (
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/stdlib_error_helpers.py", line 469, in __init__
    assert len(names) == 2
AssertionError
```

This is the shell output with the exception that causes the error:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/stefan/Downloads/Schneefall/schnee.py", line 3, in <module>
    images.test
  File "/Users/stefan/Library/Python/3.7/lib/python/site-packages/pgzero/loaders.py", line 149, in __getattr__
    raise AttributeError(*e.args) from None
AttributeError: No 'images' directory found to load image 'test'.
```

This is the test program that causes the exception:

```
import pgzrun

images.test

pgzrun.go()
```

To get the specific exception, the following conditions must be true:
- package 'pgzero' must be installed.
- a subdirectory 'images' relative to the test program must be present.
- no file named 'test.*' can be present in the subdirectory.

**Comment by aivarannamaa** [comment]
Thank you for the report! I got it fixed and the fix will be in Thonny 3.3.3
