### ISSUE TITLE
Thonny doesnt want to work

### ISSUE THREAD

**Issue by Jawanen** [thonny/thonny#1601]
Why this isnt working?

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1956, in toolbar_handler
    handler(*args)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 471, in cmd_stop_restart
    self.restart_backend(True)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 602, in restart_backend
    self._proxy = backend_class(clean)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\cpython\__init__.py", line 270, in __init__
    super().__init__(clean, get_interpreter_for_subprocess(executable))
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\cpython\__init__.py", line 38, in __init__
    super().__init__(clean, executable)
  File "C:\Users\Jaakko\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 866, in __init__
    self._start_background_process(clean=clean)
  File "C:\Users\Jaakko\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 933, in _start_background_process
    **extra_params
  File "C:\Users\Jaakko\AppData\Local\Programs\Thonny\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Jaakko\AppData\Local\Programs\Thonny\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied
```

**Comment by Jawanen** [comment]
Now i deleted all files and it isnt working

**Comment by aivarannamaa** [comment]
Thank you for the report!

Have you been able to use Thonny in the same computer before? If yes, then have you changed something in Thonny?

**Comment by Jawanen** [comment]
yes

**Comment by Jawanen** [comment]
i think i repaired it

**Comment by Jawanen** [comment]
now i am tryin to repair it

**Comment by aivarannamaa** [comment]
Have you solved the problem? What did you do?

**Comment by Phantom061** [comment]
@Jawanen what did you do? I have the same issue and I am not able to fix it
