### ISSUE TITLE
Problems with ubuntu 18.04 ans thony

### ISSUE THREAD

**Issue by antoniojteixeira** [thonny/thonny#1619]
Hi,
I started today to work with thoony and I have a problem. each time I do someting in the editor I am getting several errors. 
I can paste code, and have an error, I can run rund in the raspberry pico  but each time I type I get errors.
Any help please?
The errors output are :

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/home/atex/.local/lib/python3.5/site-packages/thonny/plugins/highlight_names.py", line 337, in update_highlighting
    from parso.python import tree  # pylint: disable=redefined-outer-name
  File "/home/atex/.local/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/atex/.local/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax
```

**Comment by aivarannamaa** [comment]
It looks like a library used by Thonny (parso) does not support Python 3.5. 

Your choices:

* Upgrade to newer Python version (recommended)
* Downgrade `parso` to 0.7.1 and `jedi` to 0.17.2
