### ISSUE TITLE
Problem when handling 'TextDelete'

### ISSUE THREAD

**Issue by Xrmolee** [thonny/thonny#1649]
i used Thonny on PI Pico, flow the code , i get crash .
Thonny version: 3.3.4

PS.:code run in python is correct .

def init_speed(start,end,level):
rate = int(end -start)/level
result = {}
for i in range(1,level+2):
result[i] = start + (i-1)*rate
result[0]=0
print(result)
return result

if name=="main":
my_speed = init_speed(10000,65535,15)
print(my_speed)
for i in range(10):
print(my_speed)

Traceback (most recent call last):
File "C:\Users\xrmol\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1708, in event_generate
handler(event)
File "C:\Users\xrmol\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 239, in text_deleted
self.update_plotter()
File "C:\Users\xrmol\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 253, in update_plotter
self.plotter.update_plot()
File "C:\Users\xrmol\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 1792, in update_plot
self.update_legend(data_lines, force_clean)
File "C:\Users\xrmol\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 1865, in update_legend
fill=self.colors[i - 1 % len(self.colors)],
IndexError: list index out of range

**Comment by Xrmolee** [comment]
fixed by #1648
