### ISSUE TITLE
numpy fails to install in thonny-3.3.6_alt.pkg on macOS Big Sur.

### ISSUE THREAD

**Issue by r0the** [thonny/thonny#1679]
Just out of curiosity, I tried out the alternative package with Python 3.9 on macOS Big Sur.
When installing numpy through the package manager, I get an error (see below).

On my system Python 3.9.2, numpy 1.20.1 installs successfully.

On the «standard» Thonny 3.3.6, numpy 1.20.1 also installs successfully.

It's nothing that worries me, I just tought you'd like to know.

```
Collecting numpy
  Downloading numpy-1.20.1.zip (7.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/bin/python3.9 /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/tmp77y34k7s
         cwd: /private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy
    Complete output (237 lines):
    Running from numpy source directory.
    setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_philox.pyx
    Processing numpy/random/_bounded_integers.pyx.in
    Processing numpy/random/_sfc64.pyx
    Processing numpy/random/_mt19937.pyx
    Processing numpy/random/bit_generator.pyx
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_pcg64.pyx
    Processing numpy/random/_common.pyx
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    blis_info:
      libraries blis not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    openblas_info:
      libraries openblas not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    atlas_3_10_blas_info:
      libraries satlas not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    /private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/system_info.py:1989: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    /private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/system_info.py:1989: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE
    
    /private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/system_info.py:1989: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE
    
    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    openblas_clapack_info:
      libraries openblas,lapack not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    flame_info:
      libraries flame not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries tatlas,tatlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /opt/local/lib
      libraries tatlas,tatlas not found in /opt/local/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries lapack_atlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries satlas,satlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /opt/local/lib
      libraries satlas,satlas not found in /opt/local/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries ptf77blas,ptcblas,atlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /opt/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /opt/local/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries lapack_atlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries f77blas,cblas,atlas not found in /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /opt/local/lib
      libraries f77blas,cblas,atlas not found in /opt/local/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    lapack_info:
      libraries lapack not found in ['/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/../../../../../../../Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
      NOT AVAILABLE
    
    /private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/system_info.py:1849: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE
    
    /private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/system_info.py:1849: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE
    
    numpy_linalg_lapack_lite:
      FOUND:
        language = c
        define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
    
    /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-10.9-universal2-3.9
    creating build/src.macosx-10.9-universal2-3.9/numpy
    creating build/src.macosx-10.9-universal2-3.9/numpy/distutils
    building library "npymath" sources
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable xlf90
    Could not locate executable xlf
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pgfortran
    don't know how to compile Fortran code on platform 'posix'
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    Traceback (most recent call last):
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-build-env-azr5dke5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-build-env-azr5dke5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-build-env-azr5dke5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 513, in <module>
        setup_package()
      File "setup.py", line 505, in setup_package
        setup(**metadata)
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-build-env-azr5dke5/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-build-env-azr5dke5/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/command/egg_info.py", line 24, in run
        self.run_command("build_src")
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/command/build_src.py", line 144, in run
        self.build_sources()
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
        self.build_library_sources(*libname_info)
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/private/var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/pip-install-3ivs0k5u/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 676, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/bin/python3.9 /Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/gh/l6t4m6dj5rb0541622rnf6s00000gn/T/tmp77y34k7s Check the logs for full command output.
Process returned with code 1
```

**Comment by aivarannamaa** [comment]
Thank you for the report!

This is good to know, as I considered publishing only the universal2 variant of Thonny+Python bundle since Thonny 4.0.
I read somewhere, that x64 packages should be usable with universal2 Python via Rosetta, but apparently it's not the case with Numpy.

Let's hope they publish universal2 wheels soon: https://github.com/numpy/numpy/issues/18143

**Comment by aivarannamaa** [comment]
Seems to install nicely now in Thonny 4.0.0b1
