### ISSUE TITLE
Error when disconnecting a stuck SSH connection to ev3dev

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1683]
```
Traceback (most recent call last):
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 521, in _pull_backend_messages
    msg = self._proxy.fetch_next_message()
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\cpython_ssh\__init__.py", line 49, in fetch_next_message
    msg = super().fetch_next_message()
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 1122, in fetch_next_message
    raise BackendTerminatedError(self._proc.returncode if self._proc else None)
thonny.running.BackendTerminatedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 508, in _poll_backend_messages
    if self._pull_backend_messages() is False:
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 531, in _pull_backend_messages
    self.destroy_backend()
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 622, in destroy_backend
    self._proxy.destroy()
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\cpython_ssh\__init__.py", line 87, in destroy
    self.send_command(ImmediateCommand("kill"))
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 961, in send_command
    self._send_msg(cmd)
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 964, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
AttributeError: 'NoneType' object has no attribute 'stdin'

```

**Comment by aivarannamaa** [comment]
I accidentally connected via Python 3 back-end and requested `pybricks-repl`
