### ISSUE TITLE
Bug in os-micropython 

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1684]
```
ERROR   thonny.plugins.micropython.backend: PROBLEM WITH THONNY'S BACK-END:
Traceback (most recent call last):
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 340, in _handle_normal_command
    response = handler(cmd)
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\os_mp_backend.py", line 251, in _cmd_Run
    self._prepare_after_soft_reboot()
TypeError: _prepare_after_soft_reboot() missing 1 required positional argument: 'clean'
Traceback (most recent call last):
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 340, in _handle_normal_command
    response = handler(cmd)
  File "C:\Users\Aivar Annamaa\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\os_mp_backend.py", line 251, in _cmd_Run
    self._prepare_after_soft_reboot()
TypeError: _prepare_after_soft_reboot() missing 1 required positional argument: 'clean'
```

**Comment by aivarannamaa** [comment]
Fixed under #1715
