### ISSUE TITLE
Run command remains available, when in MP mode and device is disconnected

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1722]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/annamaa/python_stuff/thonny/thonny/workbench.py", line 994, in dispatch
    handler()
  File "/home/annamaa/python_stuff/thonny/thonny/running.py", line 406, in cmd_run_current_script
    self.execute_current("Run")
  File "/home/annamaa/python_stuff/thonny/thonny/running.py", line 367, in execute_current
    self.execute_editor_content(command_name, self._get_active_arguments())
  File "/home/annamaa/python_stuff/thonny/thonny/running.py", line 340, in execute_editor_content
    get_shell().submit_magic_command(
  File "/home/annamaa/python_stuff/thonny/thonny/shell.py", line 224, in submit_magic_command
    self.text.submit_command(cmd_line, ("magic",))
  File "/home/annamaa/python_stuff/thonny/thonny/shell.py", line 405, in submit_command
    self.insert("input_start", cmd_line, tags)
  File "/home/annamaa/python_stuff/thonny/thonny/shell.py", line 902, in intercept_insert
    self._try_submit_input()
  File "/home/annamaa/python_stuff/thonny/thonny/shell.py", line 1084, in _try_submit_input
    self._submit_input(submittable_text)
  File "/home/annamaa/python_stuff/thonny/thonny/shell.py", line 1226, in _submit_input
    get_runner().send_program_input(text_to_be_submitted)
  File "/home/annamaa/python_stuff/thonny/thonny/running.py", line 314, in send_program_input
    self._proxy.send_program_input(data)
  File "/home/annamaa/python_stuff/thonny/thonny/running.py", line 972, in send_program_input
    self._send_msg(InputSubmission(data))
  File "/home/annamaa/python_stuff/thonny/thonny/running.py", line 965, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
AttributeError: 'NoneType' object has no attribute 'stdin'
```

**Comment by aivarannamaa** [comment]
Not anymore
