### ISSUE TITLE
ERROR: Problem when handling "Program Output" with negative integers.

### ISSUE THREAD

**Issue by the-stanely** [thonny/thonny#1746]
**Thonny v. 3.3.5 running on Windows 10**

REPL errors on a negative integer typed in the command line.  Typing this in REPL...
` -1
`
Results in this message in REPL:
`[object_link_for_thonny=-1]-1`
and a pop-up window with this message...
```
Traceback (most recent call last):
  File "C:\Users\the-stanely\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1708, in event_generate
    handler(event)
  File "C:\Users\the-stanely\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 433, in _handle_program_output
    self._update_visible_io(None)
  File "C:\Users\the-stanely\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 512, in _update_visible_io
    self._apply_io_event(data, stream_name)
  File "C:\Users\the-stanely\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 555, in _apply_io_event
    self.active_extra_tags.pop()
IndexError: pop from empty list
```
I can print negative numbers in a loop entered in REPL like,

```
i=-10
while i < 0:
    print(i)
    i+=1

```
but I can't do something like this...

```
a=-1
a
```

The Thonny REPL isn't always able to deal with negative integers.  Non-integers seem to work fine. as in:
`-1.0`

**Comment by the-stanely** [comment]
Yes, thank you!  It's fixed in 3.3.6.  I'm sorry, I thought I was running the latest version.
