### ISSUE TITLE
Memory issues?

### ISSUE THREAD

**Issue by zolf** [thonny/thonny#1763]
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1708, in event_generate
    handler(event)
  File "C:\Users\xxxx\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 1440, in _on_output
    self.append_text(msg["data"], stream_name)
  File "C:\Users\xxxx\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workdlg.py", line 243, in append_text
    setattr(self, stream_name, getattr(self, stream_name) + text)
MemoryError

With this popup, unable to close, or save my program, just reboot. the program i'm running generates a lot off output

**Comment by aivarannamaa** [comment]
Thank you for the report!

What did you do before this popup appeared?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
