### ISSUE TITLE
Error after force-closing the back-end CPython process

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1786]
* Make program stop while turtle window is visible (eg. by `input()`)
* Close the window and make Windows kill it
* next action in Thonny will cause error about subprocess

**Comment by aivarannamaa** [comment]
For example:

```
10:31:50.046 ERROR   thonny.workbench: Internal error
Traceback (most recent call last):
  File "c:\Python39-64\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\workspaces\python_stuff\thonny\thonny\tktextext.py", line 243, in dispatch
    return fun(event)
  File "C:\workspaces\python_stuff\thonny\thonny\shell.py", line 976, in perform_return
    EnhancedTextWithLogging.perform_return(self, event)
  File "C:\workspaces\python_stuff\thonny\thonny\tktextext.py", line 461, in perform_return
    self.insert("insert", "\n")
  File "C:\workspaces\python_stuff\thonny\thonny\shell.py", line 938, in intercept_insert
    self._try_submit_input()
  File "C:\workspaces\python_stuff\thonny\thonny\shell.py", line 1127, in _try_submit_input
    self._submit_input(submittable_text)
  File "C:\workspaces\python_stuff\thonny\thonny\shell.py", line 1283, in _submit_input
    get_runner().send_program_input(text_to_be_submitted)
  File "C:\workspaces\python_stuff\thonny\thonny\running.py", line 308, in send_program_input
    self._proxy.send_program_input(data)
  File "C:\workspaces\python_stuff\thonny\thonny\running.py", line 1045, in send_program_input
    self._send_msg(InputSubmission(data))
  File "C:\workspaces\python_stuff\thonny\thonny\running.py", line 1038, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
OSError: [Errno 22] Invalid argument
```

**Comment by aivarannamaa** [comment]
Weird, sometimes when killing the backend ends up with frontend detecting it and sometimes it doesn't.

Need to find out why does `_listen_stderr` catches IOError.
