### ISSUE TITLE
tkinter.TclError: couldn't connect to display ":10.0"

### ISSUE THREAD

**Issue by etalon** [thonny/thonny#1816]
Hi, 

have a raspberry 3b+ with thonny. When try to launch it via "sudo thonny" I get the error "tkinter.TclError: couldn't connect to display ":10.0"". Any Ideas what could be wrong?

Complete log:

```
INFO    thonny: Thonny version: 3.3.6
No protocol specified
No protocol specified
ERROR:root:Internal launch or mainloop error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/__init__.py", line 194, in launch
    bench = workbench.Workbench()
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 130, in __init__
    tk.Tk.__init__(self, className="Thonny")
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":10.0"
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/__init__.py", line 194, in launch
    bench = workbench.Workbench()
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 130, in __init__
    tk.Tk.__init__(self, className="Thonny")
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":10.0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/thonny", line 11, in <module>
    load_entry_point('thonny==3.3.6', 'gui_scripts', 'thonny')()
  File "/usr/lib/python3/dist-packages/thonny/__init__.py", line 213, in launch
    dlg = ui_utils.LongTextDialog("Internal error", traceback.format_exc())
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 1731, in __init__
    super().__init__(master=parent)
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 41, in __init__
    super().__init__(master=master, cnf=cnf, **kw)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2342, in __init__
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2292, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2259, in _setup
    _default_root = Tk()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":10.0"
```

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately I can't reproduce this neither with my Raspberry (updated to latest Raspberry OS) nor with Ubuntu 20.04.

Does it run properly without `sudo`?

Please make following experiment. Save follwing code to `tktest.py`:

```
import tkinter
root = tkinter.Tk()
root.mainloop()
```

and then run it with `sudo python3 tktest.py`.

Do you get the same error?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!

**Comment by technical-publishing** [comment]
Hello, I have to reopen this issue, because exactly the same error occurs on my RaspberryPi 3B. I have the bullseye 32 bit os installed. I have executed the tktest.py file and the same error occurs on the command line... could you please help me, I want to run a script with neopixel leds and therefore I have to run thonny in root mode. Thank you very much in advance.
