### ISSUE TITLE
Unable to connect to RPi Pico

### ISSUE THREAD

**Issue by BangDroid** [thonny/thonny#1832]
Traceback (most recent call last):
  File "C:\Users\Bangas Droid\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Bangas Droid\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1957, in toolbar_handler
    handler(*args)
  File "C:\Users\Bangas Droid\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 405, in cmd_run_current_script
    self.execute_current("Run")
  File "C:\Users\Bangas Droid\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 364, in execute_current
    and not self._proxy.can_run_local_files()
AttributeError: 'NoneType' object has no attribute 'can_run_local_files'

**Comment by BangDroid** [comment]
Above error occurred when mashing stop in frustration. Issue was Windows refusing to communicate on COM. Full reboot fixed.
