### ISSUE TITLE
Micropython: Thonny backend error while running on Pico

### ISSUE THREAD

**Issue by simojo** [thonny/thonny#1890]
While attempting to run a file on my pico, thonny returned this error:

```
ERROR   thonny.plugins.micropython.backend: PROBLEM WITH THONNY'S BACK-END:
Traceback (most recent call last):
  File "/nix/store/j33s68zbvz5w5v21140ack69smvwhs15-thonny-3.3.2/lib/python3.8/site-packages/thonny/plugins/micropython/backend.py", line 335, in _handle_normal_command
    response = handler(cmd)
  File "/nix/store/j33s68zbvz5w5v21140ack69smvwhs15-thonny-3.3.2/lib/python3.8/site-packages/thonny/plugins/micropython/backend.py", line 630, in _cmd_get_globals
    globs = self._evaluate(
  File "/nix/store/j33s68zbvz5w5v21140ack69smvwhs15-thonny-3.3.2/lib/python3.8/site-packages/thonny/plugins/micropython/backend.py", line 544, in _evaluate
    out, err = self._execute(script, capture_output=True)
  File "/nix/store/j33s68zbvz5w5v21140ack69smvwhs15-thonny-3.3.2/lib/python3.8/site-packages/thonny/plugins/micropython/backend.py", line 500, in _execute
    self._execute_with_consumer(script, consume_output)
  File "/nix/store/j33s68zbvz5w5v21140ack69smvwhs15-thonny-3.3.2/lib/python3.8/site-packages/thonny/plugins/micropython/bare_metal_backend.py", line 684, in _execute_with_consumer
    self._submit_code(script)
  File "/nix/store/j33s68zbvz5w5v21140ack69smvwhs15-thonny-3.3.2/lib/python3.8/site-packages/thonny/plugins/micropython/bare_metal_backend.py", line 557, in _submit_code
    self._submit_code_via_raw_paste_mode(to_be_sent)
  File "/nix/store/j33s68zbvz5w5v21140ack69smvwhs15-thonny-3.3.2/lib/python3.8/site-packages/thonny/plugins/micropython/bare_metal_backend.py", line 633, in _submit_code_via_raw_paste_mode
    assert response == RAW_PASTE_CONFIRMATION, "Got %r instead of raw-paste confirmation" % (
AssertionError: Got b'' instead of raw-paste confirmation
```

I'm trying to save a file, `main.py`, onto the board's filesystem using micropython, but there seems to be some error in writing it. Even running thonny as root results in the same error.

Thonny version: `3.3.2`
Python version: `3.8.7`
OS: `NixOS 21.05`

**Comment by aivarannamaa** [comment]
Does the problem persist after you soft-reboot your device (with Ctrl+D)? Afer hard reset?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
