### ISSUE TITLE
Editor autocomplete gives ugly stacktrace if backend (eg. CiP) is closed 

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#1899]
```
Traceback (most recent call last):
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\tktextext.py", line 229, in dispatch
    return fun(event)
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\tktextext.py", line 541, in perform_tab
    return self.perform_midline_tab(event)
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\autocomplete.py", line 321, in patched_perform_midline_tab
    _handle_autocomplete_request_for_text(text)
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\autocomplete.py", line 309, in _handle_autocomplete_request_for_text
    text.autocompleter.handle_autocomplete_request()
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\autocomplete.py", line 58, in handle_autocomplete_request
    filename=self._get_filename(),
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 268, in send_command
    response = self._proxy.send_command(cmd)
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 184, in send_command
    return super().send_command(cmd)
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 962, in send_command
    self._send_msg(cmd)
  File "C:\Users\d\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 965, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
AttributeError: 'NoneType' object has no attribute 'stdin'

```

**Comment by aivarannamaa** [comment]
Can't reproduce anymore
