### ISSUE TITLE
I cant access my interpreter and MY THONNY IS NOT WORKING PROPERLY

### ISSUE THREAD

**Issue by pranavjasani** [thonny/thonny#1948]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 514, in _start_runner
    self._runner.start()
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 122, in start
    self.restart_backend(False, True)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 612, in restart_backend
    self._proxy = backend_class(clean)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 86, in __init__
    self._fix_port()
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 99, in _fix_port
    potential = self._detect_potential_ports()
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 191, in _detect_potential_ports
    all_ports = list_serial_ports()
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 880, in list_serial_ports
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'

WHAT SHOULD I DO????

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
