### ISSUE TITLE
Cannot execute file in thonny

### ISSUE THREAD

**Issue by RockZombie123** [thonny/thonny#1991]
So I've added and edited a little bit of this code to make it execute another file if the user has successfully logged in.

Here is the code: (Original by omar-h-omar)
```
def choices():
    print("Please choose what you would like to do.")
    choice = int(input("For Sigining Up Type 1 and For Signing in Type 2: "))
    if choice == 1:
       return getdetails()
    elif choice == 2:
       return checkdetails()
    else:
       raise TypeError

def getdetails():
    print("Please Provide")
    name = str(input("Name: "))
    password = str(input("Password: "))
    f = open("User_Data.txt",'r')
    info = f.read()
    if name in info:
        return "Name Unavailable. Please Try Again"
    f.close()
    f = open("User_Data.txt",'w')
    info = info + " " +name + " " + password
    f.write(info)

def checkdetails():
    print("Please Provide")
    name = str(input("Name: "))
    password = str(input("Password: "))
    f = open("User_Data.txt",'r')
    info = f.read()
    info = info.split()
    if name in info:
        index = info.index(name) + 1
        usr_password = info[index]
        if usr_password == password:
            #return "Welcome Back, " + name
            exec(open("Jammer.py").read())
        else:
            return "Password entered is wrong"
    else:
        return "Name not found. Please Sign Up."

print(choices())
```
But when I execute it and successfully log in, it gives an error.

OUTPUT:
```
Please choose what you would like to do.
For Sigining Up Type 1 and For Signing in Type 2: 2
Please Provide
Name: S****
Password: ***
```
EXECUTED FILES:
```

Jammer
-----------------


Sorry about the trouble, but what was your username again?(1/2) 1
Welcome, Saish
Ctrl - D to continue.
None
```
``` 
Your gmail address:  @*********gmail.com

```

ERROR:

```

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<string>", line 5, in send
  File "<string>", line 7, in <module>
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 1205, in readline
    return self._generic_read("readline", limit)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 1193, in _generic_read
    "Wrong type of command (%r) when waiting for input" % (msg,)
RuntimeError: Wrong type of command (ToplevelCommand(source='rockzombie005@gmail.com\n', tty_mode=True, id='cmd_3', local_cwd='/home/pi/saish/programs', expected_cwd='/home/pi/saish/programs', name='execute_source', argv=[])) when waiting for input

```

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for the late reply!

Did it happen once or can you easily reproduce it?

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!
