### ISSUE TITLE
Installation issue with firmware v1.17

### ISSUE THREAD

**Issue by FBRISSON** [thonny/thonny#1995]
When trying to Install MicroPython firmware v1.17 on my Pi Pico i got the following errors:

Downloading 563200 bytes from https://micropython.org/resources/firmware/rp2-pico-20210902-v1.17.uf2

Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1032, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 972, in send
    self.connect()
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Thonny\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Program Files (x86)\Thonny\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Thonny\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\uf2dialog.py", line 271, in _perform_work
    self._download_to_the_device(download_url, size, target_dir)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\uf2dialog.py", line 333, in _download_to_the_device
    with urlopen(req, timeout=5) as fsrc:
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>

**Comment by aivarannamaa** [comment]
Please see #1986
