### ISSUE TITLE
Problem with emoji characters in Linux

### ISSUE THREAD

**Issue by peter-65** [thonny/thonny#2008]
Having an error on opening Python code. - appears to be a character on the forth line of the source code.  PI OS FULL (19/10/21)

Thonny 3.3.10, linux, Python 3.7.3 (32 Bit) TK 8.6.9

```
-------------------- error messages --------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 190, in __init__
    self._editor_notebook.load_startup_files()
  File "/usr/lib/python3/dist-packages/thonny/editors.py", line 686, in load_startup_files
    self.show_file(filename)
  File "/usr/lib/python3/dist-packages/thonny/editors.py", line 923, in show_file
    editor = self.get_editor(filename, True)
  File "/usr/lib/python3/dist-packages/thonny/editors.py", line 1012, in get_editor
    return self._open_file(filename)
  File "/usr/lib/python3/dist-packages/thonny/editors.py", line 996, in _open_file
    if editor._load_file(filename):
  File "/usr/lib/python3/dist-packages/thonny/editors.py", line 171, in _load_file
    result = self._load_local_file(filename, keep_undo)
  File "/usr/lib/python3/dist-packages/thonny/editors.py", line 203, in _load_local_file
    if not self._code_view.set_content_as_bytes(source, keep_undo):
  File "/usr/lib/python3/dist-packages/thonny/codeview.py", line 226, in set_content_as_bytes
    self.set_content(chars, keep_undo)
  File "/usr/lib/python3/dist-packages/thonny/codeview.py", line 256, in set_content
    self.text.direct_insert("1.0", content)
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 833, in direct_insert
    result = tktextext.EnhancedText.direct_insert(self, index, chars, tags=tags, **kw)
  File "/usr/lib/python3/dist-packages/thonny/tktextext.py", line 748, in direct_insert
    super().direct_insert(index, chars, tags, **kw)
  File "/usr/lib/python3/dist-packages/thonny/tktextext.py", line 162, in direct_insert
    self._original_insert(index, chars, tags, **kw)
  File "/usr/lib/python3/dist-packages/thonny/tktextext.py", line 38, in original_function
    self.tk.call((self._original_widget_name, operation) + args)
_tkinter.TclError: character U+1f605 is above the range (U+0000-U+FFFF) allowed by Tcl
```

OS details :-
New load of Raspberry PI OS (Full) on 19/10/21 - Apt Update and Upgrade - Install example code fro a Pimorini Enviro+ 
The sample code for the weather-and-light.py  which starts as below. 

code example from Pimoroni example code.
--------------------------------------------

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

f"Sorry! This program requires Python >= 3.6 😅"
```

----- testing done -------
Open the source in different editors, both mu, and greany both allow the code to load to be viewed.

Tried to copy the first 3  lines no problems copy from mu, paste in Thorny, 
copy of the first 4 lines and the code does not paste in to new file.

**Comment by aivarannamaa** [comment]
Latest Raspberry Pi OS has Tk 8.6.11, which has this problem fixed.
