### ISSUE TITLE
Internal error with interpreter, and I think this is the backend error

### ISSUE THREAD

**Issue by new-comer120** [thonny/thonny#2013]
when i open the interpreter in Thonny, and when I have change the interpreter to Python 3.8.10 (On my computer) it have this "internal error":
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1069, in dispatch_from_menu
    dispatch(None)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 995, in dispatch
    handler()
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\backend_config_page.py", line 317, in select_device
    get_workbench().show_options("interpreter")
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 2118, in show_options
    get_runner().restart_backend(False)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 612, in restart_backend
    self._proxy = backend_class(clean)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\cpython\__init__.py", line 284, in __init__
    super().__init__(clean, get_interpreter_for_subprocess(executable))
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\cpython\__init__.py", line 40, in __init__
    super().__init__(clean, executable)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 877, in __init__
    self._start_background_process(clean=clean)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 941, in _start_background_process
    env=self._get_environment(),
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 883, in _get_environment
    env = get_environment_for_python_subprocess(self._executable)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 1285, in get_environment_for_python_subprocess
    overrides = get_environment_overrides_for_python_subprocess(target_executable)
  File "C:\Users\Administrator\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 1332, in get_environment_overrides_for_python_subprocess
    target_executable, this_executable
  File ".\lib\genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Äv㧈v'
```
and when i open Thonny, it have another internal error:
```
Interpreter 'Äv㧈v' does not exist. Please check the configuration!
```
I'm running the latest version of Thonny, and I'm running this on Windows 7

**Comment by aivarannamaa** [comment]
Please reopen if you have more details to add!

**Comment by new-comer120** [comment]
thanks!
