### ISSUE TITLE
Can't view microbit.Image in the Object inspector

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#2024]
With V1 it gives:

```
ERROR   thonny.plugins.micropython.backend: ManagementError while handling get_object_info
Traceback (most recent call last):
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 352, in _handle_normal_command
    response = handler(cmd)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 758, in _cmd_get_object_info
    info["attributes"] = self._get_object_attributes(cmd.all_attributes)
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 845, in _get_object_attributes
    atts = self._evaluate(
  File "/home/annamaa/python_stuff/thonny/thonny/plugins/micropython/backend.py", line 626, in _evaluate
    raise ManagementError("Script produced errors", script, out, err)
thonny.plugins.micropython.backend.ManagementError: Script produced errors
ERROR   thonny.plugins.micropython.backend: ManagementError details:
SCRIPT: __thonny_helper.print_mgmt_value({name : (   __thonny_helper.builtins.id(__thonny_helper.builtins.getattr(__thonny_helper.object_info, name)),    __thonny_helper.repr(__thonny_helper.builtins.getattr(__thonny_helper.object_info, name))) for name in __thonny_helper.builtins.dir(__thonny_helper.object_info)})

STDOUT: 

STDERR: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <dictcomp>
MemoryError: 
```

Same, if I view single image constant in Image

**Comment by aivarannamaa** [comment]
Couldn't reproduce exactly, but inspecting attributes of Image or `dir(Image)` did produce memory error.
