### ISSUE TITLE
"OSError: [Errno 8] Exec format error" when selecting interpreter

### ISSUE THREAD

**Issue by CosmicVoyager** [thonny/thonny#2037]
Greetings,

I just installed Thonny. When I select another version of Python interpreter and click OK, I immediately get the following error. The same thing happens if I try to select the previous version, 3.9.

OSError: [Errno 8] Exec format error: '/Library/Frameworks/Python.framework/Versions/3.10/Python'

Mac OS 11.6

Thanks

Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/workbench.py", line 1069, in dispatch_from_menu
    dispatch(None)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/workbench.py", line 995, in dispatch
    handler()
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/backend_config_page.py", line 317, in select_device
    get_workbench().show_options("interpreter")
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/workbench.py", line 2118, in show_options
    get_runner().restart_backend(False)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/running.py", line 612, in restart_backend
    self._proxy = backend_class(clean)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/cpython/__init__.py", line 284, in __init__
    super().__init__(clean, get_interpreter_for_subprocess(executable))
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/cpython/__init__.py", line 40, in __init__
    super().__init__(clean, executable)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/running.py", line 877, in __init__
    self._start_background_process(clean=clean)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/running.py", line 944, in _start_background_process
    **extra_params
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Library/Frameworks/Python.framework/Versions/3.10/Python'

**Comment by aivarannamaa** [comment]
Thank you for the report!

Did you select the folder or executable (file)? It must be executable.
