### ISSUE TITLE
Auto Completion dosen't work

### ISSUE THREAD

**Issue by StrassenStyle** [thonny/thonny#2054]
Hello,

When i press CTRL + Space to use Auto Completion i get a Internal error popup
I'm using the version 3.3.13 for Windows 10
I have tried reinstalling Thonny but the error keeps occuring

Error:

Traceback (most recent call last):
  File "D:\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:\Thonny\lib\site-packages\thonny\workbench.py", line 995, in dispatch
    handler()
  File "D:\Thonny\lib\site-packages\thonny\plugins\autocomplete.py", line 295, in handle_autocomplete_request
    _handle_autocomplete_request_for_text(text)
  File "D:\Thonny\lib\site-packages\thonny\plugins\autocomplete.py", line 309, in _handle_autocomplete_request_for_text
    text.autocompleter.handle_autocomplete_request()
  File "D:\Thonny\lib\site-packages\thonny\plugins\autocomplete.py", line 58, in handle_autocomplete_request
    filename=self._get_filename(),
  File "D:\Thonny\lib\site-packages\thonny\running.py", line 274, in send_command
    response = self._proxy.send_command(cmd)
  File "D:\Thonny\lib\site-packages\thonny\plugins\micropython\__init__.py", line 184, in send_command
    return super().send_command(cmd)
  File "D:\Thonny\lib\site-packages\thonny\running.py", line 972, in send_command
    self._send_msg(cmd)
  File "D:\Thonny\lib\site-packages\thonny\running.py", line 975, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
AttributeError: 'NoneType' object has no attribute 'stdin'

**Comment by StrassenStyle** [comment]
worked after restart, sorry.
