### ISSUE TITLE
Micropython/ESP32 - clicking on error in console does not redirect me to code window to specific line

### ISSUE THREAD

**Issue by cz8pru** [thonny/thonny#2083]
During running code on my device ESP32 I see in console some error:
Traceback (most recent call last):
  File "<stdin>", line 149, in <module>
  File "<stdin>", line 117, in status_req
  File "<stdin>", line 65, in qpigs_parse
TypeError: function doesn't take keyword arguments

When I click on "File "<stdin>", line 65, in qpigs_parse" it does not redirect me to line number in specific file.

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll try to fix this for version 4.0
