### ISSUE TITLE
Package installing errors

### ISSUE THREAD

**Issue by zpowellman** [thonny/thonny#2091]
I'm using Windows 11 machine, Thonny Version 3.3.13.  RPI Pico with Micropython v1.17.  I can't install any packages using package manager and PyPi.  Tried micropython ssd1306, failed.   I tried micropython-dht12 package...again failed.  Maybe this error info will help.
Thanks
Dan

Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1032, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 972, in send
    self.connect()
  File "C:\Program Files (x86)\Thonny\lib\http\client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Thonny\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Program Files (x86)\Thonny\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Thonny\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\pip_gui.py", line 438, in poll_fetch_complete
    _, bin_data = url_future.result()
  File "C:\Program Files (x86)\Thonny\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Program Files (x86)\Thonny\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Program Files (x86)\Thonny\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 1230, in load_url
    with urlopen(url, timeout=timeout) as conn:
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>

**Comment by aivarannamaa** [comment]
Please see https://github.com/thonny/thonny/issues/1986
