### ISSUE TITLE
SSD1306 Library

### ISSUE THREAD

**Issue by Userintheshell** [thonny/thonny#2141]
I have a problem with library micropython ssd1306. 

How can I solve these problems:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\pip_gui.py", line 438, in poll_fetch_complete
    _, bin_data = url_future.result()
  File "C:\Program Files (x86)\Thonny\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Program Files (x86)\Thonny\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Program Files (x86)\Thonny\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 1230, in load_url
    with urlopen(url, timeout=timeout) as conn:
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>

**Comment by aivarannamaa** [comment]
Please see #1986
