### ISSUE TITLE
Paste mode doesn't work with M5 Atom

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#2143]
New UIFlow 2.0 preview: https://m5stack.oss-cn-shenzhen.aliyuncs.com/%E4%B8%B4%E6%97%B6%E6%96%87%E4%BB%B6/uiflow-b084d9e-dirty.bin

Got

```
DEBUG   thonny.plugins.micropython.bare_metal_backend: Submitting via paste: b'\ntry:\n    from time import localtime as __thonny_localtime\n    __thonn'
DEBUG   thonny.plugins.micropython.bare_metal_backend: Submitting via paste: b'\ntry:\n\n    from machine import RTC as __thonny_RTC\n    try:\n        __'
DEBUG   thonny.plugins.micropython.bare_metal_backend: Submitting via paste: b'\ntry:\n\n    from machine import RTC as __thonny_RTC\n    try:\n        # '
INFO    thonny.plugins.micropython.backend: Handling command 'get_dirs_children_info'
DEBUG   thonny.plugins.micropython.bare_metal_backend: Submitting via paste: b'\n__thonny_result = {} \ntry:\n    __thonny_names = __thonny_helper.listd'
ERROR   thonny.plugins.micropython.backend: PROBLEM WITH THONNY'S BACK-END:
Traceback (most recent call last):
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 46, in read
    self._read_buffer.extend(self._read_queue.get(True, timer.time_left))
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 347, in _handle_normal_command
    response = handler(cmd)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 215, in _cmd_get_dirs_children_info
    for path in cmd["paths"]
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 215, in <dictcomp>
    for path in cmd["paths"]
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 260, in _get_filtered_dir_children_info
    children = self._get_dir_children_info(path, include_hidden)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 1262, in _get_dir_children_info
    % (path, include_hidden, path.rstrip("/") + "/")
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 605, in _evaluate
    out, err = self._execute(script, capture_output=True)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 561, in _execute
    self._execute_with_consumer(script, consume_output)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 698, in _execute_with_consumer
    self._submit_code(script)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 554, in _submit_code
    self._submit_code_via_paste_mode(to_be_sent)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 592, in _submit_code_via_paste_mode
    self._connection.read_all_expected(expected_echo, timeout=WAIT_OR_CRASH_TIMEOUT)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 117, in read_all_expected
    actual = self.read(len(expected), timeout=timeout)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 51, in read
    raise TimeoutError("Reaction timeout. Bytes read: %s" % self._read_buffer)
TimeoutError: Reaction timeout. Bytes read: bytearray(b'".") or True:\n            try:\n                __thonny_result[__thonny_nae] = __thonny_helper.os.stat(\'/flash/\' + __thonny_name)\n            except __thonny_helper.builtins.OSError as e:\n                __thonny_result[__thonny_name] = __thonny_helper.b')
INFO    thonny.plugins.micropython.backend: Handling command 'get_globals'
DEBUG   thonny.plugins.micropython.bare_metal_backend: Submitting via paste: b'__thonny_helper.print_mgmt_value({name : (__thonny_helper.repr(value),'
```

Tried replacing `\n` => `\r\n` in the submitted code. Got:

```
INFO    thonny.plugins.micropython.backend: Handling command 'get_dirs_children_info'
DEBUG   thonny.plugins.micropython.bare_metal_backend: Submitting via paste: b'\n__thonny_result = {} \ntry:\n    __thonny_names = __thonny_helper.listd'
ERROR   thonny.plugins.micropython.backend: PROBLEM WITH THONNY'S BACK-END:
Traceback (most recent call last):
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 46, in read
    self._read_buffer.extend(self._read_queue.get(True, timer.time_left))
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 347, in _handle_normal_command
    response = handler(cmd)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 215, in _cmd_get_dirs_children_info
    for path in cmd["paths"]
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 215, in <dictcomp>
    for path in cmd["paths"]
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 260, in _get_filtered_dir_children_info
    children = self._get_dir_children_info(path, include_hidden)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 1262, in _get_dir_children_info
    % (path, include_hidden, path.rstrip("/") + "/")
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 605, in _evaluate
    out, err = self._execute(script, capture_output=True)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 561, in _execute
    self._execute_with_consumer(script, consume_output)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 698, in _execute_with_consumer
    self._submit_code(script)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 554, in _submit_code
    self._submit_code_via_paste_mode(to_be_sent)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 592, in _submit_code_via_paste_mode
    self._connection.read_all_expected(expected_echo, timeout=WAIT_OR_CRASH_TIMEOUT)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 117, in read_all_expected
    actual = self.read(len(expected), timeout=timeout)
  File "C:\Users\Maris\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 51, in read
    raise TimeoutError("Reaction timeout. Bytes read: %s" % self._read_buffer)
TimeoutError: Reaction timeout. Bytes read: bytearray(b'".") or True:\n            try:\n                __thonny_result[__thonny_nae] = __thonny_helper.os.stat(\'/flash/\' + __thonny_name)\n            except __thonny_helper.builtins.OSError as e:\n                __thonny_result[__thonny_name] = __thonny_helper.b')
INFO    thonny.plugins.micropython.backend: Handling command 'get_globals'
DEBUG   thonny.plugins.micropython.bare_metal_backend: Submitting via paste: b'__thonny_helper.print_mgmt_value({name : (__thonny_helper.repr(value),'
```

**Comment by aivarannamaa** [comment]
TODO: Only reduce block size for certain VID/PID

**Comment by aivarannamaa** [comment]
It looks like it's not possible to get paste mode working even with 30-byte blocks (usually works, but not always). Better simply avoid paste mode for this device

**Comment by aivarannamaa** [comment]
Tried also upgrading USB driver -- no help
