### ISSUE TITLE
Range marker fails with parenthesized call function or attribute value

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#218]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/218) by Anonymous.**

----------------------------------------

Running Thonny 2.0.7 (Expert Mode) on Windows 8.1.

When I run the following code in debug mode:

```
print((str(2)+".").ljust(3))
```

It outputs the following error message, but then works: (Note: some of the file link has been shortened)

```
#!

Traceback (most recent call last):
  File "C:\Users\...\ast_utils.py", line 189, in _mark_text_ranges_rec
    tokens = _mark_end_and_return_child_tokens(node, tokens, prelim_end_lineno, prelim_end_col_offset)
  File "C:\Users\...\ast_utils.py", line 274, in _mark_end_and_return_child_tokens
    _strip_trailing_junk_from_expressions(tokens)
  File "C:\Users\...\ast_utils.py", line 213, in _strip_trailing_junk_from_expressions
    while (tokens[-1].type not in (token.RBRACE, token.RPAR, token.RSQB,
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\...\ast_utils.py", line 189, in _mark_text_ranges_rec
    tokens = _mark_end_and_return_child_tokens(node, tokens, prelim_end_lineno, prelim_end_col_offset)
  File "C:\Users\...\ast_utils.py", line 301, in _mark_end_and_return_child_tokens
    assert tokens[-1].type == token.NAME
AssertionError

```

Any IDEas?

**Comment by aivarannamaa** [comment]
Fixed by using asttokens
