### ISSUE TITLE
clone feature [ : ] throws an exception

### ISSUE THREAD

**Issue by rhenley1947** [thonny/thonny#2182]
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 1712, in event_generate
    handler(event)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 1213, in _handle_debugger_progress
    _current_debugger.handle_debugger_progress(msg)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 278, in handle_debugger_progress
    self._main_frame_visualizer.update_this_and_next_frames(msg)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 407, in update_this_and_next_frames
    self._update_this_frame(msg, frame_info)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 590, in _update_this_frame
    FrameVisualizer._update_this_frame(self, msg, frame_info)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 466, in _update_this_frame
    self._expression_box.update_expression(msg, frame_info)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 671, in update_expression
    and msg["exception_info"]["is_fresh"]
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 799, in _highlight_range
    self.text.tag_add(tag, start_index, end_index)
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 3346, in tag_add
    (self._w, 'tag', 'add', tagName, index1) + args)
_tkinter.TclError: bad text index "2_14"
```

**Comment by aivarannamaa** [comment]
Thank you for the report!

Can you give me an example program for reproducing this? Which Thonny version are you using?

**Comment by aivarannamaa** [comment]
May be related to #2053

**Comment by aivarannamaa** [comment]
Will investigate under #2053
