### ISSUE TITLE
Internal Error after warning about not showing long lines on the shell

### ISSUE THREAD

**Issue by villares** [thonny/thonny#2220]
Thonny 3.3.14
"For performance reasons the Shell avoids showing very long lines (see 'Tools" ... "

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/villares/.local/lib/python3.10/site-packages/thonny/shell.py", line 596, in <lambda>
    btn.bind("<1>", lambda e: self._show_squeezed_text(btn), True)
  File "/home/villares/.local/lib/python3.10/site-packages/thonny/shell.py", line 651, in _show_squeezed_text
    dlg = SqueezedTextDialog(self, button)
  File "/home/villares/.local/lib/python3.10/site-packages/thonny/shell.py", line 1537, in __init__
    self._wrap_var = tk.BooleanVar(False)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 610, in __init__
    Variable.__init__(self, master, value, name)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'bool' object has no attribute '_root'

```

![image](https://user-images.githubusercontent.com/3694604/160952883-be7ce132-5e8f-44c9-a521-5eda9f0309c0.png)

**Comment by aivarannamaa** [comment]
Thank you for the report!

This bug is fixed by now (as of 4.0.0b1, fixed in 16c5961c)
