### ISSUE TITLE
printing failed (thonny 4.0.0b1)

### ISSUE THREAD

**Issue by speedy-10** [thonny/thonny#2233]
Hi if I try to print a file in Thonny 4.0.0b1 with ubuntu 20.04, I get the following error message:

`Traceback (most recent call last):
  File "/home/USER/apps/thonny/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/USER/apps/thonny/lib/python3.10/site-packages/thonny/workbench.py", line 1004, in dispatch
    handler()
  File "/home/USER/apps/thonny/lib/python3.10/site-packages/thonny/plugins/printing/__init__.py", line 44, in print_current_script
    if sys.platform == "darwin":
NameError: name 'sys' is not defined
`
Regards

**Comment by aivarannamaa** [comment]
Thank you for the report! Will fix this right away.
