### ISSUE TITLE
"ERROR   thonny.backend: Exception in _trace" immediately when stepping through working kivy apps

### ISSUE THREAD

**Issue by Ardemus** [thonny/thonny#2270]
I've been working on a simple Kivy App. I've had a few bugs and wanted to step through the code, but launching the debugger and pressing F6-F8, or any of the 4 toolbar buttons, immediately throws an error in the Thonny library and kills the stepper: the stepper buttons are disabled, F6-F8 just produces the OS "not allowed" tone, and the app proceeds as if I pressed resume.

I initially thought that it might be caused by the bugs in my code, but it happened every time with different issues, so went back and tried to step through the working app with the same results. Then I also reproduced it by stepping into this basic hello world app:

```
import kivy
kivy.require('2.1.0') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):

    def build(self):
        return Label(text='Hello world')

if __name__ == '__main__':
    MyApp().run()
```

Here is the ERROR in context from the Thonny Shell tab:

```
Python 3.7.9 (bundled)
>>> %cd /home/nick/Documents/PythonPractice
>>> %Debug hello_world.py
[INFO   ] [Logger      ] Record log in /home/nick/.kivy/logs/kivy_22-05-02_26.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/nick/apps/thonny/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.9 (default, Apr 30 2021, 16:54:34) 
[GCC 5.4.0 20160609]
[INFO   ] [Python      ] Interpreter at "/home/nick/apps/thonny/bin/python3.7"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
ERROR   thonny.backend: Exception in _trace
Traceback (most recent call last):
  File "/home/nick/apps/thonny/lib/python3.7/site-packages/thonny/plugins/cpython/cpython_backend.py", line 1787, in _trace
    return self._trace_and_catch(frame, event, arg)
  File "/home/nick/apps/thonny/lib/python3.7/site-packages/thonny/plugins/cpython/cpython_backend.py", line 1832, in _trace_and_catch
    self._handle_progress_event(frame.f_back, event, marker_function_args, node)
  File "/home/nick/apps/thonny/lib/python3.7/site-packages/thonny/plugins/cpython/cpython_backend.py", line 1890, in _handle_progress_event
    self._save_current_state(frame, event, args, node)
  File "/home/nick/apps/thonny/lib/python3.7/site-packages/thonny/plugins/cpython/cpython_backend.py", line 1987, in _save_current_state
    + sys.stderr._processed_symbol_count
AttributeError: 'LogFile' object has no attribute '_processed_symbol_count'
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.5
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer 
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 21.3.5'>
[INFO   ] [GL          ] OpenGL vendor <b'AMD'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon RX 580 Series (POLARIS10, DRM 3.44.0, 5.16.11-76051611-generic, LLVM 12.0.1)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
```

Here are my environment details:

Thonny 3.3.13 (fresh install using the bash scrip from the project website)
Pop_OS! 21.10
Python 3.7.9
Tk 8.6.10
Kivy 2.1.0 (installed through the Thonny system shell using the [full] dependencies option as described on the [kivy website](https://kivy.org/doc/stable/gettingstarted/installation.html) (I did not create a virtual environment, though I assume that Thonny operates in one).
Nothing else

**Comment by aivarannamaa** [comment]
I could not reproduce exact same problem, but I saw that Thonny's "nicer" debugger (Ctrl+F5) is too slow for Kivy programs. The "faster" debugger (Shift+F5) works better, but in the end of the debuggin session I still got an error, which I'll investigate later:

```
19:38:03.836 INFO    thonny: TIME/MODS 4.272 Reading debugger command DebuggerCommand(allow_stepping_into_libraries=False, breakpoints={}, focus=TextRange(lineno=15, col_offset=0, end_lineno=16, end_col_offset=0), frame_id=31314968, id='cmd_155', local_cwd='C:\\workspaces\\python_stuff', name='step_over', state='line') 
19:38:03.929 INFO    thonny: TIME/MODS 0.093 Sending message debugger_return_response 
19:38:03.929 INFO    thonny: TIME/MODS 0.000 Sending message ToplevelResponse 
19:38:03.929 INFO    thonny.backend: Loading Jedi
19:38:03.929 INFO    thonny: TIME/MODS 0.000 Before loading Jedi 
19:38:03.937 INFO    thonny.common: Using THONNY_FRONTEND_SYS_PATH ['C:\\Users\\Maris\\AppData\\Local\\JetBrains\\Toolbox\\apps\\PyCharm-C\\ch-0\\213.7172.26\\jbr\\bin', 'C:\\workspaces\\python_stuff\\thonny-pico', 'C:\\workspaces\\python_stuff\\thonny', 'C:\\Python310-32\\python310.zip', 'C:\\Python310-32\\DLLs', 'C:\\Python310-32\\lib', 'C:\\Python310-32', 'C:\\workspaces\\python_stuff\\thonny\\venv310', 'C:\\workspaces\\python_stuff\\thonny\\venv310\\lib\\site-packages', 'C:\\workspaces\\python_stuff\\thonny\\venv310\\.thonny\\plugins\\Python310-32\\site-packages']
19:38:04.128 ERROR   thonny.backend: mainloop error
Traceback (most recent call last):
  File "C:\workspaces\python_stuff\thonny\thonny\backend.py", line 80, in mainloop
    self._handle_normal_command(msg)
  File "C:\workspaces\python_stuff\thonny\thonny\plugins\cpython_backend\cp_back.py", line 187, in _handle_normal_command
    super()._handle_normal_command(cmd)
  File "C:\workspaces\python_stuff\thonny\thonny\backend.py", line 305, in _handle_normal_command
    self.send_message(real_response)
  File "C:\workspaces\python_stuff\thonny\thonny\plugins\cpython_backend\cp_back.py", line 832, in send_message
    self._check_load_jedi()
  File "C:\workspaces\python_stuff\thonny\thonny\backend.py", line 522, in _check_load_jedi
    try_load_modules_with_frontend_sys_path(["jedi", "parso"])
  File "C:\workspaces\python_stuff\thonny\thonny\common.py", line 758, in try_load_modules_with_frontend_sys_path
    execute_with_frontend_sys_path(load)
  File "C:\workspaces\python_stuff\thonny\thonny\common.py", line 743, in execute_with_frontend_sys_path
    return function()
  File "C:\workspaces\python_stuff\thonny\thonny\common.py", line 754, in load
    import_module(name)
  File "C:\Python310-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\__init__.py", line 32, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, preload_module
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\api\__init__.py", line 21, in <module>
    from jedi.api import classes
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\api\classes.py", line 24, in <module>
    from jedi.inference.utils import unite
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\inference\__init__.py", line 70, in <module>
    from jedi.inference import imports
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\inference\imports.py", line 21, in <module>
    from jedi.inference import sys_path
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\inference\sys_path.py", line 7, in <module>
    from jedi.inference.base_value import ContextualizedNode
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\inference\base_value.py", line 18, in <module>
    from jedi.inference.utils import safe_property
  File "C:\workspaces\python_stuff\thonny\venv310\lib\site-packages\jedi\inference\utils.py", line 7, in <module>
    _sep = os.path.sep
AttributeError: module 'ntpath' has no attribute 'sep'
19:38:04.148 INFO    thonny: TIME/MODS 0.219 Sending message ProgramOutput (+38 modules)
```
