### ISSUE TITLE
Open... produces errror

### ISSUE THREAD

**Issue by FueLee** [thonny/thonny#2302]
Hi,

"Open..." action produces error when zenity is used for file dialogs, in case file is finally not selected (so, cancel button is clicked).

Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 1961, in toolbar_handler
    handler(*args)
  File "/usr/lib/python3/dist-packages/thonny/editors.py", line 772, in _cmd_open_file
    path = askopenfilename(
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 1885, in askopenfilename
    return _get_dialog_provider().askopenfilename(**options)
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 1941, in askopenfilename
    return cls._call(args)
  File "/usr/lib/python3/dist-packages/thonny/ui_utils.py", line 2008, in _call
    print(result.stderr, file=sys.stderr)
BrokenPipeError: [Errno 32] Broken pipe

Version 3.3.14

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which OS are you using? I can't reproduce this in Ubuntu 20.04.

Also, which zenity version do you have (execute `zenity --version` on command line)?

**Comment by FueLee** [comment]
Hi,
![bug](https://user-images.githubusercontent.com/95375431/170966051-fe1a14a2-bc16-41a3-9cff-7731d00bb17d.png)

zenity --version = 3.42.1

**Comment by aivarannamaa** [comment]
I see, my zenity version is `3.32.0`.

Zenity updates have caused problems before... I'll implement a work-around in the next beta of Thonny 4.0
