### ISSUE TITLE
ERROR   thonny.backend: Exception in _trace

### ISSUE THREAD

**Issue by bingsi1** [thonny/thonny#2367]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 1787, in _trace
    return self._trace_and_catch(frame, event, arg)
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 1832, in _trace_and_catch
    self._handle_progress_event(frame.f_back, event, marker_function_args, node)
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 1891, in _handle_progress_event
    self._respond_to_commands()
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 2018, in _respond_to_commands
    self._fetch_next_debugger_command(frame)
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 1444, in _fetch_next_debugger_command
    cmd = self._backend._fetch_next_incoming_message()
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 173, in _fetch_next_incoming_message
    self._read_one_incoming_message()
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\backend.py", line 119, in _read_one_incoming_message
    line = self._read_incoming_msg_line()
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 203, in _read_incoming_msg_line
    return self._original_stdin.readline()
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\codecs.py", line 319, in decode
    def decode(self, input, final=False):
  File "C:\Users\Administrator\Desktop\thonny-v3.3.13\lib\site-packages\thonny\plugins\cpython\cpython_backend.py", line 163, in signal_handler
    raise KeyboardInterrupt("Execution interrupted")
KeyboardInterrupt: Execution interrupted

**Comment by aivarannamaa** [comment]
Than you for the report!

Did you enter Ctrl-C when you got this trace?
