### ISSUE TITLE
Could not import numpy library to thonny

### ISSUE THREAD

**Issue by assan** [thonny/thonny#2371]
The following message appears after trying to import numpy package to Thonny:
C:\Users\Professional\AppData\Local\Programs\Thonny\python.exe -m pip install --no-cache-dir --user numpy --disable-pip-version-check

a is 3 and b is 7 and c is 10
a is 25 and b is 5 and c is 24
a is 100 and b is 5 and c is 50
Could not import runpy module
Traceback (most recent call last):
  File "C:\Users\Professional\AppData\Local\Programs\Thonny\lib\runpy.py", line 15, in <module>
    import importlib.util
  File "C:\Users\Professional\AppData\Local\Programs\Thonny\lib\importlib\util.py", line 14, in <module>
    from contextlib import contextmanager
  File "C:\Users\Professional\AppData\Local\Programs\Thonny\lib\contextlib.py", line 5, in <module>
    from collections import deque
  File "C:\Users\Professional\AppData\Local\Programs\Thonny\lib\collections\__init__.py", line 22, in <module>
    from keyword import iskeyword as _iskeyword
ImportError: cannot import name 'iskeyword' from 'keyword' (C:\py\keyword.py)
Process returned with code 1

**Comment by aivarannamaa** [comment]
It looks like you have named one your own scripts "keyword.py", but this is causing problems, because Python standard library has module with same name and now your module is shadowing the one in the standard library.

The solution is to rename this file.
