### ISSUE TITLE
Internal error while pressing ctr+d with input in shell - AttributeError: 'Runner' object has no attribute 'winfo_toplevel'

### ISSUE THREAD

**Issue by matousss** [thonny/thonny#2388]
I am using micropython v1.19.1 on esp32. I've noticed that thonny shows Interna Error dialog when I  write something into shell and then press ctrl+d.

Got same error on 3.3.14, 4.0.0b3 and 4.0.0b4
Python 3.10.5
Tk 8.6.12

```Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/thonny-beta/venv/lib/python3.10/site-packages/thonny/workbench.py", line 1024, in dispatch
    handler()
  File "/thonny-beta/venv/lib/python3.10/site-packages/thonny/running.py", line 527, in ctrld
    messagebox.showerror(
  File "/thonny-beta/venv/lib/python3.10/site-packages/thonny/ui_utils.py", line 2396, in wrapper
    _check_dialog_parent(options)
  File "/thonny-beta/venv/lib/python3.10/site-packages/thonny/ui_utils.py", line 2015, in _check_dialog_parent
    parent = options["master"].winfo_toplevel()
AttributeError: 'Runner' object has no attribute 'winfo_toplevel'
```
![image](https://user-images.githubusercontent.com/69765321/184632194-0f60f05f-72bc-4b01-966b-df6ae2f94ce1.png)

Steps to reproduce:
- Connect esp32
- Open shell and write anything (don't press enter!)
- Press ctrl+d

**Comment by aivarannamaa** [comment]
Thank you for the report!

I could reproduce it and the fix will be in the next release.
