### ISSUE TITLE
Thonny won't run program if shell window is closed

### ISSUE THREAD

**Issue by thelmuth** [thonny/thonny#2412]
In any program (including an empty one), if I click the "play" button with the shell window closed, it does not run and I get this error:

```text
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 1273, in _submit_input
    get_shell().set_title("")
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 159, in set_title
    notebook.tab(container, text=title)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/ttk.py", line 896, in tab
    return _val_or_dict(self.tk, kw, self._w, "tab", tab_id)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/ttk.py", line 298, in _val_or_dict
    res = tk.call(*(args + options))
_tkinter.TclError: .!frame.!automaticpanedwindow.!automaticpanedwindow2.!automaticnotebook.!frame is not managed by .!frame.!automaticpanedwindow.!automaticpanedwindow2.!automaticnotebook
```

I get this different error if I hit the stop button:

```text
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/workbench.py", line 1776, in event_generate
    handler(event)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 1418, in _on_backend_terminated
    get_shell().set_title("")
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 159, in set_title
    notebook.tab(container, text=title)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/ttk.py", line 896, in tab
    return _val_or_dict(self.tk, kw, self._w, "tab", tab_id)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/ttk.py", line 298, in _val_or_dict
    res = tk.call(*(args + options))
_tkinter.TclError: .!frame.!automaticpanedwindow.!automaticpanedwindow2.!automaticnotebook.!frame is not managed by .!frame.!automaticpanedwindow.!automaticpanedwindow2.!automaticnotebook
```

Opening up the shell window fixes everything. I've been using Thonny for years (for teaching), and don't remember seeing this bug before 4.0.0. I have reproduced on 2 MacOS laptops.

**Comment by aivarannamaa** [comment]
Thank you for the report!

I was able to reproduce this and will fix it for 4.0.1
