### ISSUE TITLE
Thonny crashes on exit()

### ISSUE THREAD

**Issue by Rohukas** [thonny/thonny#2433]
**Environment:**
Thonny 4.0.0
Darwin 21.6.0 (64-bit)
Python 3.10.6 (64-bit)
Tk 8.6.12
Running on M1 Pro 14 Inch.

**Code to reproduce:**
```
if True:
    print("Hello, world.")
    exit()
print(f"Crash")
```
**How to reproduce.**
Run the code in thonny. Click on the shell window. Press enter. This should lead to a crash.

**Impact**
Thonny does not save user action logs when it crashes this way. This can be devastating to students who encounter this crash during a test/exam as they now have to prove they wrote the code without the logs.

**Crash log:**
```
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/tktextext.py", line 243, in dispatch
    return fun(event)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 1012, in perform_return
    EnhancedTextWithLogging.perform_return(self, event)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/tktextext.py", line 468, in perform_return
    self.insert("insert", "\n")
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 974, in intercept_insert
    self._try_submit_input()
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 1163, in _try_submit_input
    self._submit_input(submittable_text)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/shell.py", line 1320, in _submit_input
    get_runner().send_program_input(text_to_be_submitted)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/running.py", line 309, in send_program_input
    self._proxy.send_program_input(data)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/running.py", line 1057, in send_program_input
    self._send_msg(InputSubmission(data))
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/running.py", line 1050, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by aivarannamaa** [comment]
Thank you for the report!

I could reproduce this. This is pretty bad and I'll fix this for version 4.0.1. Hopefully I'll manage to release it by the end of this week.
