### ISSUE TITLE
Specific file name makes file unusable

### ISSUE THREAD

**Issue by spencerhartland** [thonny/thonny#2635]
Last night I saved my work, quit Thonny, and logged out of my user account. Using Thonny today, I have found that a file with a specific name cannot be opened if stored on Raspberry Pi Pico. I have a file named 'server.py,' trying to open the version stored on the Pi fails and provides the following traceback:

`Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/base_file_browser.py", line 586, in on_double_click
    self.open_file(path)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/base_file_browser.py", line 1201, in open_file
    get_workbench().get_editor_notebook().show_remote_file(path)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/editors.py", line 1069, in show_remote_file
    return self.show_file(make_remote_path(target_filename))
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/editors.py", line 1056, in show_file
    self.select(editor)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/ttk.py", line 885, in select
    return self.tk.call(self._w, "select", tab_id)
_tkinter.TclError: .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook.!editor2 is not managed by .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook` 

I can, however, open a copy of the same file stored locally on my computer. I've tried deleting the file on the Pi and re-uploading from the computer but this does not resolve the problem. I can, of course, rename the file on the computer ('network.py') and upload that to the Pi. The renamed filed can be opened from the Pi, but I'd prefer the name I'd originally chosen. I'm using Thonny 4.0.2 on macOS 13.0 and the Pi is running MicroPython v1.19.1-837-g67fac4ebc.

**Comment by aivarannamaa** [comment]
Thank you for the report!

Can you easily repeat this issue? Any chance the crash with this specific file name have been coincidence?
