### ISSUE TITLE
Thonny no longer works with circuitpython devices

### ISSUE THREAD

**Issue by drdyer9051** [thonny/thonny#2662]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 514, in _start_runner
    self._runner.start()
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 122, in start
    self.restart_backend(False, True)
  File "/usr/lib/python3/dist-packages/thonny/running.py", line 612, in restart_backend
    self._proxy = backend_class(clean)
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/__init__.py", line 86, in __init__
    self._fix_port()
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/__init__.py", line 122, in _fix_port
    elif not port_exists(self._port):
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/__init__.py", line 892, in port_exists
    for port in list_serial_ports():
  File "/usr/lib/python3/dist-packages/thonny/plugins/micropython/__init__.py", line 880, in list_serial_ports
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'

**Comment by aivarannamaa** [comment]
Have you recently installed a package named `serial`? Or uninstalled `pyserial`? Please go to "Tools => Manage plug-ins" -- Thonny needs to have `pyserial` in the list on the left and **not** have `serial` in the same list.

If this is OK, then look for `serial.py` or a directory named `serial` in your working space.
