### ISSUE TITLE
ESP32 "OSError: Wifi Internal Error"

### ISSUE THREAD

**Issue by Ersoks** [thonny/thonny#2713]
Hello, after several hours of testing without results, I turn to you, it is impossible for me to connect my esp32 (micropython) to my wifi network... Everything was working a few days ago, but I modified my script, it didn't didn't work anymore, and since then, even putting back my original script, it doesn't work anymore...

Here is my original script:

`import socket

from machine import Pin
import network

import esp
esp.osdebug(None)

import gc
gc.collect()

sta_if = network.WLAN(network.STA_IF); sta_if.active(True)
sta_if.scan()                             # Scan for available access points
sta_if.connect("....", "....")# Connect to an AP
sta_if.isconnected()                   # Check for successful connection

print('network config:', sta_if.ifconfig())

led = Pin(2, Pin.OUT)

`

Here is my new script:

`import socket

from machine import Pin
import network

import esp
esp.osdebug(None)

import gc
gc.collect()

ssid = '....'
password = '....'

sta_if = network.WLAN(network.STA_IF)
if not sta_if.isconnected():
    print('connecting to network...')
    sta_if.active(True)
    sta_if.connect(ssid, password)
    while not sta_if.isconnected():
        pass
    print('network config:', sta_if.ifconfig())

led = Pin(2, Pin.OUT)

`
I always have the OSError: Wifi Internal Error

`MPY: soft reboot
E (781062) wifi:sta is connecting, return error
Traceback (most recent call last):
  File "boot.py", line 14, in <module>
OSError: Wifi Internal Error
`
`MPY: soft reboot
E (781062) wifi:sta is connecting, return error
Traceback (most recent call last):
  File "boot.py", line 19, in <module>
OSError: Wifi Internal Error
`

Sorry if my English is not good, I'm French and not the best in English.

**Comment by aivarannamaa** [comment]
It looks like this error is not specific to Thonny. Please try https://github.com/orgs/micropython/discussions
