### ISSUE TITLE
Thonjy in termux?  How to get this running?

### ISSUE THREAD

**Issue by 6SwC** [thonny/thonny#2715]
```
s-4.5.0 wheel-0.40.0 wrapt-1.15.0
~ $ thonny
04:27:21.324 INFO    thonny: Thonny version: 4.0.2
04:27:21.325 INFO    thonny: cwd: /data/data/com.termux/files/home
04:27:21.326 INFO    thonny: original argv: ['/data/data/com.termux/files/usr/bin/python3', '/data/data/com.termux/files/usr/bin/thonny']
04:27:21.327 INFO    thonny: sys.executable: /data/data/com.termux/files/usr/bin/python3
04:27:21.327 INFO    thonny: sys.argv: ['/data/data/com.termux/files/usr/bin/thonny']
04:27:21.328 INFO    thonny: sys.path: ['/data/data/com.termux/files/usr/bin', '/data/data/com.termux/files/usr/lib/python310.zip', '/data/data/com.termux/files/usr/lib/python3.10', '/data/data/com.termux/files/usr/lib/python3.10/lib-dynload', '/data/data/com.termux/files/usr/lib/python3.10/site-packages']
04:27:21.329 INFO    thonny: sys.flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0, dev_mode=False, utf8_mode=0, warn_default_encoding=0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/thonny/__init__.py", line 253, in launch
    from thonny import workbench
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/thonny/workbench.py", line 13, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/thonny", line 8, in <module>
    sys.exit(launch())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/thonny/__init__.py", line 260, in launch
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
~ $
```

**Comment by aivarannamaa** [comment]
I don't think Tkinter (Thonny's UI toolkit) can be run on Android.
