### ISSUE TITLE
A jedi-related crash

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#274]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/274) by me.**

----------------------------------------

```
#!plain-text

INFO: Loading early plugins from ['C:\\Users\\toomasm\\AppData\\Local\\Programs\\Thonny\\python36.zip', 'C:\\Users\\toomasm\\AppData\\Local\\Programs\\Thonny\\DLLs', 'C:\\Users\\toomasm\\AppData\\Local\\Programs\\Thonny\\lib', 'C:\\Users\\toomasm\\AppData\\Local\\Programs\\Thonny', 'C:\\Users\\toomasm\\AppData\\Local\\Programs\\Thonny\\lib\\site-packages', 'C:\\Users\\toomasm\\.thonny\\plugins\\Python36\\site-packages']
ERROR: Problem when updating name highlighting
Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 119, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\highlight_names.py", line 58, in update
    for pos in self.get_positions():
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\highlight_names.py", line 40, in get_positions
    return self.get_positions_for_script(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\highlight_names.py", line 233, in get_positions_for_script
    module_node = jedi_utils.get_module_node(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\jedi_utils.py", line 3, in get_module_node
    return script._get_module_node()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 121, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\api\__init__.py", line 140, in _get_module_node
    diff_cache=True,
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\__init__.py", line 104, in parse
    new_lines=lines
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\diff.py", line 174, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (10 != 11) with the diff parser. Please report:
--- 
+++ 
@@ -7,4 +7,5 @@
 
 def checker(buttons):
     global click
-    if buttons["text"] ==  "+    if buttons["text"] == "
+)
ERROR: Problem when updating local variable tags
Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 119, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 123, in update
    highlight_positions = self.get_positions_correct_but_using_private_parts()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 85, in get_positions_correct_but_using_private_parts
    module = jedi_utils.get_module_node(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\jedi_utils.py", line 3, in get_module_node
    return script._get_module_node()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 121, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\api\__init__.py", line 140, in _get_module_node
    diff_cache=True,
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\__init__.py", line 104, in parse
    new_lines=lines
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\diff.py", line 174, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (10 != 11) with the diff parser. Please report:
--- 
+++ 
@@ -7,4 +7,5 @@
 
 def checker(buttons):
     global click
-    if buttons["text"] ==  "+    if buttons["text"] == "
+)
ERROR: Problem when updating local variable tags
Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 119, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 123, in update
    highlight_positions = self.get_positions_correct_but_using_private_parts()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 85, in get_positions_correct_but_using_private_parts
    module = jedi_utils.get_module_node(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\jedi_utils.py", line 3, in get_module_node
    return script._get_module_node()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 121, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\api\__init__.py", line 140, in _get_module_node
    diff_cache=True,
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\__init__.py", line 104, in parse
    new_lines=lines
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\diff.py", line 174, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (10 != 11) with the diff parser. Please report:
--- 
+++ 
@@ -7,4 +7,5 @@
 
 def checker(buttons):
     global click
-    if buttons["text"] ==  " +    if buttons["text"] == " 
+)
ERROR: Problem when updating name highlighting
Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 119, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\highlight_names.py", line 58, in update
    for pos in self.get_positions():
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\highlight_names.py", line 40, in get_positions
    return self.get_positions_for_script(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\highlight_names.py", line 233, in get_positions_for_script
    module_node = jedi_utils.get_module_node(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\jedi_utils.py", line 3, in get_module_node
    return script._get_module_node()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 121, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\api\__init__.py", line 140, in _get_module_node
    diff_cache=True,
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\__init__.py", line 104, in parse
    new_lines=lines
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\diff.py", line 174, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (11 != 12) with the diff parser. Please report:
--- 
+++ 
@@ -8,4 +8,5 @@
 def checker(buttons):
     global click
     if buttons["text"] == " " and click == True:
-        buttons["text"] =  "+        buttons["text"] = "
+)
ERROR: Problem when updating local variable tags
Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 119, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 123, in update
    highlight_positions = self.get_positions_correct_but_using_private_parts()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 85, in get_positions_correct_but_using_private_parts
    module = jedi_utils.get_module_node(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\jedi_utils.py", line 3, in get_module_node
    return script._get_module_node()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 121, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\api\__init__.py", line 140, in _get_module_node
    diff_cache=True,
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\__init__.py", line 104, in parse
    new_lines=lines
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\diff.py", line 174, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (11 != 12) with the diff parser. Please report:
--- 
+++ 
@@ -8,4 +8,5 @@
 def checker(buttons):
     global click
     if buttons["text"] == " " and click == True:
-        buttons["text"] =  "+        buttons["text"] = "
+)
ERROR: Problem when updating local variable tags
Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 119, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 123, in update
    highlight_positions = self.get_positions_correct_but_using_private_parts()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\locals_marker.py", line 85, in get_positions_correct_but_using_private_parts
    module = jedi_utils.get_module_node(script)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\thonny\jedi_utils.py", line 3, in get_module_node
    return script._get_module_node()
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\cache.py", line 121, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\api\__init__.py", line 140, in _get_module_node
    diff_cache=True,
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\__init__.py", line 104, in parse
    new_lines=lines
  File "C:\Users\toomasm\AppData\Local\Programs\Thonny\lib\site-packages\jedi\parser\python\diff.py", line 174, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (11 != 12) with the diff parser. Please report:
--- 
+++ 
@@ -8,4 +8,5 @@
 def checker(buttons):
     global click
     if buttons["text"] == " " and click == True:
-        buttons["text"] =  "X+        buttons["text"] = "X
+)



```

**Comment by aivarannamaa** [comment]
Hopefully irrelevant with newer jedi version
