### ISSUE TITLE
Cant clear the shell

### ISSUE THREAD

**Issue by VyshnavArun** [thonny/thonny#2770]
shows this error

```
Traceback (most recent call last):
  File "C:\Users\Vychu\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Vychu\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 1262, in _clear_shell
    self._clear_content(end_index)
  File "C:\Users\Vychu\AppData\Local\Programs\Thonny\lib\site-packages\thonny\shell.py", line 1335, in _clear_content
    btn_pos = float(self.index(btn))
ValueError: could not convert string to float: 
```

**Comment by aivarannamaa** [comment]
Please try the newest Thonny version as this problem may be already fixed.

**Comment by aivarannamaa** [comment]
Please reopen if you still have this problem
