### ISSUE TITLE
ModuleNotFoundError: No module named 'dbus_next'

### ISSUE THREAD

**Issue by wohltat** [thonny/thonny#2771]
With version 4.1.0b1 i always get the following error when choosing the backend in the lower right corner:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/boogieman/build/thonny/thonny/workbench.py", line 861, in _post_backend_menu
    if uf2_device_is_present_in_bootloader_mode():
  File "/home/boogieman/build/thonny/thonny/plugins/micropython/uf2dialog.py", line 249, in uf2_device_is_present_in_bootloader_mode
    for vol in list_volumes(skip_letters=["A"]):
  File "/home/boogieman/build/thonny/thonny/misc_utils.py", line 99, in list_volumes
    from dbus_next.errors import DBusError
ModuleNotFoundError: No module named 'dbus_next'
```

When i install it via 'Tools'->'Manage Plug-Ins' it seems to work.

**Comment by aivarannamaa** [comment]
Thanks! I'll fix this before the final 4.1.0
