### ISSUE TITLE
CRASH - macOS Ventura + Thonny 4.0.2 / Thonny 4.1.0b1

### ISSUE THREAD

**Issue by IAmOrion** [thonny/thonny#2783]
Saw other posts about this, but Thonny crashes under macOS Ventura when trying to change the interpreter.  4.0.2 insta-crashed, 4.1.0b1 crashes more gracefully and actually give a traceback shown below:

`Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/backend_config_page.py", line 128, in _backend_changed
    page = self._get_conf_page(backend_desc)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/backend_config_page.py", line 146, in _get_conf_page
    self._conf_pages[backend_desc] = cp_constructor(self.labelframe)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/micropython/mp_front.py", line 458, in __init__
    self._ports_by_desc["< " + tr("Try to detect port automatically") + " >"] = "auto"
TypeError: 'set' object does not support item assignment`

**Comment by aivarannamaa** [comment]
Thanks and sorry for the late reply. This has been already fixed (115ab502) but not released yet.
