### ISSUE TITLE
Get an error while want to flash esp32 with a local image file on Thonny 4.1.0

### ISSUE THREAD

**Issue by robmlee** [thonny/thonny#2811]
I just upgrade my Thonny to 4.1.0 on my Win 10 PC. When I want to flash esp32 with a pre downloaded  image file on my PC, I got an error mesg as follows:

`Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\base_flashing_dialog.py", line 434, in _perform_work_and_update_status
    temp_file = self._download_to_temp(download_info)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\esptool_dialog.py", line 259, in _download_to_temp
    return super()._download_to_temp(download_info)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\base_flashing_dialog.py", line 474, in _download_to_temp
    shutil.copyfile(download_url, target_path)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'E:\\AIoT-ESP32-CAM\\MicroPython-Camera-Support\\Shariltumin\\firmware-2023-06-07.bin' and 'E:\\AIoT-ESP32-CAM\\MicroPython-Camera-Support\\Shariltumin\\firmware-2023-06-07.bin' are the same file`

And my friend did the same way on his Mac, it works just fine.

**Comment by aivarannamaa** [comment]
Thanks for the report! I found the bug. The fix will be in 4.1.1
