### ISSUE TITLE
_tkinter.TclError: couldn't recognize data in image file - thonny.png

### ISSUE THREAD

**Issue by TrainerRed151** [thonny/thonny#2818]
I have run `pip install thonny` in a pyenv virtualenv running Python 3.9.2 on a 2017 MacBook Pro running MacOS Catalina 10.15.7 and get the following error when I try and run thonny from the command line:

```
Traceback (most recent call last):
  File "/Users/brian/.pyenv/versions/pico/bin/thonny", line 8, in <module>
    sys.exit(launch())
  File "/Users/brian/.pyenv/versions/3.9.2/envs/pico/lib/python3.9/site-packages/thonny/__init__.py", line 237, in launch
    if not _check_welcome():
  File "/Users/brian/.pyenv/versions/3.9.2/envs/pico/lib/python3.9/site-packages/thonny/__init__.py", line 211, in _check_welcome
    win = FirstRunWindow(mgr)
  File "/Users/brian/.pyenv/versions/3.9.2/envs/pico/lib/python3.9/site-packages/thonny/first_run.py", line 30, in __init__
    self.logo = tk.PhotoImage(file=logo_file)
  File "/Users/brian/.pyenv/versions/3.9.2/lib/python3.9/tkinter/__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Users/brian/.pyenv/versions/3.9.2/lib/python3.9/tkinter/__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/Users/brian/.pyenv/versions/3.9.2/envs/pico/lib/python3.9/site-packages/thonny/res/thonny.png"
```

**Comment by aivarannamaa** [comment]
How did you install this Python 3.9? If this installation uses macOS's own Tcl/Tk 8.5, which is too old for Thonny.
