### ISSUE TITLE
PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_globals' 

### ISSUE THREAD

**Issue by amir16yp** [thonny/thonny#2833]
I was working on my usual projects, when suddenly i get this error, and now cant compile my projects :( 
PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_globals' (thonny.plugins.micropython.mp_back.ManagementError: Script produced errors).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.
here's the backend.log:
```
05:03:26.213 [MainThread] INFO    thonny: Thonny version: 4.1.1
05:03:26.213 [MainThread] INFO    thonny: cwd: C:\Users\pc\Desktop\New folder
05:03:26.213 [MainThread] INFO    thonny: original argv: ['C:\\Program Files (x86)\\Thonny\\python.exe', '-I', '-u', '-B', 'C:\\Program Files (x86)\\Thonny\\lib\\site-packages\\thonny\\plugins\\rp2040\\rp2040_back.py', "{'clean': False, 'port': 'COM3', 'dtr': None, 'rts': None, 'submit_mode': 'raw_paste', 'interrupt_on_connect': True, 'write_block_size': 64, 'write_block_delay': None, 'proxy_class': 'RaspberryPiPicoBackendProxy', 'sync_time': True, 'validate_time': False, 'local_rtc': True}"]
05:03:26.213 [MainThread] INFO    thonny: sys.executable: C:\Program Files (x86)\Thonny\python.exe
05:03:26.213 [MainThread] INFO    thonny: sys.argv: ['C:\\Program Files (x86)\\Thonny\\lib\\site-packages\\thonny\\plugins\\rp2040\\rp2040_back.py', "{'clean': False, 'port': 'COM3', 'dtr': None, 'rts': None, 'submit_mode': 'raw_paste', 'interrupt_on_connect': True, 'write_block_size': 64, 'write_block_delay': None, 'proxy_class': 'RaspberryPiPicoBackendProxy', 'sync_time': True, 'validate_time': False, 'local_rtc': True}"]
05:03:26.214 [MainThread] INFO    thonny: sys.path: ['C:\\Program Files (x86)\\Thonny\\python310.zip', 'C:\\Program Files (x86)\\Thonny\\DLLs', 'C:\\Program Files (x86)\\Thonny\\lib', 'C:\\Program Files (x86)\\Thonny', 'C:\\Program Files (x86)\\Thonny\\lib\\site-packages']
05:03:26.214 [MainThread] INFO    thonny: sys.flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=1, no_user_site=1, no_site=0, ignore_environment=1, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=1, dev_mode=False, utf8_mode=0, warn_default_encoding=0, int_max_str_digits=-1)
05:03:26.215 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Starting backend, args: {'clean': False, 'port': 'COM3', 'dtr': None, 'rts': None, 'submit_mode': 'raw_paste', 'interrupt_on_connect': True, 'write_block_size': 64, 'write_block_delay': None, 'proxy_class': 'RaspberryPiPicoBackendProxy', 'sync_time': True, 'validate_time': False, 'local_rtc': True}
05:03:26.231 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Initial submit_mode: raw_paste, write_block_size: 64, write_block_delay: 0, read_block_size: 0
05:03:26.232 [MainThread] INFO    thonny.plugins.micropython.mp_back: Initializing MicroPythonBackend of type RP2040Backend
05:03:26.233 [MainThread] INFO    thonny: TIME/MODS 0.911 before prepare (+73 modules)
05:03:26.233 [MainThread] INFO    thonny: NEW MODS ['__future__', '_bz2', '_compression', '_ctypes', '_datetime', '_heapq', '_lzma', '_queue', '_struct', '_tkinter', 'binascii', 'bz2', 'ctypes', 'ctypes._endian', 'ctypes.wintypes', 'datetime', 'encodings.ascii', 'errno', 'faulthandler', 'fnmatch', 'gettext', 'heapq', 'lzma', 'math', 'msvcrt', 'pathlib', 'platform', 'posixpath', 'queue', 'serial', 'serial.serialutil', 'serial.serialwin32', 'serial.win32', 'shlex', 'shutil', 'signal', 'struct', 'subprocess', 'textwrap', 'thonny.backend', 'thonny.base_file_browser', 'thonny.codeview', 'thonny.config_ui', 'thonny.editors', 'thonny.languages', 'thonny.misc_utils', 'thonny.plugins', 'thonny.plugins.backend_config_page', 'thonny.plugins.micropython', 'thonny.plugins.micropython.bare_metal_backend', 'thonny.plugins.micropython.connection', 'thonny.plugins.micropython.mp_back', 'thonny.plugins.micropython.mp_common', 'thonny.plugins.micropython.mp_front', 'thonny.plugins.micropython.serial_connection', 'thonny.plugins.micropython.webrepl_connection', 'thonny.roughparse', 'thonny.running', 'thonny.tktextext', 'thonny.ui_utils', 'thonny.workdlg', 'tkinter', 'tkinter.commondialog', 'tkinter.constants', 'tkinter.dialog', 'tkinter.filedialog', 'tkinter.font', 'tkinter.messagebox', 'tkinter.simpledialog', 'tkinter.ttk', 'urllib', 'urllib.parse', 'zlib']
05:03:26.234 [MainThread] INFO    thonny.plugins.micropython.mp_back: Sending interrupt
05:03:26.235 [MainThread] INFO    thonny.plugins.micropython.mp_back: Done sending interrupt
05:03:26.287 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Poking
05:03:26.318 [MainThread] INFO    thonny: TIME/MODS 0.085 got welcome 
05:03:26.318 [MainThread] INFO    thonny: TIME/MODS 0.000 bef preparing helpers 
05:03:26.319 [MainThread] INFO    thonny.plugins.micropython.mp_back: Preparing helpers
05:03:26.321 [MainThread] INFO    thonny: TIME/MODS 0.003 befsubcode 
05:03:26.321 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Requesting raw mode at b'>>> '
05:03:26.323 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Discarding stdout: '\r\n'
05:03:26.350 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Discarding stdout: ''
05:03:26.351 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Entered raw prompt
05:03:26.394 [MainThread] INFO    thonny: TIME/MODS 0.073 affsubcode 
05:03:26.430 [MainThread] INFO    thonny: TIME/MODS 0.036 affforw 
05:03:26.430 [MainThread] INFO    thonny: TIME/MODS 0.000 prepared helpers 
05:03:26.430 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
05:03:26.433 [MainThread] INFO    thonny: TIME/MODS 0.003 affsubcode 
05:03:26.461 [MainThread] INFO    thonny: TIME/MODS 0.028 affforw 
05:03:26.461 [MainThread] INFO    thonny: TIME/MODS 0.000 got cwd 
05:03:26.461 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
05:03:26.464 [MainThread] INFO    thonny: TIME/MODS 0.003 affsubcode 
05:03:26.477 [MainThread] INFO    thonny: TIME/MODS 0.013 affforw 
05:03:26.478 [MainThread] INFO    thonny: TIME/MODS 0.001 prepared 
05:03:26.478 [MainThread] INFO    thonny.plugins.micropython.mp_back: Prepared
05:03:26.478 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
05:03:26.480 [MainThread] INFO    thonny: TIME/MODS 0.002 affsubcode 
05:03:26.509 [MainThread] INFO    thonny: TIME/MODS 0.029 affforw 
05:03:26.509 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
05:03:26.517 [MainThread] INFO    thonny: TIME/MODS 0.008 affsubcode 
05:03:26.541 [MainThread] INFO    thonny: TIME/MODS 0.024 affforw 
05:03:26.542 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
05:03:26.557 [MainThread] INFO    thonny: TIME/MODS 0.016 affsubcode 
05:03:26.589 [MainThread] INFO    thonny: TIME/MODS 0.032 affforw 
05:03:26.590 [MainThread] INFO    thonny.backend: Loading Jedi
05:03:26.590 [MainThread] INFO    thonny: TIME/MODS 0.001 Before loading Jedi 
05:03:26.591 [MainThread] INFO    thonny.common: Using THONNY_FRONTEND_SYS_PATH ['C:\\Program Files (x86)\\Thonny\\python310.zip', 'C:\\Program Files (x86)\\Thonny\\DLLs', 'C:\\Program Files (x86)\\Thonny\\lib', 'C:\\Program Files (x86)\\Thonny', 'C:\\Program Files (x86)\\Thonny\\lib\\site-packages', 'C:\\Users\\pc\\AppData\\Roaming\\Thonny\\plugins\\Python310\\site-packages']
05:03:27.565 [MainThread] INFO    thonny: TIME/MODS 0.975 After loading Jedi (+123 modules)
05:03:27.565 [MainThread] INFO    thonny: NEW MODS ['_blake2', '_compat_pickle', '_hashlib', '_json', '_pickle', '_socket', 'difflib', 'filecmp', 'gc', 'hashlib', 'importlib._abc', 'importlib.util', 'jedi', 'jedi._compatibility', 'jedi.api', 'jedi.api.classes', 'jedi.api.completion', 'jedi.api.completion_cache', 'jedi.api.environment', 'jedi.api.errors', 'jedi.api.exceptions', 'jedi.api.file_name', 'jedi.api.helpers', 'jedi.api.interpreter', 'jedi.api.keywords', 'jedi.api.project', 'jedi.api.refactoring', 'jedi.api.refactoring.extract', 'jedi.api.strings', 'jedi.cache', 'jedi.common', 'jedi.debug', 'jedi.file_io', 'jedi.inference', 'jedi.inference.analysis', 'jedi.inference.arguments', 'jedi.inference.base_value', 'jedi.inference.cache', 'jedi.inference.compiled', 'jedi.inference.compiled.access', 'jedi.inference.compiled.getattr_static', 'jedi.inference.compiled.mixed', 'jedi.inference.compiled.subprocess', 'jedi.inference.compiled.subprocess.functions', 'jedi.inference.compiled.value', 'jedi.inference.context', 'jedi.inference.docstring_utils', 'jedi.inference.docstrings', 'jedi.inference.filters', 'jedi.inference.flow_analysis', 'jedi.inference.gradual', 'jedi.inference.gradual.annotation', 'jedi.inference.gradual.base', 'jedi.inference.gradual.conversion', 'jedi.inference.gradual.generics', 'jedi.inference.gradual.stub_value', 'jedi.inference.gradual.type_var', 'jedi.inference.gradual.typeshed', 'jedi.inference.gradual.typing', 'jedi.inference.gradual.utils', 'jedi.inference.helpers', 'jedi.inference.imports', 'jedi.inference.lazy_value', 'jedi.inference.names', 'jedi.inference.param', 'jedi.inference.parser_cache', 'jedi.inference.recursion', 'jedi.inference.references', 'jedi.inference.signature', 'jedi.inference.syntax_tree', 'jedi.inference.sys_path', 'jedi.inference.utils', 'jedi.inference.value', 'jedi.inference.value.decorator', 'jedi.inference.value.dynamic_arrays', 'jedi.inference.value.function', 'jedi.inference.value.instance', 'jedi.inference.value.iterable', 'jedi.inference.value.klass', 'jedi.inference.value.module', 'jedi.parser_utils', 'jedi.plugins', 'jedi.plugins.django', 'jedi.plugins.flask', 'jedi.plugins.pytest', 'jedi.plugins.registry', 'jedi.plugins.stdlib', 'jedi.settings', 'json', 'json.decoder', 'json.encoder', 'json.scanner', 'parso', 'parso._compatibility', 'parso.cache', 'parso.file_io', 'parso.grammar', 'parso.normalizer', 'parso.parser', 'parso.pgen2', 'parso.pgen2.generator', 'parso.pgen2.grammar_parser', 'parso.python', 'parso.python.diff', 'parso.python.errors', 'parso.python.parser', 'parso.python.pep8', 'parso.python.prefix', 'parso.python.token', 'parso.python.tokenize', 'parso.python.tree', 'parso.tree', 'parso.utils', 'pickle', 'pkgutil', 'pydoc', 'pydoc_data', 'pydoc_data.topics', 'select', 'selectors', 'socket', 'sysconfig', 'zipfile']
05:03:27.566 [MainThread] INFO    thonny: TIME/MODS 0.001 sent ready 
05:03:27.566 [MainThread] INFO    thonny: TIME/MODS 0.000 Beginning of mainloop 
05:03:27.566 [MainThread] INFO    thonny: TIME/MODS 0.000 before get_dirs_children_info 
05:03:27.566 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
05:03:27.584 [MainThread] INFO    thonny: TIME/MODS 0.018 affsubcode 
05:03:27.615 [MainThread] INFO    thonny: TIME/MODS 0.031 affforw 
05:03:27.616 [MainThread] INFO    thonny: TIME/MODS 0.001 after get_dirs_children_info 
05:03:27.638 [MainThread] INFO    thonny: TIME/MODS 0.022 before get_globals 
05:03:27.639 [MainThread] INFO    thonny: TIME/MODS 0.001 befsubcode 
05:03:27.651 [MainThread] INFO    thonny: TIME/MODS 0.012 affsubcode 
05:03:27.678 [MainThread] INFO    thonny: TIME/MODS 0.027 affforw 
05:03:27.678 [MainThread] ERROR   thonny.backend: Exception while handling 'get_globals'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\backend.py", line 284, in _handle_normal_command
    response = handler(cmd)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\mp_back.py", line 653, in _cmd_get_globals
    globs = self._evaluate(
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\mp_back.py", line 566, in _evaluate
    raise ManagementError("Script produced errors", script, out, err)
thonny.plugins.micropython.mp_back.ManagementError: Script produced errors
05:03:27.681 [MainThread] ERROR   thonny.plugins.micropython.mp_back: ManagementError details:
SCRIPT: __thonny_helper.print_mgmt_value({name : (__thonny_helper.repr(value), __thonny_helper.builtins.id(value)) for (name, value) in __thonny_helper.builtins.globals().items() if not name.startswith('__')})

STDOUT: 

STDERR: Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "<stdin>", line 1, in <dictcomp>

NameError: name '__thonny_helper' isn't defined




```

**Comment by aivarannamaa** [comment]
Thank you for the report!

I've seen similar error when MicroPython has executed code with certain errors in it (see https://github.com/micropython/micropython/issues/7171). Do you happen to have the exact copy of your code elsewhere?
