### ISSUE TITLE
Double Clicking on a file crashes Thonny in 4.1.1

### ISSUE THREAD

**Issue by jouellnyc** [thonny/thonny#2837]
File exists and is valid. I can load Significantly larger files than the one that makes Thonny fail.

If I download the file to the PC, I can open it in Thonny....

Soft reboot does not help.

Hard reboot does not help either.

If I create a new file and try to save it as the one on the esp32, Thonny says the file is open, but it's not open in the IDE.

Various tests like this suggest the file contents don't seem to be the problem. 

frontend.log:

```
20:21:38.733 [MainThread] INFO    thonny.shell: BaseShellText.restart(False)
20:22:50.014 [MainThread] ERROR   thonny.workbench: Internal error
Traceback (most recent call last):
  File "/home/myhome/apps/thonny/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/base_file_browser.py", line 590, in on_double_click
    self.open_file(path)
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/base_file_browser.py", line 1205, in open_file
    get_workbench().get_editor_notebook().show_remote_file(path)
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/editors.py", line 1076, in show_remote_file
    return self.show_file(make_remote_path(target_filename))
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/editors.py", line 1063, in show_file
    self.select(editor)
  File "/home/myhome/apps/thonny/lib/python3.10/tkinter/ttk.py", line 885, in select
    return self.tk.call(self._w, "select", tab_id)
_tkinter.TclError: .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook.!editor2 is not managed by .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook
20:22:50.029 [MainThread] INFO    thonny.ui_utils: Parent y: 50, rooty: 50, vrooty: 0
20:22:50.030 [MainThread] INFO    thonny.ui_utils: Placing .!longtextdialog2 with geometry +608+466
20:23:50.704 [MainThread] ERROR   thonny.workbench: Internal error
Traceback (most recent call last):
  File "/home/myhome/apps/thonny/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/base_file_browser.py", line 590, in on_double_click
    self.open_file(path)
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/base_file_browser.py", line 1205, in open_file
    get_workbench().get_editor_notebook().show_remote_file(path)
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/editors.py", line 1076, in show_remote_file
    return self.show_file(make_remote_path(target_filename))
  File "/home/myhome/apps/thonny/lib/python3.10/site-packages/thonny/editors.py", line 1063, in show_file
    self.select(editor)
  File "/home/myhome/apps/thonny/lib/python3.10/tkinter/ttk.py", line 885, in select
    return self.tk.call(self._w, "select", tab_id)
_tkinter.TclError: .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook.!editor2 is not managed by .!frame.!automaticpanedwindow.!automaticpanedwindow2.!editornotebook
20:23:50.720 [MainThread] INFO    thonny.ui_utils: Parent y: 50, rooty: 50, vrooty: 0
20:23:50.720 [MainThread] INFO    thonny.ui_utils: Placing .!longtextdialog3 with geometry +608+466

```

**Comment by aivarannamaa** [comment]
Thank you for the report!

Which Thonny version are you using? The latest is 4.1.1 and it's worth trying this.
