### ISSUE TITLE
Support for Thonny on Wayland

### ISSUE THREAD

**Issue by mrgreen3** [thonny/thonny#2838]
Was wondering if Thonny will work under Wayland other than using xorg-xwayland?

The error i am getting is:

`  File "/usr/lib/python3.11/site-packages/thonny/workbench.py", line 133, in __init__
    tk.Tk.__init__(self, className="Thonny")
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2326, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: no display name and no $DISPLAY environment variable
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/thonny/__init__.py", line 255, in launch
    bench = workbench.Workbench()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/thonny/workbench.py", line 133, in __init__
    tk.Tk.__init__(self, className="Thonny")
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2326, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: no display name and no $DISPLAY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/thonny/__main__.py", line 4, in <module>
    launch()
  File "/usr/lib/python3.11/site-packages/thonny/__init__.py", line 267, in launch
    dlg = ui_utils.LongTextDialog("Internal error", traceback.format_exc())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/thonny/ui_utils.py", line 1954, in __init__
    super().__init__(master=parent)
  File "/usr/lib/python3.11/site-packages/thonny/ui_utils.py", line 132, in __init__
    assert master
AssertionError`

**Comment by mrgreen3** [comment]
Thonny works fine with xorg-xwayland, but would prefer not to use it. So I have loaded Thonny on my laptop and have xorg-xwayland installed and everything works fine.

Sorry for the noise.....
