### ISSUE TITLE
blocking ui when removing esp32 device

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#2839]
by disconnecting a mp esp32 device from usb port thonny blocks the ui, or it becomes very very slow responsive.

in addition there is an error window:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/benutzer/repo/thonny/thonny/running.py", line 586, in _cmd_interrupt_with_shortcut
    self._cmd_interrupt()
  File "/home/benutzer/repo/thonny/thonny/running.py", line 545, in _cmd_interrupt
    self._proxy.interrupt()
  File "/home/benutzer/repo/thonny/thonny/plugins/micropython/mp_front.py", line 185, in interrupt
    self._send_msg(ImmediateCommand("interrupt"))
  File "/home/benutzer/repo/thonny/thonny/running.py", line 1146, in _send_msg
    self._proc.stdin.write(serialize_message(msg) + "\n")
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by kr-g** [comment]
it constantly prints into shell panel without entering an error mode

![Bildschirmfoto_2023-07-01_07-48-16](https://github.com/thonny/thonny/assets/23188189/a71903c3-951e-407a-96b8-5db3c5dd02c3)

**Comment by kr-g** [comment]
it happens only when removing a device with running code (as it looks like)

**Comment by kr-g** [comment]
duplicate of https://github.com/thonny/thonny/issues/2836

**Comment by aivarannamaa** [comment]
Thank you for the report! I'll close this and handle the problem under #2836.
