### ISSUE TITLE
NameError: name 'border_color' is not defined

### ISSUE THREAD

**Issue by wohltat** [thonny/thonny#2842]
```
>>> python3 -m thonny
19:36:07.522 [MainThread] INFO    thonny: Thonny version: 4.1.1
19:36:07.522 [MainThread] INFO    thonny: cwd: /home/user/build/thonny
19:36:07.526 [MainThread] INFO    thonny: original argv: ['python3', '-m', 'thonny']
19:36:07.526 [MainThread] INFO    thonny: sys.executable: /home/user/build/thonny/thonny_venv/bin/python3
19:36:07.526 [MainThread] INFO    thonny: sys.argv: ['/home/user/build/thonny/thonny/__main__.py']
19:36:07.526 [MainThread] INFO    thonny: sys.path: ['/home/user/build/thonny', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/user/build/thonny/thonny_venv/lib/python3.8/site-packages']
19:36:07.527 [MainThread] INFO    thonny: sys.flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0, dev_mode=False, utf8_mode=0)
19:36:07.658 [MainThread] INFO    thonny.workbench: Starting Workbench
19:36:07.774 [MainThread] INFO    thonny.workbench: Creating runner
19:36:07.790 [MainThread] INFO    thonny.workbench: Start loading plugins
19:36:07.852 [MainThread] INFO    thonny.workbench: Done loading plugins
ERROR:root:Internal launch or mainloop error
Traceback (most recent call last):
  File "/home/user/build/thonny/thonny/__init__.py", line 255, in launch
    bench = workbench.Workbench()
  File "/home/user/build/thonny/thonny/workbench.py", line 181, in __init__
    self._init_containers()
  File "/home/user/build/thonny/thonny/workbench.py", line 761, in _init_containers
    "nw": AutomaticNotebook(
  File "/home/user/build/thonny/thonny/ui_utils.py", line 687, in __init__
    super().__init__(master, closable=closable)
  File "/home/user/build/thonny/thonny/custom_notebook.py", line 29, in __init__
    super().__init__(master, background=border_color)
NameError: name 'border_color' is not defined
19:36:08.065 [MainThread] INFO    thonny.ui_utils: Parent y: 27, rooty: 27, vrooty: 0
19:36:08.065 [MainThread] INFO    thonny.ui_utils: Placing .!longtextdialog with geometry +2014+428
(thonny_venv) 

```

on latest: 
5e8948d8db95d980f2df4436f7834d9e26b14b8f - Progress with CustomToolbutton, #2760

but first on: 
a4c22ac54cafa11477c6b271f9dd8680775716f8 - Start using CustomNotebook, #2737

--------

```
> uname -a
Linux computer 5.4.0-149-generic #166-Ubuntu SMP Tue Apr 18 16:51:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by aivarannamaa** [comment]
This is now fixed.
