### ISSUE TITLE
Thonny with ESP32 running MicroPython on a Vitualbox Machine!

### ISSUE THREAD

**Issue by Zorbadil** [thonny/thonny#2883]
I'm using an ESP32DEVKIT V1 running a 1.20 version of micropython.  Thonny connects to it fine in the native operating system (windows 10), but if I pass the USB port (com10) across to my ubuntu virtual machine running on virtualbox, and use Thonny on the VM, when I try to open the option at the bottom right of the screen to select the python version, or ESP board, I get the following error:

```
Traceback (most recent call last):
  File "/snap/thonny/79/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/snap/thonny/79/lib/python3.10/site-packages/thonny/workbench.py", line 847, in _post_backend_menu
    entries = backend.proxy_class.get_switcher_entries()
  File "/snap/thonny/79/lib/python3.10/site-packages/thonny/plugins/micropython/mp_front.py", line 374, in get_switcher_entries
    for device, desc in cls._detect_potential_ports():
  File "/snap/thonny/79/lib/python3.10/site-packages/thonny/plugins/micropython/mp_front.py", line 199, in _detect_potential_ports
    all_ports = list_serial_ports()
  File "/snap/thonny/79/lib/python3.10/site-packages/thonny/plugins/micropython/mp_front.py", line 994, in list_serial_ports
    _PORTS_CACHE = _list_serial_ports_uncached(skip_logging=skip_logging)
  File "/snap/thonny/79/lib/python3.10/site-packages/thonny/plugins/micropython/mp_front.py", line 1028, in _list_serial_ports_uncached
    for p in comports():
  File "/snap/thonny/79/lib/python3.10/site-packages/serial/tools/list_ports_linux.py", line 102, in comports
    for info in [SysFS(d) for d in devices]
  File "/snap/thonny/79/lib/python3.10/site-packages/serial/tools/list_ports_linux.py", line 102, in <listcomp>
    for info in [SysFS(d) for d in devices]
  File "/snap/thonny/79/lib/python3.10/site-packages/serial/tools/list_ports_linux.py", line 48, in __init__
    num_if = int(self.read_line(self.usb_device_path, 'bNumInterfaces'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

The same thing happens if I pass across the USB port for my rpi Pico W.

**Comment by aivarannamaa** [comment]
Please try running following command in your VM: 

```
python3 -m serial.tools.list_ports
```

If this fails as well, then you should report this issue at https://github.com/pyserial/pyserial/issues

**Comment by Zorbadil** [comment]
I gave this a try, and it appears that python is finding the ports fine.  The serial port ttyS0 is my Arduino Uno, also connected via USB,  which appears to present itself  as a serial port.  This works fine with the Arduino IDE.

ttyUSB0 is my ESP32DEVKITV1, which describes itself as a CP2102 USB to UART Bridge Controller, which is the onboard usb to serial interface.  I understand that this controller can be problematic for developers, but it works fine with Thonny running on the host Windows 10 system.

nik@nik-VirtualBox:~$ python3 -m serial.tools.list_ports
/dev/ttyS0          
/dev/ttyUSB0        
2 ports found
nik@nik-VirtualBox:~$ 

after running the command I ran Thonny, and as soon as I click in the bottom right hand corner of the Thonny window to change the device, the same error as before occurs.

**Comment by capecrusader-121** [comment]
@Zorbadil  Is this on arm64 ?

**Comment by Zorbadil** [comment]
Indeed it is.  Ubuntu 22.04 64-bit, running on VirtualBox 7.0.10 r 158379 (Qt5.15.2), running on Windows 10 22H2 (OS Build 19045.3208)

**Comment by aivarannamaa** [comment]
Closing as I don't think I can do anything in Thonny's side.
