### ISSUE TITLE
MicroPython images download error

### ISSUE THREAD

**Issue by bh1rio** [thonny/thonny#2912]
Error log:
Downloading from https://micropython.org/resources/firmware/esp32c3-20230426-v1.20.0.bin

Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\base_flashing_dialog.py", line 434, in _perform_work_and_update_status
    temp_file = self._download_to_temp(download_info)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\esptool_dialog.py", line 259, in _download_to_temp
    return super()._download_to_temp(download_info)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\base_flashing_dialog.py", line 495, in _download_to_temp
    with urlopen(req, timeout=5) as fsrc:
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Thonny\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by aivarannamaa** [comment]
Thank you for the report!

It looks like there was refactoring of the board names and download pages in MicroPython project: https://github.com/orgs/micropython/discussions/12294

Please download the firmware manually for now and use the "hamburger menu" button (☰) for selecting the firmware from disk.

I'll try to refactor my link-scraping script and upload new links soon.
