### ISSUE TITLE
Problem in backend while handling Circuitpython errors on M0 board

### ISSUE THREAD

**Issue by DavePutz** [thonny/thonny#2914]
Running latest Thonny (4.1.2) on Windows 10; connecting to a Metro M0 Express running Circuitpython 8.2.4.
Just typing in the REPL a command that will throw an error (such as "dir(board)" without importing board first)
I see in the Shell window:
```
PROBLEM IN THONNY'S BACK-END: Exception while handling 'execute_source' (ConnectionError: EOF).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your CircuitPython device and try again.


Process ended with exit code 1.
Couldn't find the device automatically. 
Check the connection (making sure the device is not in bootloader mode) or choose
"Configure interpreter" in the interpreter menu (bottom-right corner of the window)
to select specific port or another interpreter.

Process ended with exit code None.
```
Running the same command on an RP2040 board running CP 8.2.4 gives the expected response:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'board' is not defined
```

The backend log shows:
```
12:25:40.103 [MainThread] ERROR   thonny.backend: Exception while handling 'execute_source'
Traceback (most recent call last):
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\backend.py", line 285, in _handle_normal_command
    response = handler(cmd)
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\mp_back.py", line 642, in _cmd_execute_source
    self._execute(source, capture_output=False)
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\mp_back.py", line 524, in _execute
    self._execute_with_consumer(script, self._send_output)
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 723, in _execute_with_consumer
    self._process_output_until_active_prompt(output_consumer)
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 875, in _process_output_until_active_prompt
    new_data = self._connection.soft_read_until(
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 67, in soft_read_until
    return self.read_until(terminator, timeout, timeout_is_soft=True)
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 83, in read_until
    self.check_for_error()
  File "G:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\micropython\connection.py", line 135, in check_for_error
    raise ConnectionError(self._error)
ConnectionError: EOF
```
If I use a terminal emulator such as TeraTerm to connect to the board I will get the expected error when running "dir(board)".

Note that I cannot be positive that this is entirely a Thonny issue, as running Circuitpython 7 on the same Metro M0 board
will handle the error correctly. If you can point me to some difference coming from Circuitpython I can investigate there as well.

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for the late reply!

I could reproduce this in Windows 10 but not in macOS Ventura. Haven't tried Linux yet.

At the moment I don't have any ideas how to approach this. I'll revisit this when the problem persists with the next CircuitPython version.
