### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by ryancaulfieldd** [thonny/thonny#2917]
Traceback (most recent call last):
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 524, in _start_runner
    self._runner.start()
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 155, in start
    self.restart_backend(False, True)
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 730, in restart_backend
    self._proxy = backend_class(clean)
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\cpython_frontend\cp_front.py", line 37, in __init__
    super().__init__(clean, executable)
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 994, in __init__
    self._start_background_process(clean=clean)
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 1088, in _start_background_process
    self._proc = subprocess.Popen(
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Ryan Canfield\AppData\Local\Programs\Thonny\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] The parameter is incorrect

This error keeps showing up when I install.

**Comment by aivarannamaa** [comment]
Which Windows version are you using? Which Thonny version?

> This error keeps showing up when I install.

Do you really mean "install"? It looks to me like something that happens when Thonny starts up.
