### ISSUE TITLE
CircuitPython  upload file fail

### ISSUE THREAD

**Issue by bbllmaster** [thonny/thonny#2930]
device:Wemos Lolin C3 Mini with ESP32-C3FH4 

```
E:\adafruit-circuitpython-bundle-8.x-mpy-20230807\lib\adafruit_ble\__init__.mpy (3409 bytes)
PROBLEM IN THONNY'S BACK-END: Exception while handling 'upload' (thonny.plugins.micropython.mp_back.ProtocolError: Could not complete raw paste).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your CircuitPython device and try again.


Process ended with exit code 1.
```

**Comment by aivarannamaa** [comment]
Thank you for the report! 

Unfortunately I can't reproduce this with Thonny 4.1.2, Windows 11 and CircuitPython 8.6.2. Which versions are you using?

**Comment by bbllmaster** [comment]
I can reproduce this , 
`
D:\os\esp\esp32c3 circuitpython ssd1306\lib\myboard.py (854 bytes)
PROBLEM IN THONNY'S BACK-END: Exception while handling 'upload' (thonny.plugins.micropython.mp_back.ProtocolError: Could not get raw-paste confirmation).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your CircuitPython device and try again.


Process ended with exit code 1.
`

**Comment by bbllmaster** [comment]
> Thank you for the report!
> 
> Unfortunately I can't reproduce this with Thonny 4.1.2, Windows 11 and CircuitPython 8.6.2. Which versions are you using?

it test on 4.1.2 and 4.1.3         windows11

**Comment by davidvfx07** [comment]
Got the same error here with SeeedStudio XIAO-ESP32C3.

**Comment by aivarannamaa** [comment]
@davidvfx07, thanks! I now tried uploading to a SeeedStudio XIAO-ESP32C3 and could reproduce this problem. Will investigate further.

**Comment by aivarannamaa** [comment]
The problem occurred both in Win11 and macOS Sonoma (haven't tried Linux yet), both with CircuitPython 8.2.8 and 9.0.0a5 (with the latter it sometimes occurred even with earlier management commands).

Importantly, the same problem occurs when trying to upload a file with [mpremote](https://docs.micropython.org/en/latest/reference/mpremote.html):

```
 data % mpremote cp data.json :
cp data.json :
 ... copying   6% [#-------------------]^CTraceback (most recent call last):
  File "/Users/aa/python_stuff/thonny/venv312/bin/mpremote", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/main.py", line 528, in main
    handler_func(state, args)
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/commands.py", line 159, in do_filesystem
    state.transport.filesystem_command(
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/transport_serial.py", line 476, in filesystem_command
    op(src2, dest2, progress_callback=progress_callback)
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/transport_serial.py", line 420, in fs_put
    self.exec("w(" + repr(data) + ")")
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/transport_serial.py", line 285, in exec
    ret, ret_err = self.exec_raw(command, data_consumer=data_consumer)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/transport_serial.py", line 271, in exec_raw
    self.exec_raw_no_follow(command)
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/transport_serial.py", line 249, in exec_raw_no_follow
    return self.raw_paste_write(command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/transport_serial.py", line 225, in raw_paste_write
    data = self.read_until(1, b"\x04")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/mpremote/transport_serial.py", line 118, in read_until
    data = self.serial.read(min_num_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aa/python_stuff/thonny/venv312/lib/python3.12/site-packages/serial/serialposix.py", line 565, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

I tried uploading with this file: 
[circuitpython-variants-esptool.json](https://github.com/thonny/thonny/files/13463585/circuitpython-variants-esptool.json)

**Comment by aivarannamaa** [comment]
I reported it at CircuitPython issue tracker. You can start following this issue: https://github.com/adafruit/circuitpython/issues/8658
