### ISSUE TITLE
Installation Thonny on Linux, Thonny not work

### ISSUE THREAD

**Issue by 99Key-357** [thonny/thonny#2933]
Hi, I installed thonny both from the command line and via the file downloaded from the site.
When I try to run the code I get this error 
Traceback (most recent call last):
  File "/snap/thonny/185/lib/python3.10/site-packages/thonny/shell.py", line 1262, in _submit_input
    argv = parse_cmd_line(cmd_line[1:])
  File "/snap/thonny/185/lib/python3.10/site-packages/thonny/misc_utils.py", line 294, in parse_cmd_line
    return shlex.split(s, posix=True)
  File "/snap/thonny/185/lib/python3.10/shlex.py", line 315, in split
    return list(lex)
  File "/snap/thonny/185/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/snap/thonny/185/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/snap/thonny/185/lib/python3.10/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation and I searched for solutions on the web but found nothing
![Screenshot from 2023-09-19 15-25-48](https://github.com/thonny/thonny/assets/122654908/7489981f-bfb2-44cf-a95a-f0899f572db2)

**Comment by aivarannamaa** [comment]
Thank you for the report!

You seem to have linebreak in your folder name. This is pretty unusual and Thonny did not expect this. You can work around this problem by renaming your folder.

I'll see whether I can make Thonny work with such names.
