### ISSUE TITLE
Extended exception info is missing

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#2942]
```python
x, y, z = 1, 2, 0
a, b, c = 3, 4, 5
result = (x / y / z) * (a / b / c)
```
should give 
```
Traceback (most recent call last):
  File "/Users/sss/python_stuff/sss/vigad.py", line 3, in <module>
    result = (x / y / z) * (a / b / c)
              ~~~~~~^~~
ZeroDivisionError: float division by zero
```

but gives 

```
Traceback (most recent call last):
  File "/Users/sss/python_stuff/sss/vigad.py", line 3, in <module>
    result = (x / y / z) * (a / b / c)
ZeroDivisionError: float division by zero
```

**Comment by aivarannamaa** [comment]
Need to check if it still works with Python 3.14
