### ISSUE TITLE
Internal error when no files are opened

### ISSUE THREAD

**Issue by matusmlady** [thonny/thonny#2958]
When closing all opened files but leaving Thonny opened, an internal error pops up. Mostly automatically, even multiple pop ups with the error of the same type are displayed. It is an annoying behaviour :(. After some time there can be even 10+ of them you have to close. I thought they appear when I only single click a file in the left file bar, but now I think the error auto appears in a regular interval. I am using Thonny Flathub version 4.1.3 on Linux Mint 21.2.

Error text:

```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/matus/.var/app/org.thonny.Thonny/config/Thonny/plugins/lib/python3.11/site-packages/thonnycontrib/thonny-autosave/__init__.py", line 30, in save_current
    filename = editor.get_filename(False)
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/matus/.var/app/org.thonny.Thonny/config/Thonny/plugins/lib/python3.11/site-packages/thonnycontrib/thonny-autosave/__init__.py", line 30, in save_current
    filename = editor.get_filename(False)
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/matus/.var/app/org.thonny.Thonny/config/Thonny/plugins/lib/python3.11/site-packages/thonnycontrib/thonny-autosave/__init__.py", line 30, in save_current
    filename = editor.get_filename(False)
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_filename'
```

![image](https://github.com/thonny/thonny/assets/96914042/66929843-eb24-453d-87c2-77c878ef89f8)

**Comment by aivarannamaa** [comment]
Sorry for the late reply!

It looks like the problem is caused by a plug-in you have installed -- `thonny-autosave`. You should contact the author of the plug-in.
