### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by eugenerod33** [thonny/thonny#2976]
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/lib/python3/dist-packages/thonny/shell.py", line 1268, in _clear_shell
    self._clear_content(end_index)
  File "/usr/lib/python3/dist-packages/thonny/shell.py", line 1361, in _clear_content
    btn_pos = float(self.index(btn))
ValueError: could not convert string to float: ''

**Comment by Moosems** [comment]
Could you give more information on reproducing this issue?

**Comment by aivarannamaa** [comment]
@eugenerod33, if you still have this problem with the latest Thonny version (4.1.3) then please reopen this issue and try to find the steps for reproducing this.
