### ISSUE TITLE
PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_globals' (thonny.plugins.micropython.mp_back.ManagementError: Could not parse management response)

### ISSUE THREAD

**Issue by JatsuLC** [thonny/thonny#2977]
Currently running micropython v1.21.0 and thonny 4.1.3. I get the following error whenever I try running my code.
PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_globals' (thonny.plugins.micropython.mp_back.ManagementError: Could not parse management response)

I have attached the backend.log text. Any idea on what to do or how to fix this?

```
00:07:05.518 [MainThread] INFO    thonny: Thonny version: 4.1.3
00:07:05.518 [MainThread] INFO    thonny: cwd: E:\Chrome Downloads\Pi pico code\Adafruit_Blinka-8.16.1\Adafruit_Blinka-8.16.1\src
00:07:05.518 [MainThread] INFO    thonny: original argv: ['E:\\Program Files\\Thonny\\python.exe', '-s', '-u', '-B', 'E:\\Program Files\\Thonny\\lib\\site-packages\\thonny\\plugins\\esp\\esp_back.py', "{'clean': True, 'port': 'COM9', 'dtr': None, 'rts': None, 'submit_mode': None, 'interrupt_on_connect': True, 'write_block_size': None, 'write_block_delay': None, 'proxy_class': 'ESP32Proxy', 'sync_time': True, 'validate_time': False, 'local_rtc': True}"]
00:07:05.518 [MainThread] INFO    thonny: sys.executable: E:\Program Files\Thonny\python.exe
00:07:05.518 [MainThread] INFO    thonny: sys.argv: ['E:\\Program Files\\Thonny\\lib\\site-packages\\thonny\\plugins\\esp\\esp_back.py', "{'clean': True, 'port': 'COM9', 'dtr': None, 'rts': None, 'submit_mode': None, 'interrupt_on_connect': True, 'write_block_size': None, 'write_block_delay': None, 'proxy_class': 'ESP32Proxy', 'sync_time': True, 'validate_time': False, 'local_rtc': True}"]
00:07:05.518 [MainThread] INFO    thonny: sys.path: ['E:\\Program Files\\Thonny\\lib\\site-packages\\thonny\\plugins\\esp', 'E:\\Program Files\\Thonny\\python310.zip', 'E:\\Program Files\\Thonny\\DLLs', 'E:\\Program Files\\Thonny\\lib', 'E:\\Program Files\\Thonny', 'E:\\Program Files\\Thonny\\lib\\site-packages']
00:07:05.518 [MainThread] INFO    thonny: sys.flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=1, no_user_site=1, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0, dev_mode=False, utf8_mode=0, warn_default_encoding=0, int_max_str_digits=-1)
00:07:05.519 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Starting backend, args: {'clean': True, 'port': 'COM9', 'dtr': None, 'rts': None, 'submit_mode': None, 'interrupt_on_connect': True, 'write_block_size': None, 'write_block_delay': None, 'proxy_class': 'ESP32Proxy', 'sync_time': True, 'validate_time': False, 'local_rtc': True}
00:07:05.616 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Initial submit_mode: raw_paste, write_block_size: 127, write_block_delay: 0, read_block_size: 0
00:07:05.616 [MainThread] INFO    thonny.plugins.micropython.mp_back: Initializing MicroPythonBackend of type EspMicroPythonBackend
00:07:05.617 [MainThread] INFO    thonny: TIME/MODS 0.164 before prepare (+73 modules)
00:07:05.617 [MainThread] INFO    thonny: NEW MODS ['__future__', '_bz2', '_compression', '_ctypes', '_datetime', '_heapq', '_lzma', '_queue', '_struct', '_tkinter', 'binascii', 'bz2', 'ctypes', 'ctypes._endian', 'ctypes.wintypes', 'datetime', 'encodings.ascii', 'errno', 'faulthandler', 'fnmatch', 'gettext', 'heapq', 'lzma', 'math', 'msvcrt', 'pathlib', 'platform', 'posixpath', 'queue', 'serial', 'serial.serialutil', 'serial.serialwin32', 'serial.win32', 'shlex', 'shutil', 'signal', 'struct', 'subprocess', 'textwrap', 'thonny.backend', 'thonny.base_file_browser', 'thonny.codeview', 'thonny.config_ui', 'thonny.editors', 'thonny.languages', 'thonny.misc_utils', 'thonny.plugins', 'thonny.plugins.backend_config_page', 'thonny.plugins.micropython', 'thonny.plugins.micropython.bare_metal_backend', 'thonny.plugins.micropython.connection', 'thonny.plugins.micropython.mp_back', 'thonny.plugins.micropython.mp_common', 'thonny.plugins.micropython.mp_front', 'thonny.plugins.micropython.serial_connection', 'thonny.plugins.micropython.webrepl_connection', 'thonny.roughparse', 'thonny.running', 'thonny.tktextext', 'thonny.ui_utils', 'thonny.workdlg', 'tkinter', 'tkinter.commondialog', 'tkinter.constants', 'tkinter.dialog', 'tkinter.filedialog', 'tkinter.font', 'tkinter.messagebox', 'tkinter.simpledialog', 'tkinter.ttk', 'urllib', 'urllib.parse', 'zlib']
00:07:05.617 [MainThread] INFO    thonny.plugins.micropython.mp_back: Sending interrupt
00:07:05.617 [MainThread] INFO    thonny.plugins.micropython.mp_back: Done sending interrupt
00:07:05.640 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Requesting raw mode at b'>>> '
00:07:05.650 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Discarding stdout: '\r\n'
00:07:05.672 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Discarding stdout: ''
00:07:05.672 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Entered raw prompt
00:07:05.797 [MainThread] INFO    thonny: TIME/MODS 0.180 got welcome 
00:07:05.797 [MainThread] INFO    thonny: TIME/MODS 0.000 bef preparing helpers 
00:07:05.797 [MainThread] INFO    thonny.plugins.micropython.mp_back: Preparing helpers
00:07:05.797 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:05.797 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Requesting raw mode at b'>>> '
00:07:05.800 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Discarding stdout: '\r\n'
00:07:05.827 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Discarding stdout: ''
00:07:05.827 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Entered raw prompt
00:07:05.990 [MainThread] INFO    thonny: TIME/MODS 0.193 affsubcode 
00:07:06.011 [MainThread] INFO    thonny: TIME/MODS 0.021 affforw 
00:07:06.011 [MainThread] INFO    thonny: TIME/MODS 0.000 prepared helpers 
00:07:06.011 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:06.030 [MainThread] INFO    thonny: TIME/MODS 0.019 affsubcode 
00:07:06.057 [MainThread] INFO    thonny: TIME/MODS 0.027 affforw 
00:07:06.057 [MainThread] INFO    thonny: TIME/MODS 0.000 got cwd 
00:07:06.057 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:06.070 [MainThread] INFO    thonny: TIME/MODS 0.013 affsubcode 
00:07:06.089 [MainThread] INFO    thonny: TIME/MODS 0.019 affforw 
00:07:06.089 [MainThread] INFO    thonny: TIME/MODS 0.000 prepared 
00:07:06.089 [MainThread] INFO    thonny.plugins.micropython.mp_back: Prepared
00:07:06.089 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:06.110 [MainThread] INFO    thonny: TIME/MODS 0.021 affsubcode 
00:07:06.230 [MainThread] INFO    thonny: TIME/MODS 0.120 affforw 
00:07:06.230 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:06.280 [MainThread] INFO    thonny: TIME/MODS 0.050 affsubcode 
00:07:06.323 [MainThread] INFO    thonny: TIME/MODS 0.044 affforw 
00:07:06.323 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:06.379 [MainThread] INFO    thonny: TIME/MODS 0.056 affsubcode 
00:07:06.431 [MainThread] INFO    thonny: TIME/MODS 0.052 affforw 
00:07:06.431 [MainThread] INFO    thonny.backend: Loading Jedi
00:07:06.431 [MainThread] INFO    thonny: TIME/MODS 0.000 Before loading Jedi 
00:07:06.431 [MainThread] INFO    thonny.common: Using THONNY_FRONTEND_SYS_PATH ['E:\\Program Files\\Thonny\\python310.zip', 'E:\\Program Files\\Thonny\\DLLs', 'E:\\Program Files\\Thonny\\lib', 'E:\\Program Files\\Thonny', 'E:\\Program Files\\Thonny\\lib\\site-packages', 'C:\\Users\\rigo0\\AppData\\Roaming\\Thonny\\plugins\\Python310\\site-packages']
00:07:06.740 [MainThread] INFO    thonny: TIME/MODS 0.309 After loading Jedi (+123 modules)
00:07:06.740 [MainThread] INFO    thonny: NEW MODS ['_blake2', '_compat_pickle', '_hashlib', '_json', '_pickle', '_socket', 'difflib', 'filecmp', 'gc', 'hashlib', 'importlib._abc', 'importlib.util', 'jedi', 'jedi._compatibility', 'jedi.api', 'jedi.api.classes', 'jedi.api.completion', 'jedi.api.completion_cache', 'jedi.api.environment', 'jedi.api.errors', 'jedi.api.exceptions', 'jedi.api.file_name', 'jedi.api.helpers', 'jedi.api.interpreter', 'jedi.api.keywords', 'jedi.api.project', 'jedi.api.refactoring', 'jedi.api.refactoring.extract', 'jedi.api.strings', 'jedi.cache', 'jedi.common', 'jedi.debug', 'jedi.file_io', 'jedi.inference', 'jedi.inference.analysis', 'jedi.inference.arguments', 'jedi.inference.base_value', 'jedi.inference.cache', 'jedi.inference.compiled', 'jedi.inference.compiled.access', 'jedi.inference.compiled.getattr_static', 'jedi.inference.compiled.mixed', 'jedi.inference.compiled.subprocess', 'jedi.inference.compiled.subprocess.functions', 'jedi.inference.compiled.value', 'jedi.inference.context', 'jedi.inference.docstring_utils', 'jedi.inference.docstrings', 'jedi.inference.filters', 'jedi.inference.flow_analysis', 'jedi.inference.gradual', 'jedi.inference.gradual.annotation', 'jedi.inference.gradual.base', 'jedi.inference.gradual.conversion', 'jedi.inference.gradual.generics', 'jedi.inference.gradual.stub_value', 'jedi.inference.gradual.type_var', 'jedi.inference.gradual.typeshed', 'jedi.inference.gradual.typing', 'jedi.inference.gradual.utils', 'jedi.inference.helpers', 'jedi.inference.imports', 'jedi.inference.lazy_value', 'jedi.inference.names', 'jedi.inference.param', 'jedi.inference.parser_cache', 'jedi.inference.recursion', 'jedi.inference.references', 'jedi.inference.signature', 'jedi.inference.syntax_tree', 'jedi.inference.sys_path', 'jedi.inference.utils', 'jedi.inference.value', 'jedi.inference.value.decorator', 'jedi.inference.value.dynamic_arrays', 'jedi.inference.value.function', 'jedi.inference.value.instance', 'jedi.inference.value.iterable', 'jedi.inference.value.klass', 'jedi.inference.value.module', 'jedi.parser_utils', 'jedi.plugins', 'jedi.plugins.django', 'jedi.plugins.flask', 'jedi.plugins.pytest', 'jedi.plugins.registry', 'jedi.plugins.stdlib', 'jedi.settings', 'json', 'json.decoder', 'json.encoder', 'json.scanner', 'parso', 'parso._compatibility', 'parso.cache', 'parso.file_io', 'parso.grammar', 'parso.normalizer', 'parso.parser', 'parso.pgen2', 'parso.pgen2.generator', 'parso.pgen2.grammar_parser', 'parso.python', 'parso.python.diff', 'parso.python.errors', 'parso.python.parser', 'parso.python.pep8', 'parso.python.prefix', 'parso.python.token', 'parso.python.tokenize', 'parso.python.tree', 'parso.tree', 'parso.utils', 'pickle', 'pkgutil', 'pydoc', 'pydoc_data', 'pydoc_data.topics', 'select', 'selectors', 'socket', 'sysconfig', 'zipfile']
00:07:06.740 [MainThread] INFO    thonny: TIME/MODS 0.000 sent ready 
00:07:06.740 [MainThread] INFO    thonny: TIME/MODS 0.000 Beginning of mainloop 
00:07:06.740 [MainThread] INFO    thonny: TIME/MODS 0.000 before get_globals 
00:07:06.741 [MainThread] INFO    thonny: TIME/MODS 0.001 befsubcode 
00:07:06.773 [MainThread] INFO    thonny: TIME/MODS 0.032 affsubcode 
00:07:06.807 [MainThread] INFO    thonny: TIME/MODS 0.034 affforw 
00:07:06.807 [MainThread] INFO    thonny: TIME/MODS 0.000 after get_globals 
00:07:10.059 [MainThread] INFO    thonny: TIME/MODS 3.252 before write_file 
00:07:10.059 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:10.119 [MainThread] INFO    thonny: TIME/MODS 0.060 affsubcode 
00:07:10.168 [MainThread] INFO    thonny: TIME/MODS 0.049 affforw 
00:07:10.168 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:10.202 [MainThread] INFO    thonny: TIME/MODS 0.034 affsubcode 
00:07:10.231 [MainThread] INFO    thonny: TIME/MODS 0.029 affforw 
00:07:10.231 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:10.262 [MainThread] INFO    thonny: TIME/MODS 0.031 affsubcode 
00:07:10.291 [MainThread] INFO    thonny: TIME/MODS 0.029 affforw 
00:07:10.291 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:10.440 [MainThread] INFO    thonny: TIME/MODS 0.149 affsubcode 
00:07:10.558 [MainThread] INFO    thonny: TIME/MODS 0.119 affforw 
00:07:10.558 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:10.699 [MainThread] INFO    thonny: TIME/MODS 0.141 affsubcode 
00:07:10.792 [MainThread] INFO    thonny: TIME/MODS 0.093 affforw 
00:07:10.792 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:10.929 [MainThread] INFO    thonny: TIME/MODS 0.137 affsubcode 
00:07:11.042 [MainThread] INFO    thonny: TIME/MODS 0.113 affforw 
00:07:11.042 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:11.179 [MainThread] INFO    thonny: TIME/MODS 0.137 affsubcode 
00:07:11.307 [MainThread] INFO    thonny: TIME/MODS 0.129 affforw 
00:07:11.307 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:11.409 [MainThread] INFO    thonny: TIME/MODS 0.102 affsubcode 
00:07:11.479 [MainThread] INFO    thonny: TIME/MODS 0.070 affforw 
00:07:11.479 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:11.500 [MainThread] INFO    thonny: TIME/MODS 0.021 affsubcode 
00:07:11.527 [MainThread] INFO    thonny: TIME/MODS 0.027 affforw 
00:07:11.527 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:11.551 [MainThread] INFO    thonny: TIME/MODS 0.024 affsubcode 
00:07:11.573 [MainThread] INFO    thonny: TIME/MODS 0.023 affforw 
00:07:11.573 [MainThread] INFO    thonny.plugins.micropython.bare_metal_backend: Wrote /ledArray.py in 1.4 seconds
00:07:11.573 [MainThread] INFO    thonny: TIME/MODS 0.000 after write_file 
00:07:11.649 [MainThread] INFO    thonny: TIME/MODS 0.076 before Run 
00:07:11.745 [MainThread] INFO    thonny: TIME/MODS 0.096 befsubcode 
00:07:12.252 [MainThread] INFO    thonny: TIME/MODS 0.506 affsubcode 
00:07:12.499 [MainThread] INFO    thonny: TIME/MODS 0.247 affforw 
00:07:12.499 [MainThread] INFO    thonny: TIME/MODS 0.000 bef preparing helpers 
00:07:12.499 [MainThread] INFO    thonny.plugins.micropython.mp_back: Preparing helpers
00:07:12.499 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:12.671 [MainThread] INFO    thonny: TIME/MODS 0.173 affsubcode 
00:07:12.702 [MainThread] INFO    thonny: TIME/MODS 0.031 affforw 
00:07:12.702 [MainThread] INFO    thonny: TIME/MODS 0.000 prepared helpers 
00:07:12.702 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:12.720 [MainThread] INFO    thonny: TIME/MODS 0.018 affsubcode 
00:07:12.749 [MainThread] INFO    thonny: TIME/MODS 0.029 affforw 
00:07:12.749 [MainThread] INFO    thonny: TIME/MODS 0.000 got cwd 
00:07:12.749 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:12.770 [MainThread] INFO    thonny: TIME/MODS 0.021 affsubcode 
00:07:12.796 [MainThread] INFO    thonny: TIME/MODS 0.026 affforw 
00:07:12.796 [MainThread] INFO    thonny: TIME/MODS 0.000 prepared 
00:07:12.796 [MainThread] INFO    thonny.plugins.micropython.mp_back: Prepared
00:07:12.796 [MainThread] INFO    thonny: TIME/MODS 0.000 after Run 
00:07:12.829 [MainThread] INFO    thonny: TIME/MODS 0.033 before get_globals 
00:07:12.829 [MainThread] INFO    thonny: TIME/MODS 0.000 befsubcode 
00:07:12.863 [MainThread] INFO    thonny: TIME/MODS 0.034 affsubcode 
00:07:13.004 [MainThread] INFO    thonny: TIME/MODS 0.141 affforw 
00:07:13.004 [MainThread] ERROR   thonny.backend: Exception while handling 'get_globals'
Traceback (most recent call last):
  File "E:\Program Files\Thonny\lib\site-packages\thonny\plugins\micropython\mp_back.py", line 582, in _evaluate
    value = ast.literal_eval(value_str)
  File "E:\Program Files\Thonny\lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "E:\Program Files\Thonny\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    {'mainLoopMouth': ('<function mainLoopMouth at 0x3ffd0880>', 1073547392), 'random': ("<module 'random'>", 1061205224), 'lo0
                                                                                                                           ^
SyntaxError: unterminated string literal (detected at line 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Program Files\Thonny\lib\site-packages\thonny\backend.py", line 285, in _handle_normal_command
    response = handler(cmd)
  File "E:\Program Files\Thonny\lib\site-packages\thonny\plugins\micropython\mp_back.py", line 653, in _cmd_get_globals
    globs = self._evaluate(
  File "E:\Program Files\Thonny\lib\site-packages\thonny\plugins\micropython\mp_back.py", line 584, in _evaluate
    raise ManagementError("Could not parse management response", script, out, err) from e
thonny.plugins.micropython.mp_back.ManagementError: Could not parse management response
00:07:13.005 [MainThread] ERROR   thonny.plugins.micropython.mp_back: ManagementError details:
SCRIPT: __thonny_helper.print_mgmt_value({name : (__thonny_helper.repr(value), __thonny_helper.builtins.id(value)) for (name, value) in __thonny_helper.builtins.globals().items() if not name.startswith('__')})

STDOUT: <thonny>{'mainLoopMouth': ('<function mainLoopMouth at 0x3ffd0880>', 1073547392), 'random': ("<module 'random'>", 1061205224), 'lo0

ck': ('<lock>', 1073547296), 'mainLoopFace': ('<function mainLoopFace at 0x3ffd0790>', 1073547152), 'openFile': ('<function openFile at 0x3ffd06b0>', 1073546928), 'bdev': ('<Partition type=1, subtype=129, address=2097152, s...', 1073545504), 'json': ("<module 'json'>", 1061204448), 'mouth': ('<function mouth at 0x3ffd0780>', 1073547136), 'Pin': ("<class 'Pin'>", 1061165660), 'clearFace': ('<function clearFace at 0x3ffd05e0>', 1073546720), 'neopixel': ("<module 'neopixel' from 'neopixel.py'>", 1073545360), '_thread': ("<module '_thread'>", 1061254180), 'gc': ("<module 'gc'>", 1061252188), 'time': ("<module 'time'>", 1061206452), 'np': ('<NeoPixel object at 3ffd05a0>', 1073546656), 'clearArray': ('<function clearArray at 0x3ffd05b0>', 1073546672), 'button3': ('Pin(5)', 1061169756), 'clearMouth': ('<function clearMouth at 0x3ffd05d0>', 1073546704), 'button2': ('Pin(4)', 1061169752), 'button1': ('Pin(21)', 1061169820), 'os': ("<module 'os'>", 1061204552), 'face': ('<function face at 0x3ffd0770>', 1073547120)}</thonny>

STDERR: 

```

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for late reply!

It looks like you have an object in a global variable, which has rather unusual `__repr__` representation: 

```
lo0

ck
```

Thonny expected the representation to be on a single line. I'll revisit this assumption.

Out of curiosity --  did you implement such `__repl__` yourself or it's from a library?
