### ISSUE TITLE
CANT INSTALL PACKAGES TO PICO USING THONNY

### ISSUE THREAD

**Issue by doingus** [thonny/thonny#2979]
install --progress-bar off micropython-servo
PROBLEM IN THONNY'S BACK-END: Exception while handling 'install_distributions' (AssertionError).
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.

See Thonny's backend.log for more info.

Process ended with exit code 1.
 I get this error everytime i try to install a package
 ive restarted multiple times

**Comment by doingus** [comment]
Traceback (most recent call last):
  File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 331, in _on_install_click
    self._perform_pip_action("install")
  File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 772, in _perform_pip_action
    if self._has_remote_target():
  File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 1006, in _has_remote_target
    return get_runner().get_backend_proxy().supports_remote_files()
AttributeError: 'NoneType' object has no attribute 'supports_remote_files'

**Comment by Sherzodbek1426** [comment]
Traceback (most recent call last):
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\tkinter_init_.py", line 1921, in call
return self.func(*args)
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 331, in _on_install_click
self._perform_pip_action("install")
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 772, in _perform_pip_action
if self._has_remote_target():
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 1006, in _has_remote_target
return get_runner().get_backend_proxy().supports_remote_files()
AttributeError: 'NoneType' object has no attribute 'supports_remote_files'

**Comment by Sherzodbek1426** [comment]
Traceback (most recent call last):
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\tkinter_init_.py", line 1921, in call
return self.func(*args)
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 331, in _on_install_click
self._perform_pip_action("install")
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 772, in _perform_pip_action
if self._has_remote_target():
File "C:\Users\HAHA\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 1006, in _has_remote_target
return get_runner().get_backend_proxy().supports_remote_files()
AttributeError: 'NoneType' object has no attribute 'supports_remote_files'

**Comment by illustratordavid** [comment]
Same issue for me in 4.1.3, downgrading to 4.1.2 installs same library fine

**Comment by doingus** [comment]
> Same issue for me in 4.1.3, downgrading to 4.1.2 installs same library fine

This worked for me as well thank you!

**Comment by jansierakowski** [comment]
For me 4.0.2 only works. Pico W with v1.21 uf2

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for the late reply! I could reproduce this and will fix it soon in version 4.1.4.

**Comment by aivarannamaa** [comment]
Please try https://github.com/thonny/thonny/releases/tag/v4.1.4
