### ISSUE TITLE
instalar pacotes

### ISSUE THREAD

**Issue by joaopfbatista321** [thonny/thonny#2994]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 331, in _on_install_click
    self._perform_pip_action("install")
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 772, in _perform_pip_action
    if self._has_remote_target():
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 1006, in _has_remote_target
    return get_runner().get_backend_proxy().supports_remote_files()
AttributeError: 'NoneType' object has no attribute 'supports_remote_files'

**Comment by aivarannamaa** [comment]
Please try https://github.com/thonny/thonny/releases/tag/v4.1.4
