### ISSUE TITLE
Error pressing the tab key

### ISSUE THREAD

**Issue by nissaba** [thonny/thonny#3057]
I am getting this error when pressing the tab key after a word. 

> Traceback (most recent call last):
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/tktextext.py", line 229, in dispatch
>     return fun(event)
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/tktextext.py", line 541, in perform_tab
>     return self.perform_midline_tab(event)
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/autocomplete.py", line 321, in patched_perform_midline_tab
>     _handle_autocomplete_request_for_text(text)
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/autocomplete.py", line 309, in _handle_autocomplete_request_for_text
>     text.autocompleter.handle_autocomplete_request()
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/autocomplete.py", line 58, in handle_autocomplete_request
>     filename=self._get_filename(),
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/running.py", line 274, in send_command
>     response = self._proxy.send_command(cmd)
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/__init__.py", line 184, in send_command
>     return super().send_command(cmd)
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/running.py", line 972, in send_command
>     self._send_msg(cmd)
>   File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/running.py", line 975, in _send_msg
>     self._proc.stdin.write(serialize_message(msg) + "\n")
> AttributeError: 'NoneType' object has no attribute 'stdin'

So I get this errort any time I press the tab key.

I am on a mac system on a M2 pro chip. 
using Thonny 3.3.13
this is my code 

```
import sys
import aioble
import bluetooth
import asyncio as asyncio
import machine 
from micropython import const

def uid():
    """ Return the unique id of the device as a string """
    return "{:20x}{:20x}{:20x}{:20x}{:20x}{:20x}{:20x}{:20x}".format(*machine.unique_id())

hardware = sys.implementation

MANUFACTURER_ID = const(0x02A29)
MODEL_NUMBER_ID = const(0x2A24)
SERIAL_NUMBER_ID = const(0x2A25)
HARDWARE_REVISION_ID = const(0x2A27)
FIRMWARE_REVISION_ID = const(0x2A26)
BLE_VERSION_ID = const(0x2A28)
_BASE_UUID = "9AFA{}-50F5-4766-8EE1-709073D6E258"
# live data services
_LIVE_DATA_SERVICE = bluetooth.UUID(_BASE_UUID.format("5B00"))
print(_LIVE_DATA_SERVICE)
_LIVE_DATA_STREAM = _BASE_UUID.format("B2E1")
print(_LIVE_DATA_STREAM)

# config services
_CONF_SERVICE = bluetooth.UUID(_BASE_UUID.format("5B03"))
_CONF_SMART_LIGHT_SETTING = _BASE_UUID.format("BEE4")
_CONF_VIBRATION_SETTING = _BASE_UUID.format("BEE0")
_CONF_OTHER_SETTINGS = _BASE_UUID.format("BEE2")
_CONF_AMB_LIGHT_SETTING = _BASE_UUID.format("BEE1")
_CONF_SET_BOOTLEADER = _BASE_UUID.format("BED1")
_CONF_FRONT_LIGHT_SETTING = _BASE_UUID.format("BEE3")
_CONF_REAR_LIGHT_SETTING = _BASE_UUID.format("BEE5")
# info services
_INFO_SERVICE = bluetooth.UUID(_BASE_UUID.format("5B04"))
_INFO_SERIAL_NUMBER = _BASE_UUID.format("B2D0")
_INFO_MODEL = _BASE_UUID.format("B2D1")
_INFO_YEAR = _BASE_UUID.format("B2D2")
_INFO_MODULE_SERIAL = _BASE_UUID.format("B2D3")
_INFO_FIRMWARE_V = _BASE_UUID.format("B2D4")
#DFU_SERVICE = _BASE_UUID.format("8d53dc1d-1db7-4cd3-868b-8a527460aa84")
#DFU_CHARACTERISTIC = _BASE_UUID.format("da2e7828-fbce-4e01-ae9e-261174997c48")

led = machine.Pin("LED", machine.Pin.OUT)

_GENERIC = bluetooth.UUID(0x1800)
_DEVICE_INFO = bluetooth.UUID(0x180A)

_BLE_APPEARENCE_GENERIC_REMOTE_CONTROL = const(284)

ADV_INTERVAL_MS = 250_000

device_info = aioble.Service(_DEVICE_INFO)

connection = None

# Create Characteristics for the device info
aioble.Characteristic(device_info, bluetooth.UUID(MANUFACTURER_ID), read = True, initial="My Strawberry Pi pico")
aioble.Characteristic(device_info, bluetooth.UUID(MODEL_NUMBER_ID), read = True, initial="DM.M.363A.2E.1")
aioble.Characteristic(device_info, bluetooth.UUID(SERIAL_NUMBER_ID), read = True, initial="8WER9875432SDF16587")
aioble.Characteristic(device_info, bluetooth.UUID(FIRMWARE_REVISION_ID), read = True, initial=sys.version)
aioble.Characteristic(device_info, bluetooth.UUID(HARDWARE_REVISION_ID), read = True, initial=hardware._machine)
aioble.Characteristic(device_info, bluetooth.UUID(BLE_VERSION_ID), read = True, initial="1.0")


# Register GATT server.
live_data_service = aioble.Service(_LIVE_DATA_SERVICE)
live_data_characteristic = aioble.Characteristic(
    live_data_service, bluetooth.UUID(_LIVE_DATA_STREAM), read=True, notify=True
)

config_service = aioble.Service(_CONF_SERVICE)
config_smart_light_setting_characteristic = aioble.Characteristic(config_service, bluetooth.UUID(_CONF_SMART_LIGHT_SETTING), write=True, read=True)
config_vibration_characteristic = aioble.Characteristic(config_service,bluetooth.UUID(_CONF_VIBRATION_SETTING), write=True, read=True)
config_other_settings_characteristic = aioble.Characteristic(config_service,bluetooth.UUID(_CONF_OTHER_SETTINGS), write=True, read=True)
config_amb_light_characteristic = aioble.Characteristic(config_service,bluetooth.UUID(_CONF_AMB_LIGHT_SETTING), write=True, read=True)
config_set_boothloader_characteristic = aioble.Characteristic(config_service,bluetooth.UUID(_CONF_SET_BOOTLEADER), write=True,)
config_front_light_characteristic = aioble.Characteristic(config_service,bluetooth.UUID(_CONF_FRONT_LIGHT_SETTING), write=True, read=True)
config_rear_light_characteristic = aioble.Characteristic(config_service,bluetooth.UUID(_CONF_REAR_LIGHT_SETTING), write=True, read=True)


print('Registering services')

aioble.register_services(device_info, live_data_service, config_service)

connected = False

async def peripheral_task():
    """ Task to handle peripheral """
    global connected, connection, ADV_INTERVAL_MS
    connected = False
    async with await  aioble.advertise(
        ADV_INTERVAL_MS,
        name="ARGON_DUMMY",
        appearance=_BLE_APPEARENCE_GENERIC_REMOTE_CONTROL,
        services=[_GENERIC,_DEVICE_INFO,_CONF_SERVICE]
    ) as connection:
        print("Connection from, ", connection.device)
        connected = True
        print("connected {connected}")
        await connection.disconnected()
        print("disconnected")
        
async def blink_task():
    """ Task to blink LED """
    toggle = True
    while True:
        if(connected):
            led.value(1)
        else:
            led.value(toggle)
            toggle = not toggle
        await asyncio.sleep_ms(250)
        
async def main():    
    t1 = asyncio.create_task(peripheral_task())
    t2 = asyncio.create_task(blink_task())
    await asyncio.gather(t1, t2)
    asyncio.	
    
asyncio.run(main())
```

**Comment by nissaba** [comment]
losing. my version was old.
