### ISSUE TITLE
ERROR: Running any code --> %Run -c $EDITOR_CONTENT

### ISSUE THREAD

**Issue by myasinarslan** [thonny/thonny#3072]
I can't test any code on thonny, it literally doesn't print. with the error below:

`>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/common.py", line 772, in read_one_incoming_message_str
    msg_str = line_reader()
KeyboardInterrupt
>>> `

**Comment by aivarannamaa** [comment]
Can you post a screenshot?
