### ISSUE TITLE
random bugs with opening files from micropython

### ISSUE THREAD

**Issue by asherevan** [thonny/thonny#3206]
When i'm trying to open a file from my micropython device (ESP32) it randomly gives me this error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 1711, in event_generate
    handler(event)
  File "/usr/lib/python3/dist-packages/thonny/base_file_browser.py", line 1001, in update_dir_data
    self.render_children_from_cache(msg["node_id"])
  File "/usr/lib/python3/dist-packages/thonny/base_file_browser.py", line 430, in render_children_from_cache
    raise RuntimeError("None data for %s" % path)
RuntimeError: None data for /main.py

**Comment by aivarannamaa** [comment]
Thanks for the report and sorry for late reply!

I'll investigate this later.
