### ISSUE TITLE
common.py crashes on linux

### ISSUE THREAD

**Issue by kr-g** [thonny/thonny#3277]
just checked out the latest thonny master baseline and merged 

during thonny startup i get the following 

```

07:30:18.881 [MainThread] ERROR   thonny.backend: Exception while handling 'get_environment_info'
Traceback (most recent call last):
  File "/home/benutzer/repo/thonny/thonny/backend.py", line 291, in _handle_normal_command
    response = handler(cmd)
  File "/home/benutzer/repo/thonny/thonny/plugins/cpython_backend/cp_back.py", line 428, in _cmd_get_environment_info
    base_executable=get_base_executable(),
  File "/home/benutzer/repo/thonny/thonny/common.py", line 408, in get_base_executable
    raise RuntimeError("Don't know how to locate base executable")
RuntimeError: Don't know how to locate base executable

```

when i replace this 

https://github.com/thonny/thonny/blob/7d128229f80ddd4ab9149aa218def580dc52d0b3/thonny/common.py#L403

just with returning the executable

`
return sys.executable
`

thonny starts up properly again. 

probably there is a good reason why you dont use sys.executable directly ?!?!

remark:

using thonny with own .venv and python executable

**Comment by aivarannamaa** [comment]
Thanks for the report and sorry for the late reply!

I'll try to fix this before 5.0
