### ISSUE TITLE
Popup appears when i finish running my code (not harmful just annoying)

### ISSUE THREAD

**Issue by GitTimohus** [thonny/thonny#3300]
Traceback (most recent call last):
  File "C:\Users\timot\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1788, in event_generate
    handler(event)
  File "C:\Users\timot\AppData\Local\Programs\Thonny\lib\site-packages\thonny\assistance.py", line 143, in handle_toplevel_response
    self._start_program_analyses(
  File "C:\Users\timot\AppData\Local\Programs\Thonny\lib\site-packages\thonny\assistance.py", line 277, in _start_program_analyses
    analyzer.start_analysis(main_file_path, imported_file_paths)
  File "C:\Users\timot\AppData\Roaming\Thonny\plugins\Python310\site-packages\thonnycontrib\error-explainer\__init__.py", line 11, in start_analysis
    found_errors = error_explainer.check_runner.run_checks(main_file_path)
  File "C:\Users\timot\AppData\Roaming\Thonny\plugins\Python310\site-packages\error_explainer\check_runner.py", line 107, in run_checks
    run_checks_map(force_checks, filename, last_level)
  File "C:\Users\timot\AppData\Roaming\Thonny\plugins\Python310\site-packages\error_explainer\check_runner.py", line 82, in run_checks_map
    checks_map[level].get(c).run(filename)
  File "C:\Users\timot\AppData\Roaming\Thonny\plugins\Python310\site-packages\error_explainer\check.py", line 11, in run
    self.function(*kwargs)
  File "C:\Users\timot\AppData\Roaming\Thonny\plugins\Python310\site-packages\error_explainer\check_runner.py", line 422, in coma_instead_of_period_check
    coma_check_res = check_coma_used_instead_of_period(root_node)
  File "C:\Users\timot\AppData\Roaming\Thonny\plugins\Python310\site-packages\error_explainer\checks.py", line 271, in check_coma_used_instead_of_period
    if utils.is_bad_coma_usage(code):
  File "C:\Users\timot\AppData\Roaming\Thonny\plugins\Python310\site-packages\error_explainer\utils.py", line 152, in is_bad_coma_usage
    if len(should_be_var_names) == 1:
TypeError: object of type 'NoneType' has no len()

This is the code i was running incase it was a user error (yes its an intro to programming assignment im new)

[ThonnyIssue.zip](https://github.com/user-attachments/files/16883429/ThonnyIssue.zip)

**Comment by aivarannamaa** [comment]
Thanks for the report and sorry for the late reply!

The corresponding part of Thonny will be changed in Thonny 5.0 and your error will be gone then.
