### ISSUE TITLE
Theme error 

### ISSUE THREAD

**Issue by selmen2004** [thonny/thonny#3305]
If using interface Theme "Tidy Light A" with syntax Theme "Tomorrow"   ( maybe more combinations cause same issue ) 
when trying to open object inspector 

`Traceback (most recent call last):
  File "C:\Users\selme\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\workbench.py", line 1280, in dispatch_from_menu
    dispatch(None)
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\workbench.py", line 1206, in dispatch
    handler()
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\workbench.py", line 1383, in toggle_view_visibility
    self.show_view(view_id, True)
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\workbench.py", line 1924, in show_view
    view = self.get_view(view_id)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\workbench.py", line 1823, in get_view
    view = class_(self._main_pw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\plugins\object_inspector.py", line 27, in __init__
    self._create_content_page()
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\plugins\object_inspector.py", line 142, in _create_content_page
    ElementsInspector(self.content_page),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\plugins\object_inspector.py", line 528, in __init__
    thonny.memory.MemoryFrame.__init__(
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\memory.py", line 28, in __init__
    TreeFrame.__init__(
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\ui_utils.py", line 566, in __init__
    heading_stripe = check_create_heading_stripe(self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\selme\Desktop\thonny.last\thonny_git\Lib\site-packages\thonny\ui_utils.py", line 2580, in check_create_heading_stripe
    if px_to_hide > 0 and background is not None:
       ^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
`

**Comment by aivarannamaa** [comment]
Thank you for the report and sorry for the late reply!

This part of code have been acting strangely and I don't understand why. I added some defensive programming now. Hopefully this fixes your case as well.
