### ISSUE TITLE
Numpy and matplotlib do not run on Rpi 5

### ISSUE THREAD

**Issue by Alphina1** [thonny/thonny#3317]
On a fresh RPi5 image I've created a new virtual environment through Thonny under options, and then installed Matplotlib through the package manager. Running the simple one line script: 

"import matplotlib"

I get the following error:

"
Traceback (most recent call last):
  File "/home/lab/myENV/lib/python3.11/site-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/lab/myENV/lib/python3.11/site-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/lab/myENV/lib/python3.11/site-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lab/myENV/lib/python3.11/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/home/lab/myENV/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/home/lab/myENV/lib/python3.11/site-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/home/lab/myENV/bin/python3"
  * The NumPy version is: "2.1.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lab/test.py", line 1, in <module>
    import matplotlib
  File "/home/lab/myENV/lib/python3.11/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/home/lab/myENV/lib/python3.11/site-packages/matplotlib/cbook.py", line 24, in <module>
    import numpy as np
  File "/home/lab/myENV/lib/python3.11/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
"

I've followed the instructions listed on the referenced numpy website and it is still not running. Similarly, when I try installing just numpy and importing numpy, I get the same result.

I've tried it on two different Raspberry Pi 5's on fresh images, again, with the same results. 

I ran through the same exact steps on macOS and it works perfectly, so the common denominator is the RPi 5.

After many days, forums posts, and all the troubleshooting advice, I have been unable to get matplotlib or numpy to run. Any help would be greatly appreciated.

**Comment by aivarannamaa** [comment]
I don't think this error is specific to Thonny, unless you can use the same venv outside of Thonny.
