### ISSUE TITLE
Thonny Back internal error + can't start programms + can't  insert packs

### ISSUE THREAD

**Issue by teachi-afk** [thonny/thonny#3320]
Hi,

i reinstalled thonny and now it doesn't work at all. I get this error and can't solve it. Other threads had the same error, but none given solution solved my problem. I autoinstalled it under C:.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\workbench.py", line 2027, in toolbar_handler
    handler(*args)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 602, in cmd_stop_restart
    self.restart_backend(clean=True)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 731, in restart_backend
    self._proxy = backend_class(clean)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\plugins\cpython_frontend\cp_front.py", line 37, in __init__
    super().__init__(clean, executable)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 999, in __init__
    self._start_background_process(clean=clean)
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\running.py", line 1093, in _start_background_process
    self._proc = subprocess.Popen(
  File "C:\Program Files (x86)\Thonny\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files (x86)\Thonny\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] Falscher Parameter

PLS Help. TY

**Comment by aivarannamaa** [comment]
Which Windows version and which Thonny version are you using? 

Similar to #3302, #3287, #2917
