### ISSUE TITLE
Thonny 4.1.6 internal error on Mac Book Air & Ubuntu 24.04.1 

### ISSUE THREAD

**Issue by YachtMango** [thonny/thonny#3375]
When trying to install Micropython on a Pico get errors below.

Run | Configure interpreter | Install or update Micropython link  gives internal error box 

Traceback (most recent call last):
  File "/snap/thonny/238/lib/python3.10/site-packages/thonny/misc_utils.py", line 104, in list_volumes
    from dbus_next.errors import DBusError
ModuleNotFoundError: No module named 'dbus_next'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/thonny/238/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/snap/thonny/238/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/snap/thonny/238/lib/python3.10/site-packages/thonny/workdlg.py", line 216, in _keep_updating_ui
    self.update_ui()
  File "/snap/thonny/238/lib/python3.10/site-packages/thonny/plugins/micropython/base_flashing_dialog.py", line 147, in update_ui
    targets = self.find_targets()
  File "/snap/thonny/238/lib/python3.10/site-packages/thonny/plugins/micropython/uf2dialog.py", line 33, in find_targets
    for vol in list_volumes(skip_letters=["A"])
  File "/snap/thonny/238/lib/python3.10/site-packages/thonny/misc_utils.py", line 107, in list_volumes
    return list_volumes_with_mount_command()
  File "/snap/thonny/238/lib/python3.10/site-packages/thonny/misc_utils.py", line 125, in list_volumes_with_mount_command
    mount_output = subprocess.check_output("mount").splitlines()
  File "/snap/thonny/238/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/snap/thonny/238/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/snap/thonny/238/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/thonny/238/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'mount'

**Comment by aivarannamaa** [comment]
dbus_next was omitted from 4.1.6 by accident. Please try 4.1.7 and reopen if you still have problems.
