### ISSUE TITLE
4.1.6 MacOS 14.6.1 can't import packages

### ISSUE THREAD

**Issue by cnoblejr** [thonny/thonny#3376]
import numpy as np get 
Traceback (most recent call last):
  File "/Users/carlnoble27/Desktop/supersolvers/MNIIST01.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
>>> PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_active_distributions' (ModuleNotFoundError: No module named 'pkg_resources').
See Thonny's backend.log for more info.

Process ended with exit code 1.

**Comment by cnoblejr** [comment]
uninstalled Thonny and installed new version.  same will not allow imports.  Just happened.

**Comment by cnoblejr** [comment]
was running python 3.12 went back to 3.10 and dumpy and pandas imported ok but matplotlib  gave this:

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_launcher.py", line 69, in <module>
    MainCPythonBackend(target_cwd, options).mainloop()
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/backend.py", line 87, in mainloop
    self._handle_normal_command(msg)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 273, in _handle_normal_command
    super()._handle_normal_command(cmd)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/backend.py", line 285, in _handle_normal_command
    response = handler(cmd)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 449, in _cmd_Run
    return self._execute_file(cmd, SimpleRunner)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 839, in _execute_file
    result_attributes = self._execute_source(
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 853, in _execute_source
    return self._current_executor.execute_source(
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 1307, in execute_source
    return self._execute_prepared_user_code(statements, global_vars)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 1259, in wrapper
    result = method(self, *args, **kwargs)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 1246, in wrapper
    return method(self, *args, **kwargs)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 1314, in _execute_prepared_user_code
    exec(statements, global_vars)
  File "/Users/carlnoble27/Desktop/supersolvers/MNIIST01.py", line 5, in <module>
    from matplotlib import pyplot as plt
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 353, in _custom_import
    module = self._original_import(*args, **kw)
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 353, in _custom_import
    module = self._original_import(*args, **kw)
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 353, in _custom_import
    module = self._original_import(*args, **kw)
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 353, in _custom_import
    module = self._original_import(*args, **kw)
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 353, in _custom_import
    module = self._original_import(*args, **kw)
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 353, in _custom_import
    module = self._original_import(*args, **kw)
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox, update_path_extents)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/thonny/plugins/cpython_backend/cp_back.py", line 353, in _custom_import
    module = self._original_import(*args, **kw)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/Users/carlnoble27/Desktop/supersolvers/MNIIST01.py", line 5, in <module>
    from matplotlib import pyplot as plt
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/Users/carlnoble27/Library/Python/3.10/lib/python/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox, update_path_extents)
ImportError: numpy.core.multiarray failed to import
>>>

**Comment by cnoblejr** [comment]
ALL FIXED   (via chatGPT 40)
found path to Thonny app with python script 
import sys
print(sys.executable)

then used that path  (in terminal)

<path_to_thonny_python> -m pip install numpy==1.24.0. and reinstalled Matplotlib via  tools/manage plugins, the normal way

then back to terminal

<path_to_thonny_python> -m pip install --upgrade --force-reinstall matplotlib

Now can import Matplotlib in Python scripts.
