### ISSUE TITLE
ERROR   thonny.workbench: Problem when handling 'LanguageServerInitialized'

### ISSUE THREAD

**Issue by abouatef** [thonny/thonny#3388]
00:00:00.131 [MainThread] ERROR   thonny.workbench: Problem when handling 'LanguageServerInitialized'
Traceback (most recent call last):
  File "\thonny-master\thonny\workbench.py", line 2258, in event_generate
    handler(event)
    ~~~~~~~^^^^^^^
  File "\thonny-master\thonny\editors.py", line 678, in _language_server_initialized
    self._try_connect_to_language_server()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "\thonny-master\thonny\editors.py", line 684, in _try_connect_to_language_server
    if not is_local_path(self._filename):
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "\thonny-master\thonny\common.py", line 809, in is_local_path
    return not is_remote_path(s) and not s.startswith("<")
               ~~~~~~~~~~~~~~^^^
  File "\thonny-master\thonny\common.py", line 805, in is_remote_path
    return REMOTE_PATH_MARKER in s
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by aivarannamaa** [comment]
Please re-open if you still have the same problem with current tip of the master.
