### ISSUE TITLE
No longer able to use SSH - cp_launcher.py file not present

### ISSUE THREAD

**Issue by StrawFruit** [thonny/thonny#3415]
Hello,

i used Thonny to SSH into a RPi Zero, yesterday evening and for s short period this morning, then it stopped working with following error message. I tried to reinstall some stuff, but i am unable to SSH again :/

I installed Thonny through the bash script given on HP, also tried to install it 'pip install thonny' and in Discover. The first two give following error about 'launch.py' not present. Actually the whole folder-path is missing.

`Traceback (most recent call last):
  File "/home/tob/.local/lib/python3.12/site-packages/thonny/plugins/cpython_ssh/cps_back.py", line 213, in <module>
    backend = SshCPythonBackend(**args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tob/.local/lib/python3.12/site-packages/thonny/plugins/cpython_ssh/cps_back.py", line 45, in __init__
    self._proc = self._start_main_backend()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tob/.local/lib/python3.12/site-packages/thonny/plugins/cpython_ssh/cps_back.py", line 153, in _start_main_backend
    return self._create_remote_process(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tob/.local/lib/python3.12/site-packages/thonny/backend.py", line 820, in _create_remote_process
    raise RuntimeError(f"Got {ack!r} instead of expected {PROCESS_ACK!r}")
RuntimeError: Got "python3: can't open file '/tmp/thonny-backend-4.1.7-tob/thonny/plugins/cpython_backend/cp_launcher.py': [Errno 2] No such file or directory" instead of expected 'OK'

Process ended with exit code 1.`

With the Discover Thonny i am unable to meet the paramiko dependency. Thonny Tools shows the folderpath for paramiko at ' /app/lib ...' while it would be in '/usr/lib...'

Unfortunately i am clueless how to bug search or fix this.

**Comment by StrawFruit** [comment]
It works again, not with all versions of Thonny present on my machine, but at least with one. I don't really now why or where the working version is installed from or too :/

What i did:

1. I found this install methode: 'sudo dnf install python3-tkinter thonny', which at did no help.
2. i fiddled around with the Discover Thonny, and found out that Discover somehow has two different ones
3. I tried to install the 2nd with an error
4. after that i uninstalled the other. So now i should not have a discover thonny
5. Press 'Super' and typ 'thonny' to start the software from there
6. It Worked! i can SSH again

- Starting Thonny from Terminal still gives the Error and no SSH connection
- Right klicking Thonny in the 'Super Menu' and selecting 
--  'Manage Add-Ons...' opens discover, where Thonny is shown as NOT installed.
-- 'Edit Application' shows the path as '/usr/bin/thonny' and owner and group as root
- /tmp folderpath is still not present

If someone reads through all this, thanks a lot. Please feel free to ask anything related, or just delet this. I don't know how or what happend, but it is working (for now).

have nice holidays!
