### ISSUE TITLE
Slow shell in case of error

### ISSUE THREAD

**Issue by commongeek** [thonny/thonny#3421]
Shell becomes very slow when using a non-existent variable or function if there are a lot (or large) variables in memory:
```
Python 3.12.7 (C:\Users\Administrator\miniforge3\python.exe)

>>> # this is fast
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined

>>> data = [i for i in range(10000000)]

>>> # this is slow
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
```

**Comment by aivarannamaa** [comment]
Thank you for the report! 

I'll investigate this later.
