### ISSUE TITLE
Permission Errors on Mac

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#600]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/600) by Anonymous.**

----------------------------------------

```
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/__init__.py", line 51, in launch
    if _should_delegate():
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/__init__.py", line 129, in _should_delegate
    configuration_manager = try_load_configuration(workbench.CONFIGURATION_FILE_NAME)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/config.py", line 18, in try_load_configuration
    return ConfigurationManager(filename)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/config.py", line 45, in __init__
    with open(self._filename, "r", encoding="UTF-8") as fp:
PermissionError: [Errno 13] Permission denied: '/Users/mihai/Library/Thonny/configuration.ini'
```

Thonny works fine if I run it with sudo in the command line.

**Comment by aivarannamaa** [comment]
Closing as lot has changed in the macOS build
