### ISSUE TITLE
Cannot install plugin from zip

### ISSUE THREAD

**Issue by alexmojaki** [thonny/thonny#657]
Trying to install birdseye.zip provided [here](https://github.com/thonny/thonny/pull/647#issuecomment-454568753) using "Install from local file" shows a dialog with this error:

```
Processing /Users/alexhall/Downloads/thonny-birdseye.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/3j/4_sfj3bx0d308nn017z4n3j00000gp/T/pip-req-build-exgiucq1/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3j/4_sfj3bx0d308nn017z4n3j00000gp/T/pip-req-build-exgiucq1/


Return code: 
```

**Comment by aivarannamaa** [comment]
Sorry for the confusion.

This zip only contains code, but plug-in dialog assumes a whl or something else which is pip-installable.
