### ISSUE TITLE
File save cancel generates an error.

### ISSUE THREAD

**Issue by peterdcasey** [thonny/thonny#692]
When running / saving a new file <untitled> and selecting Cancel, an error window pops up with the error below. (Windows v3.1.2>
=================================================
Traceback (most recent call last):
  File "C:\Users\pcasey\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\pcasey\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 317, in _cmd_run_current_script
    self.execute_current("Run")
  File "C:\Users\pcasey\AppData\Local\Programs\Thonny\lib\site-packages\thonny\running.py", line 282, in execute_current
    script_dir = normpath_with_actual_case(os.path.dirname(filename))
  File "C:\Users\pcasey\AppData\Local\Programs\Thonny\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "C:\Users\pcasey\AppData\Local\Programs\Thonny\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by aivarannamaa** [comment]
Fixed in #714
