### ISSUE TITLE
Debugger fails with conditional list comprehension

### ISSUE THREAD

**Issue by ronniejoshua** [thonny/thonny#737]
```
list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]

common_num = [a for a in list_a for b in list_b if a == b]

```

While debugging this just to understand/test the code I got the following error.

```
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/workbench.py", line 1449, in event_generate
    handler(event)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/debugger.py", line 1055, in _handle_debugger_progress
    _current_debugger.handle_debugger_progress(msg)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/debugger.py", line 152, in handle_debugger_progress
    self.bring_out_frame(self._last_progress_message.stack[-1].id, force=True)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/debugger.py", line 187, in bring_out_frame
    self._last_progress_message, frame_info
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/debugger.py", line 521, in _update_this_frame
    FrameVisualizer._update_this_frame(self, msg, frame_info)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/debugger.py", line 389, in _update_this_frame
    self._tag_range(frame_info.current_statement, stmt_tag)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/debugger.py", line 424, in _tag_range
    "%d.0" % self._translate_lineno(text_range.lineno),
AttributeError: 'NoneType' object has no attribute 'lineno'
```

**Comment by aivarannamaa** [comment]
Thank you for the report!

Unfortunately it's really hard to visualize evaluation of comprehensions. I'll disable stepping into comprehensions if there are more than 1 generators.
