### ISSUE TITLE
Unplugging CP device in Mac or Linux gives stacktrace

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#802]
```
>>> %cd /sounds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '__module_os' is not defined
>>> ERROR:root:Error while reading from serial
Traceback (most recent call last):
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serial/serialposix.py", line 493, in read
    buf = os.read(self.fd, size - len(read))
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/serial_connection.py", line 62, in _listen_serial
    data += self._serial.read(1)  # To avoid busy loop
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: [Errno 6] Device not configured
ERROR:thonny.micropython.backend:Crash in backend
Traceback (most recent call last):
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 114, in _mainloop
    cmd = self._command_queue.get(timeout=0.1)
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 89, in __init__
    self._mainloop()
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 124, in _mainloop
    self._check_for_idle_events()
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 547, in _check_for_idle_events
    self._send_output(self._connection.read_all().decode(ENCODING, "replace"), "stdout")
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/connection.py", line 95, in read_all
    self._check_for_error()
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/connection.py", line 110, in _check_for_error
    raise RuntimeError(self._error)
RuntimeError: Serial reading error: read failed: [Errno 6] Device not configured
Traceback (most recent call last):
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 114, in _mainloop
    cmd = self._command_queue.get(timeout=0.1)
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 89, in __init__
    self._mainloop()
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 124, in _mainloop
    self._check_for_idle_events()
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/backend.py", line 547, in _check_for_idle_events
    self._send_output(self._connection.read_all().decode(ENCODING, "replace"), "stdout")
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/connection.py", line 95, in read_all
    self._check_for_error()
  File "/Users/aivar/Desktop/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/thonny/plugins/micropython/connection.py", line 110, in _check_for_error
    raise RuntimeError(self._error)
RuntimeError: Serial reading error: read failed: [Errno 6] Device not configured

Backend terminated or disconnected. Use 'Stop/Restart' to restart ...

```

**Comment by aivarannamaa** [comment]
From Linux:

```
>>> ERROR:root:Error while reading from serial
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/thonny/thonny/plugins/micropython/serial_connection.py", line 64, in _listen_serial
    data += self._serial.read(1)  # To avoid busy loop
  File "/usr/local/lib/python3.7/dist-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
ERROR:thonny.micropython.backend:Crash in backend
Traceback (most recent call last):
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 128, in _mainloop
    cmd = self._command_queue.get(timeout=0.1)
  File "/usr/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 101, in __init__
    self._mainloop()
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 138, in _mainloop
    self._check_for_idle_events()
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 605, in _check_for_idle_events
    self._send_output(self._connection.read_all().decode(ENCODING, "replace"), "stdout")
  File "/home/pi/thonny/thonny/plugins/micropython/connection.py", line 95, in read_all
    self._check_for_error()
  File "/home/pi/thonny/thonny/plugins/micropython/connection.py", line 110, in _check_for_error
    raise RuntimeError(self._error)
RuntimeError: Serial reading error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Traceback (most recent call last):
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 128, in _mainloop
    cmd = self._command_queue.get(timeout=0.1)
  File "/usr/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 101, in __init__
    self._mainloop()
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 138, in _mainloop
    self._check_for_idle_events()
  File "/home/pi/thonny/thonny/plugins/micropython/backend.py", line 605, in _check_for_idle_events
    self._send_output(self._connection.read_all().decode(ENCODING, "replace"), "stdout")
  File "/home/pi/thonny/thonny/plugins/micropython/connection.py", line 95, in read_all
    self._check_for_error()
  File "/home/pi/thonny/thonny/plugins/micropython/connection.py", line 110, in _check_for_error
    raise RuntimeError(self._error)
RuntimeError: Serial reading error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

Backend terminated or disconnected. Use 'Stop/Restart' to restart ...


```

**Comment by aivarannamaa** [comment]
Restart recommendation is not given in Windows

**Comment by aivarannamaa** [comment]
Needs to be tested in Linux/Mac
