### ISSUE TITLE
Error when saving on the desktop

### ISSUE THREAD

**Issue by Jpn287** [thonny/thonny#833]
Hello.
When I try to save my python file this pop out :
![image](https://user-images.githubusercontent.com/48772756/62299342-10f25100-b475-11e9-9033-f29a6cc549f5.png)

> _File not found. Verify it's name and try again_

But I'm only trying to save as, not to find a file...
Can you help ? ^^

**Comment by aivarannamaa** [comment]
Hi!

That's strange. Do you have any special characters in your user name? Can you save outside of your home directory? Can you save directly into your home directory (ie. the parent directory of Documents)?

**Comment by Jpn287** [comment]
No same username than on Git. I tried to save on desktop and I will try in the parent directory. I will come back on this after that.

**Comment by Jpn287** [comment]
Hi, @aivarannamaa.
Yes **saving into the parent folder solved the problem**. I don't understand what caused this dysfunction.
Cordially.

**Comment by aivarannamaa** [comment]
@Jpn287, can you please post the output of following program:

```
import os.path

home = os.path.expanduser("~")
print("Home:", home)
print("Documents exists:", os.path.exists(os.path.join(home, "Documents")))
print("Desktop exists:", os.path.exists(os.path.join(home, "Desktop")))

```

**Comment by Jpn287** [comment]
### Here it is :
```Traceback (most recent call last):
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 601, in _cmd_save_file
    self.get_current_editor().save_file()
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 240, in save_file
    f.flush()
OSError: [Errno 9] Bad file descriptor
```

Thanks for your hard work

**Comment by Jpn287** [comment]
When launching into Thonny : 
```
Home: C:\Users\japan
Documents exists: True
Desktop exists: True
```
And when trying to save : 

``` 
Traceback (most recent call last):
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 819, in dispatch_from_menu
    dispatch(None)
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 777, in dispatch
    handler()
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 613, in _cmd_save_file_as
    self.get_current_editor().save_file(ask_filename=True)
  File "C:\Users\japan\AppData\Local\Programs\Thonny\lib\site-packages\thonny\code.py", line 240, in save_file
    f.flush()
OSError: [Errno 9] Bad file descriptor
```
Thanks for your hard work.

**Comment by aivarannamaa** [comment]
Do you have a single user PC, or a classroom computer with shared disks or something like this?

**Comment by Jpn287** [comment]
Only a single user PC W10.

**Comment by aivarannamaa** [comment]
At the moment I don't have any new ideas how to reproduce it.

**Comment by Jpn287** [comment]
Si for now I will close the thread because for now it seems to be a unilateral case. Thanks for all if I get any news I will come back.

**Comment by aivarannamaa** [comment]
It's OK if we leave it open. I'll just move it to next milestone when required.

**Comment by aivarannamaa** [comment]
Can you write to your Documents using following Python script in Thonny (can be pasted to Thonny's shell, if you can't save it to a script):

```
f = open(r"C:\Users\japan\Documents\test.txt", "w")
f.write("testing")
f.close()
```

?

**Comment by aivarannamaa** [comment]
@Jpn287 , did you find a solution?

**Comment by Jpn287** [comment]
> @Jpn287 , did you find a solution?

No but I thought that because I’m not using Thonny I should close the issue. Is it okay ?

**Comment by aivarannamaa** [comment]
I'll leave it open so I can find it more easily when same problem pops up again.
