### ISSUE TITLE
MP interrupt not working

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#838]

**Comment by aivarannamaa** [comment]
Still has problems (on micro:bit sometimes gives ugly stacktrace sometimes doesn't work). Stop/restart does.

**Comment by aivarannamaa** [comment]
```
x: 0, y: 112
x: -16, y: 96
x: -16, y: 96
x: 0, y: 112
x: -16, y: 112
x: 0, y: 96
x: -16, y: 96
Traceback (most recent call last):
  File "__main__", line 16, in <module>
KeyboardInterrupt: 
MicroPython v1.9.2-34-gd64154c73 on 2017-09-01; micro:bit v1.0.1 with nRF51822
Type "help()" for more information.
Crash in backend
Traceback (most recent call last):
  File "D:\workspaces\python_stuff\thonny\thonny\plugins\micropython\backend.py", line 98, in __init__
    self._prepare(clean)
  File "D:\workspaces\python_stuff\thonny\thonny\plugins\micropython\backend.py", line 115, in _prepare
    self._builtin_modules = self._fetch_builtin_modules()
  File "D:\workspaces\python_stuff\thonny\thonny\plugins\micropython\backend.py", line 163, in _fetch_builtin_modules
    assert not err, "Error was: %r" % err
AssertionError: Error was: 'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nKeyboardInterrupt: \r\n'
Traceback (most recent call last):
  File "D:\workspaces\python_stuff\thonny\thonny\plugins\micropython\backend.py", line 98, in __init__
    self._prepare(clean)
  File "D:\workspaces\python_stuff\thonny\thonny\plugins\micropython\backend.py", line 115, in _prepare
    self._builtin_modules = self._fetch_builtin_modules()
  File "D:\workspaces\python_stuff\thonny\thonny\plugins\micropython\backend.py", line 163, in _fetch_builtin_modules
    assert not err, "Error was: %r" % err
AssertionError: Error was: 'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nKeyboardInterrupt: \r\n'

Backend terminated or disconnected. Use 'Stop/Restart' to restart ...

```

**Comment by aivarannamaa** [comment]
Superseded by #1147
