### ISSUE TITLE
AttributeError: 'ESP32Proxy' object has no attribute 'micropython_upload_enabled'

### ISSUE THREAD

**Issue by ShenTengTu** [thonny/thonny#845]
I found that vesion 3.2.0rc1 has some new projects that need to be translated, so I updated the project and related modules (including the `thonny` module) and edited the translation file.

When I preview the GUI in ESP32 interpreter mode and keep the connection to the ESP32 board, if I click on the item in the menu bar above, the following error would occur:
```
ERROR: Internal error
Traceback (most recent call last):
  File "D:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "d:\MainWorkSpace\WORKPROJECT\CONTRIBUTING\thonny\thonny\workbench.py", line 1364, in <lambda>
    menu["postcommand"] = lambda: self._update_menu(menu, name)
  File "d:\MainWorkSpace\WORKPROJECT\CONTRIBUTING\thonny\thonny\workbench.py", line 1971, in _update_menu
    if tester and not tester():
  File "C:\Users\Shen-Teng Tu\AppData\Roaming\Python\Python37\Python37\site-packages\thonnycontrib\esp\__init__.py", line 120, in erase_flash_enabled
    and get_runner().get_backend_proxy().micropython_upload_enabled)
AttributeError: 'ESP32Proxy' object has no attribute 'micropython_upload_enabled'
```

If the connection is closed, it will work normally.

-----

By the way, the `File browser for MicroPython backends` is really convenient, thank a lot!! :thumbsup:

**Comment by aivarannamaa** [comment]
Thanks for the report!

I need to update the ESP plug-in. In the meanwhile please use "MicroPython (generic)" back-end instead.
