### ISSUE TITLE
[Ubuntu 18.04] can't launch without sudo

### ISSUE THREAD

**Issue by NooneAtAll** [thonny/thonny#865]
If I open through Ubuntu Software, icon on taskbar or through terminal without `sudo` I get error:

> ERROR:root:Internal error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/__init__.py", line 24, in launch
    if _should_delegate():
  File "/usr/lib/python3/dist-packages/thonny/__init__.py", line 112, in _should_delegate
    configuration_manager = try_load_configuration(workbench.CONFIGURATION_FILE_NAME)
  File "/usr/lib/python3/dist-packages/thonny/config.py", line 13, in try_load_configuration
    return ConfigurationManager(filename)
  File "/usr/lib/python3/dist-packages/thonny/config.py", line 34, in __init__
    with open(self._filename, 'r', encoding="UTF-8") as fp:
PermissionError: [Errno 13] Permission denied: '/home/NooneAtAll/.thonny/configuration.ini'

If I launch with `sudo` it works without issues

Clean install from Ubuntu Software  

Anything I can do to let it access its own files?

**Comment by aivarannamaa** [comment]
Can you check the ownership of `/home/NooneAtAll/.thonny` and its content? (`ls -la`)

If they are owned by root, then maybe you ran Thonny with `sudo` first time?

You can fix ownership with https://www.computerhope.com/unix/uchown.htm
