### ISSUE TITLE
Import problem after interpreter change

### ISSUE THREAD

**Issue by RamilAkhmetov** [thonny/thonny#879]
I 've changed python 3.7.2 interpreter on alternative python 3.5 and immediately got an error: 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\backend_launcher.py", line 30, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Program Files (x86)\Thonny\lib\site-packages\thonny\__init__.py", line 4, in <module>
    from typing import TYPE_CHECKING, cast, Optional
ImportError: cannot import name 'TYPE_CHECKING'
Backend terminated (returncode: 1)
Use 'Stop/Restart' to restart the backend ...

Help, please, Thank somebody in advance

**Comment by aivarannamaa** [comment]
Are you sure it's Python 3.5? It should have this name (https://docs.python.org/3.5/library/typing.html#typing.TYPE_CHECKING)
