### ISSUE TITLE
f-string error on debugger (V3.2.1)

### ISSUE THREAD

**Issue by toddprittie** [thonny/thonny#898]
V3.2.1
Windows 10(64)
3.7.4(32)

x = 'world'
print(f'Hello {x}!')

Traceback (most recent call last):
  File "C:\Thonny\lib\site-packages\thonny\workbench.py", line 1579, in event_generate
    handler(event)
  File "C:\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 1095, in _handle_debugger_progress
    _current_debugger.handle_debugger_progress(msg)
  File "C:\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 248, in handle_debugger_progress
    self._main_frame_visualizer.update_this_and_next_frames(msg)
  File "C:\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 373, in update_this_and_next_frames
    self._update_this_frame(msg, frame_info)
  File "C:\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 556, in _update_this_frame
    FrameVisualizer._update_this_frame(self, msg, frame_info)
  File "C:\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 432, in _update_this_frame
    self._expression_box.update_expression(msg, frame_info)
  File "C:\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 619, in update_expression
    whole_source, frame_info.filename, frame_info.current_root_expression
  File "C:\Thonny\lib\site-packages\thonny\plugins\debugger.py", line 717, in _load_expression
    index2 = _create_index(node.end_lineno, node.end_col_offset)
AttributeError: 'Str' object has no attribute 'end_lineno'

**Comment by aivarannamaa** [comment]
Thanks you for the report! I'll try to solve it later.
