### ISSUE TITLE
Nicer debugger fails when run with breakpoints only in secondary files

### ISSUE THREAD

**Issue by FluffyDuckKey** [thonny/thonny#986]
```
def count_letter(word, char):
    count = 0
    for letter in word:
        if letter == char:
            count += 1
    print("There are {} {}'s in {}".format(count, char, word))
count_letter('fanta', 'a')
```

returns: 

```
>>> %Debug Pb3.py
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 1575, in _trace
    return self._trace_and_catch(frame, event, arg)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 1620, in _trace_and_catch
    self._handle_progress_event(frame.f_back, event, marker_function_args, node)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 1664, in _handle_progress_event
    self._save_current_state(frame, event, args, node)
  File "C:\Users\User\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 1676, in _save_current_state
    custom_frame = self._custom_stack[-1]
IndexError: list index out of range
There are 2 a's in fanta
```

in Debug mode

however it returns:

```
%Run Pb3.py
There are 2 a's in fanta
```

in normal run mode - Im only new to learning python, so cant actually debug what the issue is in backend.py. Thanks!

Okay, I've figured out why it happened, but it may still need fixing:

I had another py file open - and within that file, I had a stop point in it, but I was trying to debug my adjoining py file.

**Comment by aivarannamaa** [comment]
Thank you for the report and interpretation, I'll look into it.
