### ISSUE TITLE
Error, when closing package management dialog quickly

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#989]
... ie. before the list gets populated.

```
Traceback (most recent call last):
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\site-packages\thonny\workbench.py", line 1582, in event_generate
    handler(event)
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 798, in _complete_update_list
    self._set_state("idle", True)
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\pip_gui.py", line 223, in _set_state
    self.config(cursor="")
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!backendpipdialog3"


```

**Comment by aivarannamaa** [comment]
Can't reproduce anymore
